"""Writing `content_context.json`: what subject an instance is about, in prose.

The artifact has no builder of its own — the graph builder and the profile builder each
synthesise it from what their own artifact knows about the subject, in a `context` phase at
the end of their plan. Both come through here.
"""

import json

from loguru import logger

from .. import config
from ..core import inference
from ..core.repair import parse_with_repair
from ..core.workspace import Workspace
from ..instance import locale
from ..instance.content_context import CANONICAL_KEYS, NARRATIVE_KEY, ContentContext, load_for
from .. import prompts as prompts_pkg

CONTENT_CONTEXT_SCHEMA = {
    "type": "object",
    "properties": {
        NARRATIVE_KEY: {"type": "string"},
        **{key: {"type": "string"} for key in CANONICAL_KEYS},
    },
    "required": [NARRATIVE_KEY, *CANONICAL_KEYS],
    "additionalProperties": False,
}


def synthesize(
    ws: Workspace,
    evidence_block: str,
    source_label: str,
    model: str,
    *,
    think: bool = False,
) -> ContentContext | None:
    """Write the subject context draft from one builder's evidence, or `None` on failure.

    Constrained and with reasoning off by default: a grammar and the reasoning channel do
    not coexist on this stack, and with the channel closed a reasoning model deliberates
    into the answer — which here would be interpolated into every prompt as if it were the
    subject. An unreadable answer keeps whatever context was already there.
    """
    current = load_for(ws)
    prompts = prompts_pkg.of(locale.prompt_language(ws))
    prompt = prompts.synthesize_content_context_prompt(
        current_block=current.prompt_block(),
        evidence_block=evidence_block.strip(),
        source_label=source_label,
        max_chars=config.CONTENT_CONTEXT_MAX_CHARS,
    )
    response = inference.generate(
        model=model,
        prompt=prompt,
        think=think,
        temperature=inference.judgement_temperature(think),
        format=None if think else CONTENT_CONTEXT_SCHEMA,
    ).response
    parsed, error = parse_with_repair(
        response,
        _parse,
        config.REPAIR_LLM,
        config.MAX_JSON_REPAIR_TRIES,
        shape='{"narrative": "…", "subject": "…", '
        '"educational_level": "…", "language_of_instruction": "…"}',
        format=CONTENT_CONTEXT_SCHEMA,
        prompts=prompts,
    )
    if parsed is None:
        logger.warning(
            f"Could not synthesise the subject context ({error}); "
            "keeping the one that was there"
        )
        return None

    synthesized = ContentContext(
        {
            NARRATIVE_KEY: str(parsed.get(NARRATIVE_KEY, "")),
            **{key: str(parsed.get(key, "") or "") for key in CANONICAL_KEYS},
        }
    )
    # The prompt states the cap, and a prompt is a request: it is enforced here too.
    synthesized.narrative = _clip(synthesized.narrative, config.CONTENT_CONTEXT_MAX_CHARS)

    # Always the draft: the curated file is what a person wrote and what wins on read.
    synthesized.save(ws.content_context_autogenerated_path)
    logger.success(
        f"Subject context synthesised from {source_label.lower()}: "
        f"«{synthesized.subject or 'subject not declared'}», "
        f"{len(synthesized.narrative)} characters"
    )
    if ws.content_context_path.is_file():
        logger.info(
            f"A curated context exists ({ws.content_context_path.name}); it still wins. "
            f"The synthesis stays in {ws.content_context_autogenerated_path.name}"
        )
    return synthesized


def _parse(response: str) -> tuple[dict | None, str | None]:
    """Read the answer as an object carrying a non-empty narrative."""
    try:
        data = json.loads(response)
    except json.JSONDecodeError as e:
        return None, str(e)
    if not isinstance(data, dict):
        return None, f"expected an object, got {type(data).__name__}"
    if not str(data.get(NARRATIVE_KEY, "")).strip():
        return None, f"'{NARRATIVE_KEY}' is missing or empty"
    return data, None


def _clip(text: str, limit: int) -> str:
    """Trim `text` to `limit`, cutting on a sentence and never on a character.

    This string is interpolated into every prompt of the system, and a clause cut in half
    reads as a corrupted file rather than as a long one.
    """
    text = text.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    stop = cut.rfind(".")
    if stop > 0:
        return cut[: stop + 1].strip()
    space = cut.rfind(" ")
    return (cut[:space] if space > 0 else cut).strip() + "…"
