"""The «Etiquetado y generación» settings: candidate bands, few-shot, guardrail and repair."""

from ..types import Impact, Setting

SETTINGS: list[Setting] = [
    Setting(key="generation.tagger_top_k", name="TAGGER_TOP_K_CANDIDATES", kind="int",
            default=10, group="Etiquetado y generación", impact=Impact.CONTEXTS, minimum=1,
            doc="""La banda fija de candidatos que el embedder entrega al verificador LLM; lo que el prefiltro descarta el LLM nunca puede recuperarlo, así que este valor es el techo de todo el etiquetado."""),
    Setting(key="generation.tagger_fallback_top_k", name="TAGGER_FALLBACK_TOP_K", kind="int",
            default=30, group="Etiquetado y generación", impact=Impact.CONTEXTS, minimum=1,
            doc="""La banda más amplia con la que se reintenta una sola vez cuando el verificador rechaza todos los candidatos de TAGGER_TOP_K_CANDIDATES."""),
    Setting(key="generation.max_few_shot_examples", name="MAX_FEW_SHOT_EXAMPLES", kind="int",
            default=4, group="Etiquetado y generación", impact=Impact.NONE, minimum=1,
            doc="""El número de ítems del banco de ejemplares que se muestran al generador como ejemplos few-shot en el prompt de generación."""),
    Setting(key="generation.max_json_repair_tries", name="MAX_JSON_REPAIR_TRIES", kind="int",
            default=3, group="Etiquetado y generación", impact=Impact.NONE, minimum=0,
            doc="""Acota el bucle de reintentos de parse_with_repair al reparar una respuesta JSON del modelo que llega mal formada."""),
    Setting(key="generation.check_similarity_threshold", name="CHECK_SIMILARITY_THRESHOLD",
            kind="float", default=0.85, group="Etiquetado y generación", impact=Impact.NONE,
            minimum=0.0, maximum=1.0,
            doc="""Por encima de este parecido, el aviso de similitud entre variantes se marca como alto. Lo lee checks.py al comparar una variante recién generada con las que ya existen. No está medido contra un corpus. Desde que las comprobaciones dictan veredicto, cruzarlo cuenta como señal dura y dispara un reintento guiado (CHECK_MAX_RETRIES); nada se descarta por cruzarlo, la última versión se acepta con sus señales."""),
    Setting(key="generation.check_max_retries", name="CHECK_MAX_RETRIES", kind="int",
            default=1, group="Etiquetado y generación", impact=Impact.NONE, minimum=0,
            doc="""Cuántas veces se vuelve a pedir una variante cuyas comprobaciones devuelven «retry»: solo las dos señales duras lo provocan (mención literal de un concepto no impartido, o un parecido alto con un ejemplar o con otra variante del lote); que el etiquetador no la reconozca queda como aviso y nunca reintenta. El reintento repite la misma llamada (mismo razonamiento, misma temperatura) con una sección de corrección que nombra los motivos. Uno por defecto: cada reintento cuesta una generación completa, y si el último intento sigue en «retry» se acepta con sus señales, como antes de existir el bucle. A 0 las comprobaciones vuelven a ser solo diagnóstico."""),
    Setting(key="generation.avoid_recent", name="GENERATION_AVOID_RECENT", kind="int",
            default=12, group="Etiquetado y generación", impact=Impact.NONE, minimum=0,
            doc="""Cuántas variantes guardadas recientes del mismo encargo (misma modalidad y, si los hay, conceptos objetivo compartidos) entran en el prompt como «escenarios ya usados», para que una tanda nueva no repita los envoltorios de las anteriores. Cada enunciado entra recortado a 240 caracteres, igual que los del propio lote. A 0 se desactiva y cada tanda solo evita repetirse a sí misma, como antes de existir el ajuste."""),
    Setting(key="generation.instructions_max_chars", name="GENERATION_INSTRUCTIONS_MAX_CHARS",
            kind="int", default=600, group="Etiquetado y generación", impact=Impact.NONE,
            minimum=1,
            doc="""Acota el texto libre de instrucciones que puede llevar una comisión, y es lo que lee el modelo guardarraíl — por lo que la ventana de contexto del guardarraíl puede quedarse pequeña."""),
    Setting(key="generation.content_context_max_chars", name="CONTENT_CONTEXT_MAX_CHARS",
            kind="int", default=900, group="Etiquetado y generación", impact=Impact.REINDEX,
            minimum=1,
            doc="""El contexto de la asignatura entra en TODOS los prompts del sistema, así que su coste se paga una vez por llamada y en cada una de ellas. 900 caracteres son ~250 tokens: espacio de sobra para decir qué materia es, a qué nivel, en qué idioma y con qué convenciones, y poco suficiente como para que no compita con el material que el prompt lleva de verdad. También es lo que acota la síntesis: sin techo, cada reconstrucción añadiría un matiz más."""),
    Setting(key="generation.guardrail_criteria", name="GUARDRAIL_CRITERIA", kind="list[str]",
            default=["harm", "jailbreak"], group="Etiquetado y generación", impact=Impact.NONE,
            doc="""Los criterios contra los que el modelo guardarraíl examina una comisión antes de que el generador escriba la variante."""),
]
