"""The system's settings, as attributes.

This module decides no value: `settings/registry/` declares them, with their measurement
beside each one, and `settings.apply` writes them here. What is read below is the index
of what the system exposes, not its definition.
"""

from .settings import apply

INFERENCE_ENGINE: str
OLLAMA_HOST: str
CEREBRAS_BASE_URL: str
CEREBRAS_API_KEY: str
CEREBRAS_MODELS: list[str]
CEREBRAS_MAX_REQUESTS_MINUTE: int
CEREBRAS_MAX_TOKENS_MINUTE: int
CEREBRAS_MAX_REQUESTS_DAY: int
CEREBRAS_MAX_TOKENS_DAY: int
CEREBRAS_MAX_WAIT_SECONDS: int
CEREBRAS_MAX_CONCURRENT_JOBS: int
IDLE_UNLOAD_SECONDS: int
IDLE_UNLOAD_POLL_SECONDS: int

OLLAMA_SSH_HOST: str
OLLAMA_SSH_REMOTE_PORT: int
OLLAMA_SSH_KEY_PATH: str
OLLAMA_SSH_AUTOSTART: bool

GUARDRAIL_LLM: str
EMBEDDING_LLM: str
EMBEDDING_MODELS: tuple[str, ...]
LLM_CONTEXT: dict[str, int]

THINK_TRANSCRIBE: bool | str
THINK_TRANSCRIBE_IMAGE: bool | str
THINK_TRANSCRIBE_SEAM: bool | str
THINK_EP_SCAN: bool | str
THINK_EP_CONSOLIDATE: bool | str
THINK_EP_CONTEXT: bool | str
THINK_EB_EXTRACT: bool | str
THINK_KG_EXTRACT: bool | str
THINK_KG_CLEAN_MERGE: bool | str
THINK_KG_CLEAN_DROP: bool | str
THINK_KG_UNITS: bool | str
THINK_KG_DOMAINS: bool | str
THINK_KG_DOMAINS_LEFTOVERS: bool | str
THINK_KG_LINK_DOMAIN: bool | str
THINK_KG_LINK_CROSS_DOMAIN: bool | str
THINK_KG_TAGGABLE: bool | str
THINK_KG_CONTEXT: bool | str
THINK_DESCRIPTION_GENERATION: bool | str
THINK_CONCEPT_TAGGER: bool | str
THINK_ADMISSIBILITY: bool | str
TEMPERATURE_DETERMINISTIC: float
TEMPERATURE_REASONING: float
TEMPERATURE_GENERATION: float
TEMPERATURE_REPAIR: float
TEMPERATURE_DEFAULT: float

TRANSCRIBE_MODEL: str
TRANSCRIBE_SEAM_MODEL: str
EP_SCAN_MODEL: str
EP_CONSOLIDATE_MODEL: str
EP_CONTEXT_MODEL: str
EB_EXTRACT_MODEL: str
KG_EXTRACT_MODEL: str
KG_CLEAN_MERGE_MODEL: str
KG_CLEAN_DROP_MODEL: str
KG_UNITS_MODEL: str
KG_DOMAINS_MODEL: str
KG_DOMAINS_LEFTOVERS_MODEL: str
KG_LINK_DOMAIN_MODEL: str
KG_LINK_CROSS_DOMAIN_MODEL: str
KG_TAGGABLE_MODEL: str
KG_CONTEXT_MODEL: str
DESCRIPTION_GENERATION_LLM: str
CONCEPT_TAGGER_LLM: str
GENERATION_MODELS: list[str]
FIXED_EFFORT_MODELS: list[str]
FIXED_EFFORT_LEVELS: dict[str, str]
VARIANT_GENERATION_LLM: str
ADMISSIBILITY_LLM: str
REPAIR_LLM: str

TRANSCRIBE_DPI: int
TRANSCRIBE_TEMPERATURE: float
TRANSCRIBE_MAX_RETRIES: int
TRANSCRIBE_MAX_OUTPUT_TOKENS: int
TRANSCRIBE_PROMPT_VERSION: int
TRANSCRIBE_SEAM_CHARS: int
EXEMPLARS_OCR: bool

EP_CHUNK_SIZE: int
EP_SCAN_EXCERPT_CHARS: int
EP_MAX_ITEM_TYPES: int
EB_CHUNK_SIZE: int
EB_BATCH_OVERLAP_BLOCKS: int

KG_BUILDER_CHUNK_SIZE: int
KG_MAX_EVIDENCE_RELATIONS: int
KG_EXTRACT_GLEANING_PASSES: int
KG_DEFINITION_MAX_CHARS: int
KG_MAX_SOURCE_PASSAGES: int
KG_SOURCE_PASSAGE_CHARS: int
KG_BUILDER_PLURAL_SUFFIXES: list[str]
KG_BUILDER_MERGE_QUALIFIER_PATTERN: str
KG_BUILDER_UNCLASSIFIED_DOMAIN: str
KG_BUILDER_MAX_TITLES_PER_DOC: int
KG_BUILDER_TITLE_UBIQUITY: float
KG_BUILDER_MERGE_SIMILARITY: float
KG_BUILDER_MAX_MERGE_GROUP: int
KG_BUILDER_MERGE_GROUPS_PER_CALL: int
KG_BUILDER_CLEAN_BATCH_SIZE: int
KG_BUILDER_DOMAIN_BATCH_SIZE: int
KG_BUILDER_DOMAIN_ROUNDS: int

EMBEDDING_QUERY_PREFIX: str
EMBEDDING_DOCUMENT_PREFIX: str
EMBEDDING_BATCH_SIZE: int
EMBEDDING_FIELD_MAX_CHARS: int
EMBEDDING_MAX_CHARS: int
EMBEDDER_SIMILARITY_THRESHOLD: float
EMBEDDER_DESCRIPTION_WEIGHT: float
DESCRIPTION_SIBLINGS_TOP_K: int
DESCRIPTION_COLLISION_SIMILARITY: float
DESCRIPTION_PROMPT_VERSION: int

TAGGER_TOP_K_CANDIDATES: int
TAGGER_FALLBACK_TOP_K: int
MAX_FEW_SHOT_EXAMPLES: int
MAX_JSON_REPAIR_TRIES: int
CHECK_SIMILARITY_THRESHOLD: float
CHECK_MAX_RETRIES: int
GENERATION_AVOID_RECENT: int
GENERATION_MAX_ITEMS: int
GENERATION_INSTRUCTIONS_MAX_CHARS: int
CONTENT_CONTEXT_MAX_CHARS: int
GUARDRAIL_CRITERIA: list[str]


LOG_LEVEL: str
NOISY_LOGGERS: list[str]
NOISY_WARNING_MODULES: list[str]

apply(globals())
