"""The exemplars profile: the stage that declares what shape an item of this instance has.

Declares `auth.VIEW` for the whole router; validating and saving add `auth.EDIT`.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from variatio.core.workspace import Workspace
from variatio.instance import locale
from variatio.instance.exemplars_profile import profile_drift

from .. import auth, review, storage
from ..editors import profile_edit
from .pipeline import pipeline_payload

router = APIRouter(prefix="/api/profile", tags=["profile"], dependencies=[auth.VIEW])


class ProfileBody(BaseModel):
    """A whole profile document, as the editor sends it."""

    profile: dict


def pending_draft(ws: Workspace, payload: dict) -> dict | None:
    """Report the unread `_autogenerated` draft beside a curated profile, or nothing.

    Every build writes the draft and never the curated file, so once a profile has been
    curated the newest synthesis sits there unread. Only a draft that actually differs is
    worth surfacing.
    """
    if not payload.get("exists") or payload.get("is_autogenerated"):
        return None
    draft_path = review.autogenerated_path(ws, review.EXEMPLARS_PROFILE)
    curated_path = review.canonical_path(ws, review.EXEMPLARS_PROFILE)
    if draft_path is None or not draft_path.is_file():
        return None
    draft = storage.read_json(draft_path)
    if not isinstance(draft, dict):
        return None
    drift = profile_drift(payload["profile"], draft)
    if not any(drift.values()):
        return None
    return {
        "drift": drift,
        "path": str(draft_path),
        "newer": draft_path.stat().st_mtime > curated_path.stat().st_mtime,
    }


@router.get("")
def read(access: auth.Access = auth.VIEW) -> dict:
    """Answer the profile in force, with whatever draft is waiting beside it.

    It carries the difficulty field's canonical name and rungs because the editor may have
    to CREATE one — a profile written before difficulty was guaranteed has none — and the
    name is the workspace's prompt language's. Resolving it in the browser would mean the
    client guessing which language a workspace was built in.
    """
    payload = profile_edit.load(access.ws)
    field, levels = locale.difficulty(access.ws)
    return {
        **payload,
        "pending_draft": pending_draft(access.ws, payload),
        "difficulty": {"field": field, "levels": levels},
    }


@router.post("/validate", dependencies=[auth.EDIT])
def validate(body: ProfileBody) -> dict:
    """Answer whether a profile would be accepted, without writing anything."""
    error = profile_edit.validate(body.profile)
    return {"valid": error is None, "error": error}


@router.put("", dependencies=[auth.EDIT])
def save(body: ProfileBody, access: auth.Access = auth.VIEW) -> dict:
    """Write the profile and answer the chain's new state with it."""
    try:
        result = profile_edit.save(access.ws, body.profile)
    except ValueError as exc:
        raise HTTPException(422, str(exc)) from exc
    return {**result, "pipeline": pipeline_payload(access)}
