from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from variant_generator.core.workspace import Workspace
from variant_generator.instance.exemplars_profile import profile_drift

from .. import auth, review, storage
from ..editors import profile_edit
from .pipeline import pipeline_payload

router = APIRouter(prefix="/api/profile", tags=["profile"], dependencies=[auth.VIEW])


class ProfileBody(BaseModel):
    profile: dict


def pending_draft(ws: Workspace, payload: dict) -> dict | None:
    if not payload.get("exists") or payload.get("is_autogenerated"):
        return None
    draft_path = review.autogenerated_path(ws, review.EXEMPLARS_PROFILE)
    curated_path = review.canonical_path(ws, review.EXEMPLARS_PROFILE)
    if draft_path is None or not draft_path.is_file():
        return None
    draft = storage.read_json(draft_path)
    if not isinstance(draft, dict):
        return None
    drift = profile_drift(payload["profile"], draft)
    if not any(drift.values()):
        return None
    return {
        "drift": drift,
        "path": str(draft_path),
        "newer": draft_path.stat().st_mtime > curated_path.stat().st_mtime,
    }


@router.get("")
def read(access: auth.Access = auth.VIEW) -> dict:
    payload = profile_edit.load(access.ws)
    return {**payload, "pending_draft": pending_draft(access.ws, payload)}


@router.post("/validate", dependencies=[auth.EDIT])
def validate(body: ProfileBody) -> dict:
    error = profile_edit.validate(body.profile)
    return {"valid": error is None, "error": error}


@router.put("", dependencies=[auth.EDIT])
def save(body: ProfileBody, access: auth.Access = auth.VIEW) -> dict:
    try:
        result = profile_edit.save(access.ws, body.profile)
    except ValueError as exc:
        raise HTTPException(422, str(exc)) from exc
    return {**result, "pipeline": pipeline_payload(access)}
