from dataclasses import dataclass
from pathlib import Path

INSTANCE_DIRNAME = "instance"
CACHE_DIRNAME = "cache"
RAW_DIRNAME = "raw"

DEFAULT_SLUG = "default"


# `raw_dirname` was a constructor field until 2026-08-17, and it existed for exactly one
# value: the raw directory of the repo's old single-user layout. With `default` moved into
# `workspaces/`, every instance names that directory `raw`, so what looked like
# configurability is one more way for two workspaces to disagree about where a corpus lives.
@dataclass(frozen=True)
class Workspace:
    root: Path
    slug: str = DEFAULT_SLUG

    def __post_init__(self) -> None:
        object.__setattr__(self, "root", Path(self.root).resolve())

    # DIRECTORIES -------------------------------------------------------------------------

    @property
    def instance_dir(self) -> Path:
        return self.root / INSTANCE_DIRNAME

    @property
    def cache_dir(self) -> Path:
        return self.root / CACHE_DIRNAME

    @property
    def raw_dir(self) -> Path:
        return self.root / RAW_DIRNAME

    @property
    def raw_corpus_dir(self) -> Path:
        return self.raw_dir / "raw_corpus"

    @property
    def raw_exemplars_dir(self) -> Path:
        return self.raw_dir / "raw_exemplars_bank"

    # INSTANCE ARTIFACTS ------------------------------------------------------------------

    @property
    def kg_path(self) -> Path:
        return self.instance_dir / "knowledge_graph.json"

    @property
    def kg_autogenerated_path(self) -> Path:
        return self.instance_dir / "knowledge_graph_autogenerated.json"

    @property
    def exemplars_bank_path(self) -> Path:
        return self.instance_dir / "exemplars_bank.json"

    @property
    def exemplars_profile_path(self) -> Path:
        return self.instance_dir / "exemplars_profile.json"

    @property
    def exemplars_profile_autogenerated_path(self) -> Path:
        return self.instance_dir / "exemplars_profile_autogenerated.json"

    # What subject this is, in prose. It is an instance artifact and not host state, even
    # though it has no `raw/` of its own and no builder of its own: the OTHER two builders
    # synthesise it at the end of their work, each with what its artifact knows about the
    # subject. That is why it lives in `instance/` and why it has the draft/curated pair the
    # graph and the profile have — the curated one wins, and that is what stops the drift of
    # every rebuild rewriting the text once more.
    @property
    def content_context_path(self) -> Path:
        return self.instance_dir / "content_context.json"

    @property
    def content_context_autogenerated_path(self) -> Path:
        return self.instance_dir / "content_context_autogenerated.json"

    # REGENERABLE DERIVATIONS -------------------------------------------------------------

    @property
    def markdown_cache_dir(self) -> Path:
        return self.cache_dir / "markdown"

    @property
    def concept_descriptions_path(self) -> Path:
        return self.cache_dir / "concept_descriptions.json"

    # Which piece of the theory corpus each concept came from. It is a derivation of the
    # corpus, like the markdown beside it, and not part of the artifact: the curated graph is
    # edited by hand and must not swell with hundreds of KB of quotations. It is rewritten
    # whole on every graph build; without it the descriptions are composed from the relations
    # alone, which is how they used to be composed.
    @property
    def concept_sources_path(self) -> Path:
        return self.cache_dir / "concept_sources.json"

    @property
    def concepts_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "concepts_embeddings.npz"

    @property
    def exemplars_bank_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "exemplars_bank_embeddings.npz"

    @property
    def eval_rag_bank_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "eval_rag_bank.npz"

    # HOST STATE --------------------------------------------------------------------------

    @property
    def history_dir(self) -> Path:
        return self.instance_dir / ".history"

    @property
    def runs_dir(self) -> Path:
        return self.instance_dir / ".runs"

    @property
    def review_state_path(self) -> Path:
        return self.instance_dir / ".review_state.json"

    @property
    def eval_sessions_dir(self) -> Path:
        return self.instance_dir / ".evaluations"

    # The curriculum considered covered in this instance. It is host state, not an
    # artifact: no builder produces it, it does not come from `raw/`, and it is not part
    # of the instance definition. It is a teaching decision about the workspace, like
    # `.review_state.json`.
    @property
    def curriculum_path(self) -> Path:
        return self.instance_dir / ".curriculum.json"
