import json
from pathlib import Path

from loguru import logger

from system import config
from system.content_profile import ContentProfile
from system.knowledge_graph import KnowledgeGraph
from system.exemplars_bank import ExemplarsBank
from system.embedder import Embedder
from system.concept_tagger import ConceptTagger
from system.content_generator import ContentGenerator
from builders.knowledge_graph_builder import KnowledgeGraphBuilder
from builders.exemplars_bank_builder import ExemplarsBankBuilder
from builders.content_profile_builder import ContentProfileBuilder


def _json_has_key(path: str | Path, key: str) -> bool:
    path = Path(path)
    if not path.is_file():
        return False
    try:
        with path.open(encoding="utf-8") as f:
            return key in json.load(f)
    except (json.JSONDecodeError, OSError):
        return False


def _resolve_content_profile() -> ContentProfile:
    if config.CONTENT_PROFILE_PATH.is_file():
        return ContentProfile(config.CONTENT_PROFILE_PATH)
    if not config.CONTENT_PROFILE_AUTOGENERATED_PATH.is_file():
        logger.warning("No content profile found — drafting one from the raw exemplars")
        ContentProfileBuilder().build(
            config.RAW_EXEMPLARS_BANK_DIR, config.CONTENT_PROFILE_AUTOGENERATED_PATH
        )
    logger.warning(
        f"Using auto-drafted content profile: {config.CONTENT_PROFILE_AUTOGENERATED_PATH}"
    )
    return ContentProfile(config.CONTENT_PROFILE_AUTOGENERATED_PATH)


def _resolve_flat_kg(builder: KnowledgeGraphBuilder) -> Path:
    if _json_has_key(config.KG_CLEANED_PATH, "entities"):
        return config.KG_CLEANED_PATH
    if _json_has_key(config.KG_PATH, "entities"):
        return config.KG_PATH
    if not config.KG_STAGING_PATH.is_file():
        logger.warning("No staging KG found — extracting one from the raw corpus")
        builder.build(config.RAW_CORPUS_DIR, config.KG_STAGING_PATH)
    logger.warning("Deduplicating the staging KG")
    builder.clean(config.KG_STAGING_PATH, config.KG_CLEANED_PATH)
    return config.KG_CLEANED_PATH


def _resolve_kg_path() -> Path:
    if _json_has_key(config.KG_PATH, "concepts_by_domains"):
        return config.KG_PATH
    if not _json_has_key(config.KG_AUTOGENERATED_PATH, "concepts_by_domains"):
        logger.warning("No curated KG found — drafting one via curate()")
        builder = KnowledgeGraphBuilder()
        builder.curate(
            cleaned_path=_resolve_flat_kg(builder),
            output_path=config.KG_AUTOGENERATED_PATH,
        )
    logger.warning(f"Using auto-drafted KG for this run: {config.KG_AUTOGENERATED_PATH}")
    return config.KG_AUTOGENERATED_PATH


def _resolve_bank(content_profile: ContentProfile) -> dict:
    exemplars_bank = ExemplarsBank(config.EXEMPLARS_BANK_PATH)
    if exemplars_bank.bank is not None:
        return exemplars_bank.bank
    logger.warning("No exemplars bank found — building it from the raw exemplars")
    return ExemplarsBankBuilder(content_profile).build(
        config.RAW_EXEMPLARS_BANK_DIR, config.EXEMPLARS_BANK_PATH
    )


def _annotate_bank(bank: dict, tagger: ConceptTagger) -> dict:
    if bank and all("concepts" in item for item in bank.values()):
        logger.info("Exemplars bank already annotated — skipping tagging")
        return bank
    return tagger.tag_all(bank, config.EXEMPLARS_BANK_PATH)


def _pick_target_concepts(annotated_bank: dict, k: int) -> list[str]:
    counts: dict[str, int] = {}
    for item in annotated_bank.values():
        for concept in item.get("concepts") or []:
            counts[concept] = counts.get(concept, 0) + 1
    return sorted(counts, key=lambda c: counts[c], reverse=True)[:k]


if __name__ == "__main__":
    content_profile = _resolve_content_profile()
    graph = KnowledgeGraph(_resolve_kg_path())
    bank = _resolve_bank(content_profile)

    embedder = Embedder(
        graph,
        config.EMBEDDING_LLM,
        primary_field=content_profile.primary_field,
        context=content_profile.content_context,
    )

    tagger = ConceptTagger(
        embedder, config.CONCEPT_TAGGER_LLM, primary_field=content_profile.primary_field
    )
    annotated_bank = _annotate_bank(bank, tagger)
    embedder.enrich_index_with_content(annotated_bank)

    generator = ContentGenerator(
        knowledge_graph=graph,
        exemplars_bank=annotated_bank,
        embedder=embedder,
        content_profile=content_profile,
        generator_model=config.CONTENT_GENERATION_LLM,
    )

    targets = _pick_target_concepts(annotated_bank, k=2)
    if not targets:
        logger.error("No tagged concepts available to drive generation — aborting demo")
        raise SystemExit(1)

    logger.info(f"Generating 2 item(s) for target concepts: {targets}")
    results = generator.generate(
        concepts=targets,
        n=2,
        fixed={"difficulty_level": "intermedio", "is_solved": True},
    )

    logger.success(f"Generated {len(results)} item(s)")
    for i, result in enumerate(results, 1):
        print(f"\n===================== ITEM {i} =====================")
        print(result.item.model_dump_json(indent=2))
        if result.thinking:
            print(f"\n--- thinking ---\n{result.thinking}")
