# from loguru import logger

from system import config
from builders.content_profile_builder import ContentProfileBuilder
from system.concept_tagger import ConceptTagger
from system.exemplars_bank import ExemplarsBank
from system.content_generator import ContentGenerator
from system.content_profile import ContentProfile
from system.embedder import Embedder
from system.knowledge_graph import KnowledgeGraph
from builders.knowledge_graph_builder import KnowledgeGraphBuilder
from builders.exemplars_bank_builder import ExemplarsBankBuilder

if __name__ == "__main__":
    
    ContentProfileBuilder().build(config.RAW_EXEMPLARS_BANK_DIR, config.CONTENT_PROFILE_AUTOGENERATED_PATH)
    
    # graph = KnowledgeGraphBuilder()
    # graph.build(config.RAW_CORPUS_DIR, config.KG_STAGING_PATH)
    # graph.clean()
    
    # content_profile = ContentProfile(config.CONTENT_PROFILE_PATH)
    
    
    # graph = KnowledgeGraph(config.KG_PATH)

    # exemplars_bank = ExemplarsBank(config.EXEMPLARS_BANK_PATH)
    # bank = exemplars_bank.bank
    # if bank is None:
    #     bank = ExemplarsBankBuilder(content_profile).build(
    #         config.RAW_EXEMPLARS_BANK_DIR, config.EXEMPLARS_BANK_PATH
    #     )

    # embedder = Embedder(
    #     graph,
    #     config.EMBEDDING_LLM,
    #     primary_field=content_profile.primary_field,
    #     context=content_profile.content_context,
    # )

    # tagger = ConceptTagger(
    #     embedder, config.CONCEPT_TAGGER_LLM, primary_field=content_profile.primary_field
    # )

    # # annotated_bank = tagger.tag_all(bank, config.EXEMPLARS_BANK_PATH)
    # # embedder.enrich_index_with_content(annotated_bank)

    # generator = ContentGenerator(
    #     knowledge_graph=graph,
    #     exemplars_bank=bank,
    #     embedder=embedder,
    #     content_profile=content_profile,
    #     generator_model=config.CONTENT_GENERATION_LLM,
    # )