[project]
name = "graph-guided-llm-content-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "docling>=2.0.0",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "ollama>=0.4.7",
    "scipy>=1.15.3",
    "tqdm>=4.67.3",
    "streamlit>=1.57.0",
]

[dependency-groups]
dev = []
