import json
from pathlib import Path

from .. import config

EXEMPLARS_PROFILE = "exemplars_profile"
KNOWLEDGE_GRAPH = "knowledge_graph"
EXEMPLARS_BANK = "exemplars_bank"


class MissingArtifactError(Exception):
    def __init__(self, artifact: str):
        self.artifact = artifact
        super().__init__(f"Missing instance artifact '{artifact}'")


def _json_has_key(path: str | Path, key: str) -> bool:
    path = Path(path)
    if not path.is_file():
        return False
    try:
        with path.open(encoding="utf-8") as f:
            return key in json.load(f)
    except (json.JSONDecodeError, OSError):
        return False


def exemplars_profile_path() -> Path | None:
    if config.EXEMPLARS_PROFILE_PATH.is_file():
        return config.EXEMPLARS_PROFILE_PATH
    if config.EXEMPLARS_PROFILE_AUTOGENERATED_PATH.is_file():
        return config.EXEMPLARS_PROFILE_AUTOGENERATED_PATH
    return None


def knowledge_graph_path() -> Path | None:
    if _json_has_key(config.KG_PATH, "concepts_by_domains"):
        return config.KG_PATH
    if _json_has_key(config.KG_AUTOGENERATED_PATH, "concepts_by_domains"):
        return config.KG_AUTOGENERATED_PATH
    return None


def missing_artifacts() -> list[str]:
    missing = []
    if exemplars_profile_path() is None:
        missing.append(EXEMPLARS_PROFILE)
    if knowledge_graph_path() is None:
        missing.append(KNOWLEDGE_GRAPH)
    if not config.EXEMPLARS_BANK_PATH.is_file():
        missing.append(EXEMPLARS_BANK)
    return missing
