import json
from pathlib import Path

from .. import config
from ..content_context import ContentContext, load_for, resolve_path
from ..workspace import Workspace

EXEMPLARS_PROFILE = "exemplars_profile"
KNOWLEDGE_GRAPH = "knowledge_graph"
EXEMPLARS_BANK = "exemplars_bank"


class MissingArtifactError(Exception):
    def __init__(self, artifact: str):
        self.artifact = artifact
        super().__init__(f"Missing instance artifact '{artifact}'")


def resolve(ws: Workspace | None = None) -> Workspace:
    return ws or config.default_workspace()


def _json_has_key(path: str | Path, key: str) -> bool:
    path = Path(path)
    if not path.is_file():
        return False
    try:
        with path.open(encoding="utf-8") as f:
            return key in json.load(f)
    except (json.JSONDecodeError, OSError):
        return False


def exemplars_profile_path(ws: Workspace | None = None) -> Path | None:
    ws = resolve(ws)
    if ws.exemplars_profile_path.is_file():
        return ws.exemplars_profile_path
    if ws.exemplars_profile_autogenerated_path.is_file():
        return ws.exemplars_profile_autogenerated_path
    return None


def knowledge_graph_path(ws: Workspace | None = None) -> Path | None:
    ws = resolve(ws)
    if _json_has_key(ws.kg_path, "concepts_by_domains"):
        return ws.kg_path
    if _json_has_key(ws.kg_autogenerated_path, "concepts_by_domains"):
        return ws.kg_autogenerated_path
    return None


# Not in `missing_artifacts`, and that is the point: the context has no builder of its own
# and no `raw/` slot, so "absent" is never a step somebody skipped. It is what a workspace
# looks like before either of the other two builds has run.
def content_context_path(ws: Workspace | None = None) -> Path | None:
    return resolve_path(resolve(ws))


def load_content_context(ws: Workspace | None = None) -> ContentContext:
    return load_for(resolve(ws))


def missing_artifacts(ws: Workspace | None = None) -> list[str]:
    ws = resolve(ws)
    missing = []
    if exemplars_profile_path(ws) is None:
        missing.append(EXEMPLARS_PROFILE)
    if knowledge_graph_path(ws) is None:
        missing.append(KNOWLEDGE_GRAPH)
    if not ws.exemplars_bank_path.is_file():
        missing.append(EXEMPLARS_BANK)
    return missing
