from loguru import logger

from .. import config
from ..builders.content_profile_builder import ContentProfileBuilder
from ..builders.exemplars_bank_builder import ExemplarsBankBuilder
from ..builders.knowledge_graph_builder import KnowledgeGraphBuilder
from ..content_profile import ContentProfile
from . import _artifacts


def build_content_profile() -> dict:
    logger.info("Building content profile draft from raw exemplars")
    profile = ContentProfileBuilder().build(
        config.RAW_EXEMPLARS_BANK_DIR, config.CONTENT_PROFILE_AUTOGENERATED_PATH
    )
    if not profile:
        raise RuntimeError(
            f"Could not draft a content profile from {config.RAW_EXEMPLARS_BANK_DIR}"
        )
    return profile


def build_knowledge_graph() -> dict:
    logger.info("Building knowledge graph draft from raw corpus")
    return KnowledgeGraphBuilder().build(config.RAW_CORPUS_DIR)


def build_exemplars_bank(content_profile: ContentProfile | None = None) -> dict:
    if content_profile is None:
        path = _artifacts.content_profile_path()
        if path is None:
            raise _artifacts.MissingArtifactError(_artifacts.CONTENT_PROFILE)
        content_profile = ContentProfile(path)

    logger.info("Building exemplars bank from raw exemplars")
    bank = ExemplarsBankBuilder(content_profile).build(
        config.RAW_EXEMPLARS_BANK_DIR, config.EXEMPLARS_BANK_PATH
    )
    if not bank:
        raise RuntimeError(
            f"Could not build an exemplars bank from {config.RAW_EXEMPLARS_BANK_DIR}"
        )
    return bank


_BUILDERS = {
    _artifacts.CONTENT_PROFILE: build_content_profile,
    _artifacts.KNOWLEDGE_GRAPH: build_knowledge_graph,
    _artifacts.EXEMPLARS_BANK: build_exemplars_bank,
}


def build_missing() -> list[str]:
    missing = _artifacts.missing_artifacts()
    for artifact in missing:
        _BUILDERS[artifact]()
    return missing
