from loguru import logger

from .. import config, progress
from ..builders import exemplars_profile_builder, exemplars_bank_builder, knowledge_graph_builder
from ..builders.exemplars_profile_builder import ExemplarsProfileBuilder
from ..builders.exemplars_bank_builder import ExemplarsBankBuilder
from ..builders.knowledge_graph_builder import KnowledgeGraphBuilder
from ..exemplars_profile import ExemplarsProfile
from . import _artifacts


def build_exemplars_profile() -> dict:
    logger.info("Building exemplars profile draft from raw exemplars")
    profile = ExemplarsProfileBuilder().build(
        config.RAW_EXEMPLARS_BANK_DIR, config.EXEMPLARS_PROFILE_AUTOGENERATED_PATH
    )
    if not profile:
        raise RuntimeError(
            f"Could not draft a exemplars profile from {config.RAW_EXEMPLARS_BANK_DIR}"
        )
    return profile


def build_knowledge_graph() -> dict:
    logger.info("Building knowledge graph draft from raw corpus")
    return KnowledgeGraphBuilder().build(config.RAW_CORPUS_DIR)


def build_exemplars_bank(exemplars_profile: ExemplarsProfile | None = None) -> dict:
    if exemplars_profile is None:
        path = _artifacts.exemplars_profile_path()
        if path is None:
            raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_PROFILE)
        exemplars_profile = ExemplarsProfile(path)

    logger.info("Building exemplars bank from raw exemplars")
    bank = ExemplarsBankBuilder(exemplars_profile).build(
        config.RAW_EXEMPLARS_BANK_DIR, config.EXEMPLARS_BANK_PATH
    )
    if not bank:
        raise RuntimeError(
            f"Could not build an exemplars bank from {config.RAW_EXEMPLARS_BANK_DIR}"
        )
    return bank


_BUILDERS = {
    _artifacts.EXEMPLARS_PROFILE: build_exemplars_profile,
    _artifacts.KNOWLEDGE_GRAPH: build_knowledge_graph,
    _artifacts.EXEMPLARS_BANK: build_exemplars_bank,
}


_LABELS = {
    _artifacts.EXEMPLARS_PROFILE: "Perfil de ejemplares",
    _artifacts.KNOWLEDGE_GRAPH: "Grafo de conocimiento",
    _artifacts.EXEMPLARS_BANK: "Banco de ejemplares",
}

# Each builder declares what its phases cost; installing the plan here is what turns
# "some step is running" into a percentage of the whole build, for all three alike.
_PHASES = {
    _artifacts.EXEMPLARS_PROFILE: exemplars_profile_builder.BUILD_PHASES,
    _artifacts.KNOWLEDGE_GRAPH: knowledge_graph_builder.BUILD_PHASES,
    _artifacts.EXEMPLARS_BANK: exemplars_bank_builder.BUILD_PHASES,
}


def build_artifact(artifact: str) -> dict:
    if artifact not in _BUILDERS:
        raise ValueError(f"Unknown artifact '{artifact}'; expected one of {list(_BUILDERS)}")
    
    with progress.step(f"build_{artifact}", f"Construyendo: {_LABELS[artifact]}"), progress.overall(_PHASES[artifact]):
        return _BUILDERS[artifact]()


def build_missing() -> list[str]:
    missing = _artifacts.missing_artifacts()
    for artifact in missing:
        progress.checkpoint()
        build_artifact(artifact)
    return missing
