from dataclasses import dataclass
from pathlib import Path

from loguru import logger

from .. import config
from ..concept_tagger import ConceptTagger
from ..content_generator import ContentGenerator
from ..content_profile import ContentProfile
from ..embedder import Embedder
from ..exemplars_bank import ExemplarsBank
from ..knowledge_graph import KnowledgeGraph
from . import _artifacts


@dataclass
class PipelineContext:
    content_profile: ContentProfile
    knowledge_graph: KnowledgeGraph
    embedder: Embedder
    exemplars_bank: dict
    tagger: ConceptTagger
    generator: ContentGenerator
    content_profile_path: Path
    knowledge_graph_path: Path

    # The bank is the one artifact that changes while the context is alive (tagging,
    # manual edits). Swapping it means re-embedding and re-merging the index; doing it
    # here keeps embedder and generator from drifting apart.
    def apply_bank(self, bank: dict) -> None:
        self.exemplars_bank = bank
        self.embedder.enrich_index_with_content(bank)
        self.generator.exemplars_bank = bank


def initialize(tag: bool = False) -> PipelineContext:
    """Load the instance and warm the indices.

    Read-only by default: tagging is a separate, explicit act (`stages.tag_bank`)
    because it rewrites the exemplars bank. `tag=True` restores the old all-in-one
    behaviour the CLI relies on.
    """
    profile_path = _artifacts.content_profile_path()
    if profile_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.CONTENT_PROFILE)
    if profile_path == config.CONTENT_PROFILE_AUTOGENERATED_PATH:
        logger.warning(f"Using auto-drafted content profile: {profile_path}")

    kg_path = _artifacts.knowledge_graph_path()
    if kg_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.KNOWLEDGE_GRAPH)
    if kg_path == config.KG_AUTOGENERATED_PATH:
        logger.warning(
            f"Using auto-drafted KG for this run: {kg_path} — "
            f"curate it manually into {config.KG_PATH.name}"
        )

    bank = ExemplarsBank(config.EXEMPLARS_BANK_PATH).bank
    if bank is None:
        raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_BANK)

    content_profile = ContentProfile(profile_path)
    knowledge_graph = KnowledgeGraph(kg_path)

    embedder = Embedder(
        knowledge_graph,
        config.EMBEDDING_LLM,
        primary_field=content_profile.primary_field,
        context=content_profile.content_context,
    )
    tagger = ConceptTagger(
        embedder,
        config.CONCEPT_TAGGER_LLM,
        primary_field=content_profile.primary_field,
        context=content_profile.content_context,
    )
    generator = ContentGenerator(
        knowledge_graph=knowledge_graph,
        exemplars_bank=bank,
        embedder=embedder,
        content_profile=content_profile,
        generator_model=config.CONTENT_GENERATION_LLM,
    )

    context = PipelineContext(
        content_profile=content_profile,
        knowledge_graph=knowledge_graph,
        embedder=embedder,
        exemplars_bank=bank,
        tagger=tagger,
        generator=generator,
        content_profile_path=profile_path,
        knowledge_graph_path=kg_path,
    )

    if tag:
        from .tag import tag_bank

        tag_bank(context)
    else:
        embedder.enrich_index_with_content(bank)

    return context
