import json
from dataclasses import dataclass
from functools import partial
from pathlib import Path

from loguru import logger

from .. import config, progress
from ..concept_tagger import ConceptTagger
from ..content_generator import ContentGenerator
from ..embedder import Embedder
from ..exemplars_profile import ExemplarsProfile
from ..knowledge_graph import KnowledgeGraph
from ..workspace import Workspace
from . import _artifacts


# El cableado del índice y del etiquetador, aparte de `initialize` porque hay un segundo
# sitio que los necesita: la construcción del banco, que etiqueta cada documento nada más
# extraerlo y no puede llamar a `initialize` — el banco que esa función exige es
# justamente el que se está escribiendo.
def _embed_text(exemplars_profile: ExemplarsProfile):
    return partial(
        exemplars_profile.embed_text, field_max_chars=config.EMBEDDING_FIELD_MAX_CHARS
    )


def make_embedder(
    ws: Workspace,
    exemplars_profile: ExemplarsProfile,
    knowledge_graph: KnowledgeGraph,
) -> Embedder:
    return Embedder(
        knowledge_graph,
        config.EMBEDDING_LLM,
        embed_text=_embed_text(exemplars_profile),
        embed_signature=exemplars_profile.embed_signature,
        context=exemplars_profile.content_context,
        descriptions_path=ws.concept_descriptions_path,
        concept_sources_path=ws.concept_sources_path,
        concepts_cache_path=ws.concepts_embeddings_path,
        exemplars_bank_cache_path=ws.exemplars_bank_embeddings_path,
    )


def make_tagger(embedder: Embedder, exemplars_profile: ExemplarsProfile) -> ConceptTagger:
    return ConceptTagger(
        embedder,
        config.CONCEPT_TAGGER_LLM,
        embed_text=_embed_text(exemplars_profile),
        context=exemplars_profile.content_context,
    )


@dataclass
class PipelineContext:
    exemplars_profile: ExemplarsProfile
    knowledge_graph: KnowledgeGraph
    embedder: Embedder
    exemplars_bank: dict
    tagger: ConceptTagger
    generator: ContentGenerator
    exemplars_profile_path: Path
    knowledge_graph_path: Path
    workspace: Workspace

    # The bank is the one artifact that changes while the context is alive (tagging,
    # manual edits). Swapping it means re-embedding and re-merging the index; doing it
    # here keeps embedder and generator from drifting apart.
    def apply_bank(self, bank: dict) -> None:
        self.exemplars_bank = bank
        self.embedder.enrich_index_with_content(bank)
        self.generator.exemplars_bank = bank


def initialize(tag: bool = False, ws: Workspace | None = None) -> PipelineContext:
    """Load the instance and warm the indices.

    Read-only by default: tagging is a separate, explicit act (`stages.tag_bank`)
    because it rewrites the exemplars bank. `tag=True` restores the old all-in-one
    behaviour the CLI relies on.
    """
    ws = _artifacts.resolve(ws)

    profile_path = _artifacts.exemplars_profile_path(ws)
    if profile_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_PROFILE)
    if profile_path == ws.exemplars_profile_autogenerated_path:
        logger.warning(f"Perfil de ejemplares sin curar: {profile_path.name}")

    kg_path = _artifacts.knowledge_graph_path(ws)
    if kg_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.KNOWLEDGE_GRAPH)
    if kg_path == ws.kg_autogenerated_path:
        logger.warning(f"Grafo sin curar: {kg_path.name}; cúralo a mano en {ws.kg_path.name}")

    with progress.step("load_instance", "Cargando la instancia (perfil, grafo y banco)"):
        if ws.exemplars_bank_path.is_file():
            with open(ws.exemplars_bank_path, encoding="utf-8") as f:
                bank = json.load(f)
        else:
            raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_BANK)

        exemplars_profile = ExemplarsProfile(profile_path)
        knowledge_graph = KnowledgeGraph(kg_path)

        logger.info(
            f"Perfil ({profile_path.name}): {len(exemplars_profile.item_types)} tipo(s) de ítem — "
            + ", ".join(exemplars_profile.item_types)
        )

        # Everything downstream resolves each item against the type it declares, so a bank
        # extracted before a type was added or renamed would fail deep inside the embedding
        # loop. One aggregated error here names the artifact that has to be rebuilt.
        unplaceable = exemplars_profile.unplaceable_items(bank)
        if unplaceable:
            sample = list(unplaceable.items())[:5]
            raise ValueError(
                f"{len(unplaceable)} bank item(s) do not match the exemplars profile "
                f"({profile_path.name}); the bank was built against a different one and "
                f"has to be rebuilt. First: "
                + "; ".join(f"{item_id}: {reason}" for item_id, reason in sample)
            )
        oversized = exemplars_profile.oversized_embed_items(
            bank, config.EMBEDDING_MAX_CHARS, config.EMBEDDING_FIELD_MAX_CHARS
        )
        if oversized:
            worst = sorted(oversized.items(), key=lambda pair: -pair[1])[:5]
            logger.warning(
                f"{len(oversized)} ítem(s) del banco superan los {config.EMBEDDING_MAX_CHARS:,} "
                "caracteres de presupuesto y pueden truncarse al indexarlos: "
                + ", ".join(f"{item_id} ({size:,})" for item_id, size in worst)
            )

        logger.info(
            f"Grafo ({kg_path.name}): {len(knowledge_graph.all_concepts)} concepto(s), "
            f"{len(knowledge_graph.taggable_concepts)} etiquetables, "
            f"{len(knowledge_graph.relation_details)} tipo(s) de relación"
        )
        nothing_excluded = not knowledge_graph.generic_non_taggable_concepts
        if not knowledge_graph.taggability_reviewed and nothing_excluded:
            logger.warning(
                f"Grafo ({kg_path.name}): etiquetabilidad sin revisar; los "
                f"{len(knowledge_graph.all_concepts)} concepto(s) se tratan como "
                "etiquetables, incluidos los que no identifican nada"
            )
        logger.info(
            f"Banco: {len(bank)} ítem(s), "
            f"{sum(1 for item in bank.values() if item.get('concepts'))} ya etiquetados"
        )

    embedder = make_embedder(ws, exemplars_profile, knowledge_graph)
    tagger = make_tagger(embedder, exemplars_profile)
    generator = ContentGenerator(
        knowledge_graph=knowledge_graph,
        exemplars_bank=bank,
        embedder=embedder,
        exemplars_profile=exemplars_profile,
        generator_model=config.CONTENT_GENERATION_LLM,
    )

    context = PipelineContext(
        exemplars_profile=exemplars_profile,
        knowledge_graph=knowledge_graph,
        embedder=embedder,
        exemplars_bank=bank,
        tagger=tagger,
        generator=generator,
        exemplars_profile_path=profile_path,
        knowledge_graph_path=kg_path,
        workspace=ws,
    )

    if tag:
        from .tag import tag_bank

        tag_bank(context)
    else:
        embedder.enrich_index_with_content(bank)

    return context
