import json
from dataclasses import dataclass

from loguru import logger

from .. import config
from ..concept_tagger import ConceptTagger
from ..content_generator import ContentGenerator
from ..content_profile import ContentProfile
from ..embedder import Embedder
from ..exemplars_bank import ExemplarsBank
from ..knowledge_graph import KnowledgeGraph
from . import _artifacts


@dataclass
class PipelineContext:
    content_profile: ContentProfile
    knowledge_graph: KnowledgeGraph
    embedder: Embedder
    exemplars_bank: dict
    generator: ContentGenerator


def initialize() -> PipelineContext:
    profile_path = _artifacts.content_profile_path()
    if profile_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.CONTENT_PROFILE)
    if profile_path == config.CONTENT_PROFILE_AUTOGENERATED_PATH:
        logger.warning(f"Using auto-drafted content profile: {profile_path}")

    kg_path = _artifacts.knowledge_graph_path()
    if kg_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.KNOWLEDGE_GRAPH)
    if kg_path == config.KG_AUTOGENERATED_PATH:
        logger.warning(
            f"Using auto-drafted KG for this run: {kg_path} — "
            f"curate it manually into {config.KG_PATH.name}"
        )

    bank = ExemplarsBank(config.EXEMPLARS_BANK_PATH).bank
    if bank is None:
        raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_BANK)

    content_profile = ContentProfile(profile_path)
    knowledge_graph = KnowledgeGraph(kg_path)

    embedder = Embedder(
        knowledge_graph,
        config.EMBEDDING_LLM,
        primary_field=content_profile.primary_field,
        context=content_profile.content_context,
    )
    tagger = ConceptTagger(
        embedder,
        config.CONCEPT_TAGGER_LLM,
        primary_field=content_profile.primary_field,
        context=content_profile.content_context,
    )

    annotated_bank = _annotate(bank, tagger)
    embedder.enrich_index_with_content(annotated_bank)

    generator = ContentGenerator(
        knowledge_graph=knowledge_graph,
        exemplars_bank=annotated_bank,
        embedder=embedder,
        content_profile=content_profile,
        generator_model=config.CONTENT_GENERATION_LLM,
    )

    return PipelineContext(
        content_profile=content_profile,
        knowledge_graph=knowledge_graph,
        embedder=embedder,
        exemplars_bank=annotated_bank,
        generator=generator,
    )


def _annotate(bank: dict, tagger: ConceptTagger) -> dict:
    if bank and all("concepts" in item for item in bank.values()):
        logger.info("Exemplars bank already annotated — skipping tagging")
        return bank

    annotated = tagger.tag_all(bank)
    config.EXEMPLARS_BANK_PATH.parent.mkdir(parents=True, exist_ok=True)
    with config.EXEMPLARS_BANK_PATH.open("w", encoding="utf-8") as f:
        json.dump(annotated, f, ensure_ascii=False, indent=2)
    logger.success(f"Saved {len(annotated)} annotated item(s) to {config.EXEMPLARS_BANK_PATH}")
    return annotated
