from contextlib import contextmanager

import pytest
from sqlalchemy import create_engine, select
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from server import review, storage
from server.db import Approval, Artifact, Base, instance_io, repository
from server.db import mirror
from variant_generator.core.workspace import Workspace

GRAPH = {"concepts_by_domains": {"D": ["A"]}, "relations": []}
PROFILE = {"fields": {}, "primary_field": "x"}


@pytest.fixture
def factory(monkeypatch):
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    Base.metadata.create_all(engine)
    make = sessionmaker(bind=engine, expire_on_commit=False)

    @contextmanager
    def scope():
        session = make()
        try:
            yield session
            session.commit()
        except BaseException:
            session.rollback()
            raise
        finally:
            session.close()

    monkeypatch.setattr(mirror, "session_scope", scope)
    return make


@pytest.fixture
def ws(tmp_path):
    return Workspace(root=tmp_path, slug="espejo")


def _rows(make, kind):
    with make() as session:
        return list(session.scalars(select(Artifact).where(Artifact.kind == kind)))


def test_an_edit_becomes_an_artifact_row(factory, ws):
    storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=review.KNOWLEDGE_GRAPH)

    rows = _rows(factory, review.KNOWLEDGE_GRAPH)
    assert [(r.stage, r.version) for r in rows] == [("curated", 1)]
    assert rows[0].content == GRAPH
    assert rows[0].sha256 == repository.content_sha256(GRAPH)
    assert ws.kg_path.is_file()


def test_the_draft_path_lands_in_the_draft_stage(factory, ws):
    storage.write_json(
        ws.exemplars_profile_autogenerated_path, PROFILE, ws=ws, artifact=review.EXEMPLARS_PROFILE
    )
    rows = _rows(factory, review.EXEMPLARS_PROFILE)
    assert [r.stage for r in rows] == ["draft"]


def test_identical_content_adds_no_version(factory, ws):
    for _ in range(2):
        storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=review.KNOWLEDGE_GRAPH)
    assert len(_rows(factory, review.KNOWLEDGE_GRAPH)) == 1

    storage.write_json(ws.kg_path, {**GRAPH, "x": 1}, ws=ws, artifact=review.KNOWLEDGE_GRAPH)
    assert sorted(r.version for r in _rows(factory, review.KNOWLEDGE_GRAPH)) == [1, 2]


def test_a_write_without_artifact_is_not_mirrored(factory, ws):
    storage.write_json(ws.content_context_path, {"subject": "x"})
    with factory() as session:
        assert session.scalars(select(Artifact)).first() is None


def test_approve_and_reopen_round_trip(factory, ws):
    storage.write_json(ws.exemplars_profile_path, PROFILE, ws=ws, artifact=review.EXEMPLARS_PROFILE)
    storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=review.KNOWLEDGE_GRAPH)
    storage.write_json(ws.exemplars_bank_path, {"i1": {}}, ws=ws, artifact=review.EXEMPLARS_BANK)

    state = review.ReviewState(ws)
    state.approve(review.EXEMPLARS_PROFILE)
    state.approve(review.KNOWLEDGE_GRAPH)
    state.approve(review.EXEMPLARS_BANK)

    with factory() as session:
        bank = session.scalar(select(Approval).where(Approval.kind == review.EXEMPLARS_BANK))
        assert bank is not None
        assert bank.sha256 == repository.content_sha256({"i1": {}})
        assert bank.upstream_hashes == {
            review.EXEMPLARS_PROFILE: repository.content_sha256(PROFILE),
            review.KNOWLEDGE_GRAPH: repository.content_sha256(GRAPH),
        }
        assert bank.artifact_id is not None

    state.reopen(review.EXEMPLARS_BANK)
    with factory() as session:
        assert session.scalar(select(Approval).where(Approval.kind == review.EXEMPLARS_BANK)) is None
        assert session.scalar(select(Approval).where(Approval.kind == review.KNOWLEDGE_GRAPH)) is not None


def test_import_after_the_mirror_adds_nothing(factory, ws):
    storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=review.KNOWLEDGE_GRAPH)
    review.ReviewState(ws).approve(review.KNOWLEDGE_GRAPH)

    with factory() as session:
        summary = instance_io.import_instance(session, ws, "espejo")
        session.commit()
    assert summary["approvals"] == 1
    assert len(_rows(factory, review.KNOWLEDGE_GRAPH)) == 1


def test_a_database_failure_never_breaks_the_write(monkeypatch, ws):
    @contextmanager
    def broken():
        raise OperationalError("connect", {}, Exception("sin base de datos"))
        yield

    monkeypatch.setattr(mirror, "session_scope", broken)
    warnings: list[str] = []
    from loguru import logger

    sink = logger.add(lambda m: warnings.append(m.record["message"]), level="WARNING")
    try:
        storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=review.KNOWLEDGE_GRAPH)
        review.ReviewState(ws).approve(review.KNOWLEDGE_GRAPH)
    finally:
        logger.remove(sink)

    assert ws.kg_path.is_file()
    assert review.ReviewState(ws).state(review.KNOWLEDGE_GRAPH)["status"] == "approved"
    assert len(warnings) == 2
    assert all(w.startswith("[bd] No se pudo reflejar «knowledge_graph» de «espejo»") for w in warnings)
