import json

import pytest

from server import approvals
from server.db import mirror
from server.jobs import handlers
from server.jobs.catalogue import Job
from variatio import entrypoints
from variatio.core.workspace import Workspace

CURATED = {"concepts_by_domains": {"Dominio inventado": ["A"]}, "relations": {}}
DRAFT = {"concepts_by_domains": {"Tema I": ["A"], "Tema II": ["B"]}, "relations": {}}


@pytest.fixture
def ws(tmp_path, monkeypatch):
    monkeypatch.setattr(mirror, "mirror_approval", lambda *a, **k: None)
    monkeypatch.setattr(mirror, "mirror_file", lambda *a, **k: None)
    workspace = Workspace(tmp_path / "aula", slug="aula")
    workspace.instance_dir.mkdir(parents=True)
    return workspace


def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8")


def test_retiring_moves_the_curated_file_to_history(ws):
    write(ws.kg_path, CURATED)
    write(ws.kg_autogenerated_path, DRAFT)

    assert approvals.retire_curated(ws, approvals.KNOWLEDGE_GRAPH) is True

    assert not ws.kg_path.is_file()
    assert entrypoints.knowledge_graph_path(ws) == ws.kg_autogenerated_path
    snapshots = list((ws.history_dir / approvals.KNOWLEDGE_GRAPH).iterdir())
    assert len(snapshots) == 1
    assert json.loads(snapshots[0].read_text(encoding="utf-8")) == CURATED


def test_a_first_build_has_nothing_to_retire(ws):
    write(ws.kg_autogenerated_path, DRAFT)

    assert approvals.retire_curated(ws, approvals.KNOWLEDGE_GRAPH) is False

    assert entrypoints.knowledge_graph_path(ws) == ws.kg_autogenerated_path
    assert not (ws.history_dir / approvals.KNOWLEDGE_GRAPH).exists()


def test_without_a_fresh_draft_the_curated_stays(ws):
    write(ws.kg_path, CURATED)

    assert approvals.retire_curated(ws, approvals.KNOWLEDGE_GRAPH) is False

    assert ws.kg_path.is_file()


def test_retiring_reopens_the_approval(ws):
    write(ws.kg_path, CURATED)
    write(ws.kg_autogenerated_path, DRAFT)
    approvals.Approvals(ws).approve(approvals.KNOWLEDGE_GRAPH)

    approvals.retire_curated(ws, approvals.KNOWLEDGE_GRAPH)

    state = approvals.Approvals(ws).state(approvals.KNOWLEDGE_GRAPH)
    assert state["status"] == "draft"
    assert state["is_autogenerated"] is True


def test_the_build_handler_retires_after_a_successful_build(ws, monkeypatch):
    write(ws.kg_path, CURATED)

    def fake_build(artifact, control):
        write(ws.kg_autogenerated_path, DRAFT)
        return {"ok": True}

    monkeypatch.setattr(handlers, "run_build", fake_build)
    monkeypatch.setattr(handlers.installation, "workspace_for", lambda slug: ws)
    handler = handlers._build(approvals.KNOWLEDGE_GRAPH)

    handler(Job(kind="build_kg", workspace="aula"), None)

    assert not ws.kg_path.is_file()
    assert entrypoints.knowledge_graph_path(ws) == ws.kg_autogenerated_path


def test_a_failed_build_retires_nothing(ws, monkeypatch):
    write(ws.kg_path, CURATED)

    def failing_build(artifact, control):
        raise RuntimeError("boom")

    monkeypatch.setattr(handlers, "run_build", failing_build)
    monkeypatch.setattr(handlers.installation, "workspace_for", lambda slug: ws)
    handler = handlers._build(approvals.KNOWLEDGE_GRAPH)

    with pytest.raises(RuntimeError):
        handler(Job(kind="build_kg", workspace="aula"), None)

    assert ws.kg_path.is_file()
    assert json.loads(ws.kg_path.read_text(encoding="utf-8")) == CURATED
