from contextlib import contextmanager

import pytest
from sqlalchemy import create_engine, select
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from server import approvals, storage
from server.db import Approval, Artifact, Base, instance_io, repository
from server.db import mirror
from variatio.core.workspace import Workspace

GRAPH = {"concepts_by_domains": {"D": ["A"]}, "relations": []}
PROFILE = {"fields": {}, "primary_field": "x"}


@pytest.fixture
def factory(monkeypatch):
    engine = create_engine(
        "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    Base.metadata.create_all(engine)
    make = sessionmaker(bind=engine, expire_on_commit=False)

    @contextmanager
    def scope():
        session = make()
        try:
            yield session
            session.commit()
        except BaseException:
            session.rollback()
            raise
        finally:
            session.close()

    monkeypatch.setattr(mirror, "session_scope", scope)
    return make


@pytest.fixture
def ws(tmp_path):
    return Workspace(root=tmp_path, slug="espejo")


def _rows(make, kind):
    with make() as session:
        return list(session.scalars(select(Artifact).where(Artifact.kind == kind)))


def test_an_edit_becomes_an_artifact_row(factory, ws):
    storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=approvals.KNOWLEDGE_GRAPH)

    rows = _rows(factory, approvals.KNOWLEDGE_GRAPH)
    assert [(r.stage, r.version) for r in rows] == [("curated", 1)]
    assert rows[0].content == GRAPH
    assert rows[0].sha256 == repository.content_sha256(GRAPH)
    assert ws.kg_path.is_file()


def test_the_draft_path_lands_in_the_draft_stage(factory, ws):
    storage.write_json(
        ws.exemplars_profile_autogenerated_path, PROFILE, ws=ws, artifact=approvals.EXEMPLARS_PROFILE
    )
    rows = _rows(factory, approvals.EXEMPLARS_PROFILE)
    assert [r.stage for r in rows] == ["draft"]


def test_identical_content_adds_no_version(factory, ws):
    for _ in range(2):
        storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=approvals.KNOWLEDGE_GRAPH)
    assert len(_rows(factory, approvals.KNOWLEDGE_GRAPH)) == 1

    storage.write_json(ws.kg_path, {**GRAPH, "x": 1}, ws=ws, artifact=approvals.KNOWLEDGE_GRAPH)
    assert sorted(r.version for r in _rows(factory, approvals.KNOWLEDGE_GRAPH)) == [1, 2]


def test_a_write_without_artifact_is_not_mirrored(factory, ws):
    storage.write_json(ws.content_context_path, {"subject": "x"})
    with factory() as session:
        assert session.scalars(select(Artifact)).first() is None


def test_approve_and_reopen_round_trip(factory, ws):
    storage.write_json(ws.exemplars_profile_path, PROFILE, ws=ws, artifact=approvals.EXEMPLARS_PROFILE)
    storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=approvals.KNOWLEDGE_GRAPH)
    storage.write_json(ws.exemplars_bank_path, {"i1": {}}, ws=ws, artifact=approvals.EXEMPLARS_BANK)

    state = approvals.Approvals(ws)
    state.approve(approvals.EXEMPLARS_PROFILE)
    state.approve(approvals.KNOWLEDGE_GRAPH)
    state.approve(approvals.EXEMPLARS_BANK)

    with factory() as session:
        bank = session.scalar(select(Approval).where(Approval.kind == approvals.EXEMPLARS_BANK))
        assert bank is not None
        assert bank.sha256 == repository.content_sha256({"i1": {}})
        assert bank.upstream_hashes == {
            approvals.EXEMPLARS_PROFILE: repository.content_sha256(PROFILE),
            approvals.KNOWLEDGE_GRAPH: repository.content_sha256(GRAPH),
        }
        assert bank.artifact_id is not None

    state.reopen(approvals.EXEMPLARS_BANK)
    with factory() as session:
        assert session.scalar(select(Approval).where(Approval.kind == approvals.EXEMPLARS_BANK)) is None
        assert session.scalar(select(Approval).where(Approval.kind == approvals.KNOWLEDGE_GRAPH)) is not None


def test_import_after_the_mirror_adds_nothing(factory, ws):
    storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=approvals.KNOWLEDGE_GRAPH)
    approvals.Approvals(ws).approve(approvals.KNOWLEDGE_GRAPH)

    with factory() as session:
        summary = instance_io.import_instance(session, ws, "espejo")
        session.commit()
    assert summary["approvals"] == 1
    assert len(_rows(factory, approvals.KNOWLEDGE_GRAPH)) == 1


def test_a_database_failure_never_breaks_the_write(monkeypatch, ws):
    @contextmanager
    def broken():
        raise OperationalError("connect", {}, Exception("sin base de datos"))
        yield

    monkeypatch.setattr(mirror, "session_scope", broken)
    warnings: list[str] = []
    from loguru import logger

    sink = logger.add(lambda m: warnings.append(m.record["message"]), level="WARNING")
    try:
        storage.write_json(ws.kg_path, GRAPH, ws=ws, artifact=approvals.KNOWLEDGE_GRAPH)
        approvals.Approvals(ws).approve(approvals.KNOWLEDGE_GRAPH)
    finally:
        logger.remove(sink)

    assert ws.kg_path.is_file()
    assert approvals.Approvals(ws).state(approvals.KNOWLEDGE_GRAPH)["status"] == "approved"
    assert len(warnings) == 2
    assert all(w.startswith("[bd] No se pudo reflejar «knowledge_graph» de «espejo»") for w in warnings)


# Best-effort was never meant to mean indistinguishable. A database that is down comes back
# and the next write catches up; content the database REFUSES never will. Measured on a
# reference installation: a bank whose extraction had left four NUL characters in it had a
# file of 151 items and a row of 152, and the only trace was one warning among many.
def test_a_refusal_is_reported_as_permanent_and_a_hiccup_as_a_hiccup():
    from sqlalchemy.exc import DataError, OperationalError

    from loguru import logger

    from server.db import mirror

    def caught(exc):
        seen = []
        sink = logger.add(lambda m: seen.append(m.record), level="WARNING")
        try:
            mirror._warn("exemplars_bank", "cs0-examenes", exc)
        finally:
            logger.remove(sink)
        return seen[0]

    refused = caught(
        DataError("INSERT INTO artifacts …", {"content": "…" * 5000},
                  Exception("unsupported Unicode escape sequence"))
    )
    assert refused["level"].name == "ERROR"
    assert "seguirá rechazando" in refused["message"]
    assert "unsupported Unicode escape sequence" in refused["message"]
    # The statement and its parameters must not end up in a log line.
    assert "INSERT INTO" not in refused["message"]

    hiccup = caught(
        OperationalError("SELECT 1", {}, Exception("server closed the connection"))
    )
    assert hiccup["level"].name == "WARNING"
    assert "No se pudo reflejar" in hiccup["message"]
