import pytest

from server import storage
from server.db.layout import locate
from server.editors import context_edit
from variatio.core.workspace import Workspace


@pytest.fixture
def ws(tmp_path):
    workspace = Workspace(root=tmp_path / "ws", slug="probe")
    workspace.instance_dir.mkdir(parents=True, exist_ok=True)
    return workspace


def test_the_first_save_has_nothing_to_snapshot(ws):
    context_edit.save(ws, "Primero", {"subject": "Programación"})

    assert storage.history(ws, context_edit.HISTORY_NAME) == []


def test_an_edit_leaves_the_previous_text_recoverable(ws):
    context_edit.save(ws, "Primero", {"subject": "Programación"})
    context_edit.save(ws, "Segundo", {"subject": "Programación"})

    snapshots = storage.history(ws, context_edit.HISTORY_NAME)
    assert len(snapshots) == 1

    restored = storage.read_json(ws.history_dir / context_edit.HISTORY_NAME / snapshots[0]["id"])
    assert restored["narrative"] == "Primero"
    assert context_edit.load(ws)["narrative"] == "Segundo"


def test_adopting_the_draft_snapshots_the_curated_text(ws):
    context_edit.save(ws, "A mano", {"subject": "Programación"})
    storage.write_json(
        ws.content_context_autogenerated_path,
        {"narrative": "Sintetizado", "subject": "Programación"},
    )

    context_edit.adopt_draft(ws)

    snapshots = storage.history(ws, context_edit.HISTORY_NAME)
    assert len(snapshots) == 1
    restored = storage.read_json(ws.history_dir / context_edit.HISTORY_NAME / snapshots[0]["id"])
    assert restored["narrative"] == "A mano"


def test_the_context_is_still_not_a_database_kind(ws):
    assert locate(ws, ws.content_context_path) is None
