"""A stage built from documents its slot no longer holds reads stale, and names them.

The record is the BUILD's, written by the handler off what the slot held when the build
started; the approval's `upstream` hashes are a different question (the artifacts above)
and are untouched. A stage nobody built through the API has no record and cannot be stale
for its documents — the CLI and `import-instance` arrive without one.
"""

import json
import os

import pytest

from server import approvals, raw_data
from server.db import mirror
from server.jobs import handlers
from variatio.core.workspace import Workspace

DRAFT = {"concepts_by_domains": {"Tema I": ["A"]}, "relations": {}}


@pytest.fixture
def ws(tmp_path, monkeypatch):
    monkeypatch.setattr(mirror, "mirror_approval", lambda *a, **k: None)
    monkeypatch.setattr(mirror, "mirror_file", lambda *a, **k: None)
    workspace = Workspace(tmp_path / "aula", slug="aula")
    workspace.instance_dir.mkdir(parents=True)
    workspace.raw_corpus_dir.mkdir(parents=True)
    workspace.raw_exemplars_dir.mkdir(parents=True)
    return workspace


def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8")


def drop(ws, slot, name, text="hola"):
    path = approvals.raw_directory(ws, slot) / name
    path.write_text(text, encoding="utf-8")
    return path


def built_graph(ws):
    """A graph built through the handler, from whatever the corpus holds right now."""
    write(ws.kg_autogenerated_path, DRAFT)
    approvals.record_built(ws, approvals.KNOWLEDGE_GRAPH, approvals.raw_documents(ws, "corpus"))


def state(ws, artifact=approvals.KNOWLEDGE_GRAPH):
    return approvals.Approvals(ws).state(artifact)


# THE RECORD ----------------------------------------------------------------------------------


def test_the_build_handler_records_what_the_slot_held_when_it_started(ws, monkeypatch):
    drop(ws, "corpus", "tema1.pdf")
    monkeypatch.setattr(handlers, "_workspace", lambda job: ws)
    monkeypatch.setattr(handlers.deps, "invalidate", lambda *a, **k: None)

    def build(artifact, control):
        # A document dropped in while the build runs is one it never read.
        drop(ws, "corpus", "tema2.pdf")
        write(ws.kg_autogenerated_path, DRAFT)
        return {"artifact": artifact}

    monkeypatch.setattr(handlers, "run_build", build)

    handlers.HANDLERS["build_kg"](handlers.Job(kind="build_kg", workspace="aula"), None)

    record = approvals.built_from(ws, approvals.KNOWLEDGE_GRAPH)
    assert record["slot"] == "corpus"
    assert list(record["documents"]) == ["tema1.pdf"]
    assert state(ws)["status"] == "stale"
    assert state(ws)["stale_because"][0]["added"] == ["tema2.pdf"]


def test_a_failed_build_records_nothing(ws, monkeypatch):
    drop(ws, "corpus", "tema1.pdf")
    monkeypatch.setattr(handlers, "_workspace", lambda job: ws)

    def boom(artifact, control):
        raise RuntimeError("se rompió")

    monkeypatch.setattr(handlers, "run_build", boom)

    with pytest.raises(RuntimeError):
        handlers.HANDLERS["build_kg"](handlers.Job(kind="build_kg", workspace="aula"), None)

    assert approvals.built_from(ws, approvals.KNOWLEDGE_GRAPH) is None


def test_a_stage_with_no_record_is_never_stale_for_its_documents(ws):
    write(ws.kg_autogenerated_path, DRAFT)
    drop(ws, "corpus", "tema1.pdf")

    assert state(ws)["status"] == "draft"
    assert state(ws)["stale_because"] == []


# THE DRIFT -----------------------------------------------------------------------------------


def test_nothing_changed_is_not_stale(ws):
    drop(ws, "corpus", "tema1.pdf")
    built_graph(ws)

    assert state(ws)["status"] == "draft"


def test_a_document_added_after_the_build_stales_the_draft_and_names_it(ws):
    drop(ws, "corpus", "tema1.pdf")
    built_graph(ws)
    drop(ws, "corpus", "tema2.pdf")

    result = state(ws)
    assert result["status"] == "stale"
    (cause,) = result["stale_because"]
    assert cause["slot"] == "corpus"
    assert cause["added"] == ["tema2.pdf"]
    assert cause["removed"] == [] and cause["changed"] == []
    assert "tema2.pdf" in cause["reason"]


def test_an_approved_stage_goes_stale_too_and_closes_the_gates_behind_it(ws):
    drop(ws, "exemplars", "hoja1.pdf")
    write(ws.exemplars_profile_autogenerated_path, {"fields": {}})
    approvals.record_built(ws, approvals.EXEMPLARS_PROFILE, approvals.raw_documents(ws, "exemplars"))
    approvals.Approvals(ws).approve(approvals.EXEMPLARS_PROFILE)
    assert state(ws, approvals.EXEMPLARS_PROFILE)["status"] == "approved"

    drop(ws, "exemplars", "hoja2.pdf")

    assert state(ws, approvals.EXEMPLARS_PROFILE)["status"] == "stale"
    assert approvals.Approvals(ws).gate_open(approvals.EXEMPLARS_BANK) is False


def test_removed_and_rewritten_documents_are_told_apart(ws):
    kept = drop(ws, "corpus", "tema1.pdf")
    drop(ws, "corpus", "tema2.pdf")
    built_graph(ws)
    (approvals.raw_directory(ws, "corpus") / "tema2.pdf").unlink()
    kept.write_text("otro contenido, otro tamaño", encoding="utf-8")
    # A rewrite of the same size still moves the mtime, and the signature reads it.
    os.utime(kept, ns=(kept.stat().st_atime_ns, kept.stat().st_mtime_ns + 5_000_000))

    (cause,) = state(ws)["stale_because"]
    assert cause["removed"] == ["tema2.pdf"]
    assert cause["changed"] == ["tema1.pdf"]
    assert cause["added"] == []


def test_a_file_the_builders_do_not_read_is_not_a_document(ws):
    drop(ws, "corpus", "tema1.pdf")
    built_graph(ws)
    drop(ws, "corpus", "notas.xyz")

    assert state(ws)["status"] == "draft"


def test_both_stages_fed_by_the_exemplars_stale_together(ws):
    drop(ws, "exemplars", "hoja1.pdf")
    write(ws.exemplars_profile_autogenerated_path, {"fields": {}})
    write(ws.exemplars_bank_path, {"C001": {}})
    for artifact in (approvals.EXEMPLARS_PROFILE, approvals.EXEMPLARS_BANK):
        approvals.record_built(ws, artifact, approvals.raw_documents(ws, "exemplars"))
    write(ws.kg_autogenerated_path, DRAFT)

    drop(ws, "exemplars", "hoja2.pdf")

    assert state(ws, approvals.EXEMPLARS_PROFILE)["status"] == "stale"
    assert state(ws, approvals.EXEMPLARS_BANK)["status"] == "stale"
    assert state(ws, approvals.KNOWLEDGE_GRAPH)["status"] == "draft"


# THE RECORD'S LIFE ---------------------------------------------------------------------------


def test_emptying_a_stage_drops_its_record(ws):
    drop(ws, "corpus", "tema1.pdf")
    built_graph(ws)

    approvals.discard(ws, approvals.KNOWLEDGE_GRAPH)

    assert approvals.built_from(ws, approvals.KNOWLEDGE_GRAPH) is None


def test_a_corrupt_record_file_reads_as_none(ws):
    write(ws.kg_autogenerated_path, DRAFT)
    ws.built_from_path.write_text("{no es json", encoding="utf-8")

    assert approvals.built_from(ws, approvals.KNOWLEDGE_GRAPH) is None
    assert state(ws)["status"] == "draft"


def test_raw_data_derives_its_feeds_from_the_one_table():
    for kind, slot in raw_data.SLOTS.items():
        assert slot["feeds"] == [a for a, s in approvals.RAW_SOURCE.items() if s == kind]
    assert raw_data.slot_feeding(approvals.EXEMPLARS_BANK) == "exemplars"
    assert raw_data.slot_feeding("tag") is None
