import type { VgEvent } from "./types";

/**
 * What the pipeline is doing, in words.
 *
 * The core emits step ids and raw log lines; both are written for whoever wrote the
 * code. This is the other half: for every step and every event that reaches the UI,
 * one sentence saying what is happening and why it takes as long as it does. It lives
 * here and not in the components so the drawer, the timeline and the log view all
 * describe the same run the same way.
 */

export interface JobExplain {
  what: string;
  produces: string;
  cost: string;
}

export const JOB_EXPLAIN: Record<string, JobExplain> = {
  transcribe: {
    what: "Copia cada página de los documentos de un origen a markdown, mirándolas como imagen, y decide cómo unir las que un ejercicio parte en dos. Las construcciones lo hacen por su cuenta si hace falta: esto solo lo adelanta.",
    produces: "cache/markdown/, una página por fichero, corregible a mano.",
    cost: "Una llamada al modelo por página, más una por costura entre páginas.",
  },
  build_profile: {
    what: "Lee una muestra de los ejemplares en bruto y deduce qué campos tiene un ítem y cómo se rellenan.",
    produces: "instance/exemplars_profile_autogenerated.json (un borrador que hay que curar).",
    cost: "Minutos. Un solo documento largo por pasada.",
  },
  build_kg: {
    what: "Extrae conceptos, dominios y relaciones del corpus, los limpia, fusiona duplicados, los organiza en dominios y revisa cuáles sirven como etiqueta.",
    produces: "instance/knowledge_graph_autogenerated.json (borrador; la curación final es manual).",
    cost: "Horas. Es el trabajo más caro de toda la cadena.",
  },
  build_bank: {
    what: "Convierte cada documento a markdown, lo trocea y extrae los ítems que valida contra el perfil de ejemplares.",
    produces: "instance/exemplars_bank.json, con checkpoint tras cada documento.",
    cost: "Decenas de minutos según cuántos documentos haya.",
  },
  describe_concepts: {
    what: "Escribe la prosa que describe cada concepto del grafo, a partir de los párrafos del corpus de teoría de los que salió. Es el texto contra el que se compara después, no el nombre. Indexar ya lo hace: esto solo lo adelanta o lo rehace.",
    produces: "cache/concept_descriptions.json.",
    cost: "Una llamada al modelo por concepto sin descripción.",
  },
  index: {
    what: "Carga la instancia y calcula los embeddings de las descripciones y del banco, fusionándolos en un índice por concepto.",
    produces: "cache/embeddings/*.npz y el contexto caliente en memoria.",
    cost: "Minutos en frío; segundos si la caché sigue siendo válida.",
  },
  warm_models: {
    what: "Descarga, si falta, y carga en la memoria del motor los modelos del siguiente paso: los del primer artefacto que queda por construir, o los de generación si la instancia está completa.",
    produces: "Nada en disco: los modelos residentes en el motor.",
    cost: "Segundos por modelo ya en disco; la descarga, si hace falta, tarda minutos.",
  },
  tag: {
    what: "Para cada ítem del banco recupera conceptos candidatos por similitud y los verifica con el modelo.",
    produces: "Las etiquetas 'concepts' y 'primary_concept' del banco, guardadas tras cada ítem.",
    cost: "Una o dos llamadas por ítem sin etiquetar.",
  },
  generate: {
    what: "Recupera ejemplos parecidos del banco, construye el prompt y genera ítems nuevos validándolos contra el esquema.",
    produces: "Los ítems que aparecen en la pantalla de generación.",
    cost: "Segundos por ítem, más la carga del modelo si acaba de cambiar.",
  },
  evaluate: {
    what: "Genera la misma consigna con las tres arquitecturas y las presenta a ciegas para que elijas sin saber cuál es cuál.",
    produces: "Una sesión de comparación con las tres propuestas y tu elección.",
    cost: "Tres generaciones seguidas: el triple que una generación normal.",
  },
};

export const STEP_EXPLAIN: Record<string, string> = {
  context:
    "Carga el perfil, el grafo y el banco, y calcula los embeddings que falten. La primera vez es lenta; después se reutiliza la caché.",
  warm_models:
    "Comprueba que cada modelo del siguiente paso está en disco, lo descarga si falta, y le manda una petición vacía para que el motor lo cargue en memoria.",
  load_instance: "Lee de disco los tres artefactos y valida que el perfil y el grafo cargan.",
  descriptions:
    "Escribe con el modelo la descripción de cada concepto contra los párrafos del corpus de teoría en los que aparece, y contrastándola con los conceptos con los que se podría confundir. Después mide cuáles han salido casi idénticas y solo reescribe esas. Se guarda tras cada una, así que cancelar no pierde lo hecho.",
  index_concepts: "Convierte cada descripción en un vector: es el lado del índice contra el que se busca.",
  embed_bank:
    "Convierte cada ítem del banco en un vector y lo funde con el de su concepto. Solo se re-embeben los ítems que han cambiado.",
  embed_queries:
    "Vectoriza de una tacada todos los enunciados por etiquetar, en lotes, para que el etiquetado no alterne entre el modelo de embeddings y el del tagger ítem a ítem.",
  tagging:
    "Por cada ítem: candidatos por similitud sobre los vectores ya calculados y, si hay más de uno plausible, una verificación del modelo.",
  guardrail:
    "Antes de que las instrucciones adicionales entren en el prompt, una comprobación fija bloquea las órdenes de anular instrucciones («olvida lo anterior…») y después un modelo juez decide si contienen algo dañino o un intento de saltarse las restricciones del ejercicio. Solo se ejecuta si has escrito algo.",
  admissibility:
    "Un modelo lee tu petición y decide si lo que pides es de lo que se pide en este campo o de lo que ya has decidido más arriba: los conceptos, la modalidad, los campos del ítem o la propia asignatura. Solo se ejecuta si has escrito algo.",
  generate:
    "Una variante por vuelta, con los mismos ejemplares en todas: prompt, generación en streaming y validación contra el esquema.",
  check:
    "Lo que el sistema puede comprobar de la variante sin juzgarla: si nombra algo no impartido, si se parece demasiado a un ejemplo o a otra del lote, y si el etiquetador la reconoce como el concepto pedido. Señales para quien la lee, no un rechazo.",
  build_exemplars_profile: "Infiere el esquema de un ítem a partir de los ejemplares en bruto.",
  build_knowledge_graph: "Construye el grafo desde el corpus: extracción, limpieza y curación.",
  build_exemplars_bank: "Extrae los ítems de los documentos y los valida contra el perfil.",
  sample: "Lee una muestra del corpus hasta llenar el presupuesto de contexto.",
  infer_profile: "Pide al modelo el esquema de campos y sus guías de extracción y generación.",
  kg_convert:
    "Docling convierte y trocea todo el corpus antes de extraer nada. El markdown se guarda en cache/markdown y se reutiliza mientras el original no cambie —recomponiendo de paso los acentos que los PDF de LaTeX parten en dos («M´etodo» → «Método»)—; el troceado corta por encabezados, no por longitud.",
  kg_extract:
    "Una llamada al modelo por fragmento, pidiendo conceptos y relaciones, con la ruta de encabezados del fragmento como contexto. Es la parte larga: la barra avanza fragmento a fragmento.",
  kg_clean:
    "Normaliza nombres y fusiona duplicados mecánicamente (mayúsculas, acentos, plurales) antes de preguntar nada al modelo.",
  kg_merge:
    "Los nombres se agrupan por parecido con sus propios embeddings y el modelo decide, grupo a grupo, cuáles son de verdad el mismo concepto. Solo se pregunta por lo dudoso.",
  kg_drop:
    "Por lotes y sin razonamiento, qué nodos no nombran un concepto de la materia: metadatos del documento, escenarios de los ejemplos y trozos de frase. Se decide leyendo el nombre, no deliberando.",
  kg_domains:
    "Reparte todos los conceptos ya limpios en los bloques temáticos del temario, y vuelve a preguntar por los que se hayan quedado fuera para que no acaben en «Sin clasificar». De aquí sale la estructura que usan el enlazado y la revisión de etiquetabilidad.",
  kg_link:
    "Una pasada por dominio buscando las relaciones que faltan dentro de él —sobre todo el orden en que hay que enseñarlos— y una última pasada solo para las que cruzan de un dominio a otro.",
  kg_curate:
    "Agrupa las relaciones por tipo y rompe los ciclos que el grafo no admite. Es determinista, sin modelo.",
  kg_taggability:
    "Una pasada por dominio decidiendo qué conceptos sirven de etiqueta: los que valen para cualquier ítem («codificación», «diseño») se marcan como no etiquetables. Al terminar se escribe el borrador.",
  convert: "Docling convierte el documento a markdown antes de extraer nada.",
  extract: "Un documento tras otro, guardando el banco después de cada uno.",
  extract_batches: "El documento se trocea y cada trozo se extrae por separado para que quepa en contexto.",
};

export function stepExplain(id: string): string | null {
  return STEP_EXPLAIN[id] ?? null;
}

export type ActivityTone = "info" | "good" | "warn" | "bad";

export interface ActivityLine {
  seq: number;
  ts: number;
  text: string;
  tone: ActivityTone;
}

/** The one-line, plain-Spanish version of an event, or null when it is not worth a line. */
export function describeEvent(event: VgEvent): { text: string; tone: ActivityTone } | null {
  switch (event.kind) {
    case "job.queued":
      return { text: `${event.job?.label ?? "Trabajo"} en cola`, tone: "info" };
    case "job.started":
      return { text: `${event.job?.label ?? "Trabajo"} iniciado`, tone: "info" };
    case "job.finished":
      return { text: `${event.job?.label ?? "Trabajo"} completado`, tone: "good" };
    case "job.failed":
      return { text: `Falló: ${event.job?.error ?? "error desconocido"}`, tone: "bad" };
    case "job.cancelling":
      return { text: "Cancelación solicitada; parando en el próximo punto seguro", tone: "warn" };
    case "job.cancelled":
      return { text: "Trabajo cancelado", tone: "warn" };

    case "step.started":
      return { text: event.label ?? `Paso ${event.id}`, tone: "info" };
    case "step.finished":
      if (event.status === "failed") {
        return { text: `Paso «${event.id}» fallido: ${event.error ?? ""}`, tone: "bad" };
      }
      if (event.status === "cancelled") return { text: `Paso «${event.id}» cancelado`, tone: "warn" };
      return null;

    case "retrieval": {
      const candidates = event.candidates ?? [];
      if (candidates.length === 0) {
        return { text: "Ningún concepto superó el umbral de similitud", tone: "warn" };
      }
      const best = candidates[0];
      return {
        text: `${candidates.length} candidato(s); mejor: ${best[0]} (${best[1].toFixed(3)})`,
        tone: "info",
      };
    }
    case "guardrail":
      if (!event.checked) {
        return { text: "No se pudieron revisar las instrucciones; siguen adelante", tone: "warn" };
      }
      if (event.ok) return { text: "Instrucciones adicionales revisadas: correctas", tone: "good" };
      return { text: `Instrucciones bloqueadas por «${event.criteria}»`, tone: "bad" };
    case "admissibility":
      if (!event.checked) {
        return { text: "No se pudo revisar el alcance; la petición entra sin tipar", tone: "warn" };
      }
      if (event.ok) {
        return { text: `Petición admitida: ${(event.slots ?? []).join(", ")}`, tone: "good" };
      }
      return { text: `Bloqueada: «${event.term}» lo decide ${event.owner}`, tone: "bad" };
    case "few_shot": {
      const used = (event.items ?? event.ids ?? []).length;
      if (used === 0) {
        return { text: "Sin ejemplares en el banco: se genera en zero-shot", tone: "warn" };
      }
      return {
        text: `${used} ejemplar(es) del banco usados para el few-shot prompting`,
        tone: "info",
      };
    }
    case "prompt":
      return {
        text: `Prompt enviado (${(event.text ?? "").length.toLocaleString("es-ES")} caracteres)`,
        tone: "info",
      };
    case "repair":
      return {
        text: `JSON no válido en ${event.where}; reintento ${event.attempt}/${event.max_attempts}`,
        tone: "warn",
      };
    case "item.retried":
      return {
        text: `Ítem ${event.index} rechazado, reintento ${event.attempt}: ${(event.reasons ?? []).join("; ")}`,
        tone: "warn",
      };
    case "item.produced":
      return event.checks?.flags?.length
        ? { text: `Ítem ${event.index} generado, con ${event.checks.flags.length} señal(es)`, tone: "warn" }
        : { text: `Ítem ${event.index} generado y validado`, tone: "good" };
    case "item.saved":
      return { text: `Ítem ${event.index} guardado en «Mis variantes»`, tone: "good" };
    case "item.rejected":
      return { text: `Ítem ${event.index} descartado: no valida contra el esquema`, tone: "warn" };
    case "item.tagged":
      return {
        text: `${event.id ?? "Ítem"} etiquetado${
          event.concepts?.length ? `: ${event.concepts.join(", ")}` : " sin conceptos"
        }`,
        tone: event.concepts?.length ? "good" : "warn",
      };
    case "artifact.progress":
      return { text: `${event.name}: ${event.count} elemento(s) guardados`, tone: "info" };

    default:
      return null;
  }
}
