import type { VgEvent } from "./types";

/**
 * What the pipeline is doing, in words.
 *
 * The core emits step ids and raw log lines; both are written for whoever wrote the
 * code. This is the other half: for every step and every event that reaches the UI,
 * one sentence saying what is happening and why it takes as long as it does. It lives
 * here and not in the components so the drawer, the timeline and the log view all
 * describe the same run the same way.
 */

export interface JobExplain {
  what: string;
  produces: string;
  cost: string;
}

export const JOB_EXPLAIN: Record<string, JobExplain> = {
  build_profile: {
    what: "Lee una muestra de los ejemplares en bruto y deduce qué campos tiene un ítem y cómo se rellenan.",
    produces: "instance/content_profile_autogenerated.json (un borrador que hay que curar).",
    cost: "Minutos. Un solo documento largo por pasada.",
  },
  build_kg: {
    what: "Extrae conceptos, dominios y relaciones del corpus, los limpia, fusiona duplicados y los organiza en dominios.",
    produces: "instance/knowledge_graph_autogenerated.json (borrador; la curación final es manual).",
    cost: "Horas. Es el trabajo más caro de toda la cadena.",
  },
  build_bank: {
    what: "Convierte cada documento a markdown, lo trocea y extrae los ítems que valida contra el perfil de contenido.",
    produces: "instance/exemplars_bank.json, con checkpoint tras cada documento.",
    cost: "Decenas de minutos según cuántos documentos haya.",
  },
  describe_concepts: {
    what: "Escribe la prosa que describe cada concepto del grafo. Es el texto contra el que se compara después, no el nombre.",
    produces: "cache/concept_descriptions.json.",
    cost: "Una llamada al modelo por concepto sin descripción.",
  },
  index: {
    what: "Carga la instancia y calcula los embeddings de las descripciones y del banco, fusionándolos en un índice por concepto.",
    produces: "cache/embeddings/*.npz y el contexto caliente en memoria.",
    cost: "Minutos en frío; segundos si la caché sigue siendo válida.",
  },
  tag: {
    what: "Para cada ítem del banco recupera conceptos candidatos por similitud y los verifica con el modelo.",
    produces: "Las etiquetas 'concepts' y 'primary_concept' del banco, guardadas tras cada ítem.",
    cost: "Una o dos llamadas por ítem sin etiquetar.",
  },
  generate: {
    what: "Recupera ejemplos parecidos del banco, construye el prompt y genera ítems nuevos validándolos contra el esquema.",
    produces: "Los ítems que aparecen en la pantalla de generación.",
    cost: "Segundos por ítem, más la carga del modelo si acaba de cambiar.",
  },
};

export const STEP_EXPLAIN: Record<string, string> = {
  context:
    "Carga el perfil, el grafo y el banco, y calcula los embeddings que falten. La primera vez es lenta; después se reutiliza la caché.",
  load_instance: "Lee de disco los tres artefactos y valida que el perfil y el grafo cargan.",
  descriptions:
    "Escribe con el modelo la descripción de cada concepto. Se guarda tras cada uno, así que cancelar no pierde lo hecho.",
  index_concepts: "Convierte cada descripción en un vector: es el lado del índice contra el que se busca.",
  embed_bank:
    "Convierte cada ítem del banco en un vector y lo funde con el de su concepto. Solo se re-embeben los ítems que han cambiado.",
  tagging:
    "Por cada ítem: candidatos por similitud y, si hay más de uno plausible, una verificación del modelo.",
  generate: "Un ítem por vuelta: ejemplos, prompt, generación en streaming y validación contra el esquema.",
  build_content_profile: "Infiere el esquema de un ítem a partir de los ejemplares en bruto.",
  build_knowledge_graph: "Construye el grafo desde el corpus: extracción, limpieza y curación.",
  build_exemplars_bank: "Extrae los ítems de los documentos y los valida contra el perfil.",
  sample: "Lee una muestra del corpus hasta llenar el presupuesto de contexto.",
  infer_profile: "Pide al modelo el esquema de campos y sus guías de extracción y generación.",
  kg_extract: "Recorre el corpus por trozos pidiendo entidades y relaciones. Es la parte larga.",
  kg_clean: "Normaliza nombres, fusiona duplicados y rompe los ciclos que el grafo no admite.",
  kg_curate: "Agrupa los conceptos en dominios y vacía la bolsa de «Sin clasificar».",
  convert: "Docling convierte el documento a markdown antes de extraer nada.",
  extract: "Un documento tras otro, guardando el banco después de cada uno.",
  extract_batches: "El documento se trocea y cada trozo se extrae por separado para que quepa en contexto.",
};

export function stepExplain(id: string): string | null {
  if (id.startsWith("model:")) {
    return "Ollama está cargando los pesos en la GPU. Solo ocurre al cambiar de modelo, y son segundos en los que parece que no pasa nada.";
  }
  return STEP_EXPLAIN[id] ?? null;
}

export type ActivityTone = "info" | "good" | "warn" | "bad";

export interface ActivityLine {
  seq: number;
  ts: number;
  text: string;
  tone: ActivityTone;
}

/** The one-line, plain-Spanish version of an event, or null when it is not worth a line. */
export function describeEvent(event: VgEvent): { text: string; tone: ActivityTone } | null {
  switch (event.kind) {
    case "job.queued":
      return { text: `${event.job?.label ?? "Trabajo"} en cola`, tone: "info" };
    case "job.started":
      return { text: `${event.job?.label ?? "Trabajo"} iniciado`, tone: "info" };
    case "job.finished":
      return { text: `${event.job?.label ?? "Trabajo"} completado`, tone: "good" };
    case "job.failed":
      return { text: `Falló: ${event.job?.error ?? "error desconocido"}`, tone: "bad" };
    case "job.cancelling":
      return { text: "Cancelación solicitada; parando en el próximo punto seguro", tone: "warn" };
    case "job.cancelled":
      return { text: "Trabajo cancelado", tone: "warn" };

    case "step.started":
      return { text: event.label ?? `Paso ${event.id}`, tone: "info" };
    case "step.finished":
      if (event.status === "failed") {
        return { text: `Paso «${event.id}» fallido: ${event.error ?? ""}`, tone: "bad" };
      }
      if (event.status === "cancelled") return { text: `Paso «${event.id}» cancelado`, tone: "warn" };
      return null;

    case "model.loading":
      return { text: `Cargando el modelo ${event.model} en la GPU (${event.role})`, tone: "info" };

    case "retrieval": {
      const candidates = event.candidates ?? [];
      if (candidates.length === 0) {
        return { text: "Ningún concepto superó el umbral de similitud", tone: "warn" };
      }
      const best = candidates[0];
      return {
        text: `${candidates.length} candidato(s); mejor: ${best[0]} (${best[1].toFixed(3)})`,
        tone: "info",
      };
    }
    case "few_shot":
      return {
        text: `${(event.ids ?? []).length} ejemplo(s) del banco usados como few-shot`,
        tone: "info",
      };
    case "prompt":
      return {
        text: `Prompt enviado (${(event.text ?? "").length.toLocaleString("es-ES")} caracteres)`,
        tone: "info",
      };
    case "repair":
      return {
        text: `JSON no válido en ${event.where}; reintento ${event.attempt}/${event.max_attempts}`,
        tone: "warn",
      };
    case "item.produced":
      return { text: `Ítem ${event.index} generado y validado`, tone: "good" };
    case "item.rejected":
      return { text: `Ítem ${event.index} descartado: no valida contra el esquema`, tone: "warn" };
    case "item.tagged":
      return {
        text: `${event.id ?? "Ítem"} etiquetado${
          event.concepts?.length ? `: ${event.concepts.join(", ")}` : " sin conceptos"
        }`,
        tone: event.concepts?.length ? "good" : "warn",
      };
    case "artifact.progress":
      return { text: `${event.name}: ${event.count} elemento(s) guardados`, tone: "info" };

    default:
      return null;
  }
}
