export type ArtifactName = "content_profile" | "knowledge_graph" | "exemplars_bank";

export type ArtifactStatus = "missing" | "building" | "draft" | "approved" | "stale";

export type JobKind =
  | "build_profile"
  | "build_kg"
  | "build_bank"
  | "describe_concepts"
  | "index"
  | "tag"
  | "generate"
  | "evaluate";

export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";

export interface StaleCause {
  artifact: ArtifactName;
  label: string;
  reason: string;
}

export interface StageState {
  artifact: ArtifactName;
  label: string;
  status: ArtifactStatus;
  hash: string | null;
  path: string | null;
  is_autogenerated: boolean;
  approved_at: string | null;
  stale_because: StaleCause[];
  blocked_by: string[];
  blocked_reason: string | null;
  build_job: JobKind;
}

export interface Pipeline {
  stages: StageState[];
  generation_unlocked: boolean;
  current_job: Job | null;
  queued: number;
}

export interface Job {
  id: string;
  kind: JobKind;
  params: Record<string, unknown>;
  status: JobStatus;
  created_at: number;
  started_at: number | null;
  finished_at: number | null;
  error: string | null;
  result: Record<string, any> | null;
  label: string;
  artifact: ArtifactName | null;
  elapsed_ms: number | null;
}

export interface Health {
  engine: string;
  host: string;
  available: boolean;
  models: { required: Record<string, string>; installed: string[]; missing: string[] };
  context_ready: boolean;
  paths: {
    instance: string;
    raw_exemplars: string;
    raw_corpus: string;
    raw_exemplars_exists: boolean;
    raw_corpus_exists: boolean;
  };
  busy: boolean;
}

/* Raw source data ------------------------------------------------------------------ */

export type RawKind = "corpus" | "exemplars";

export interface RawFile {
  name: string;
  bytes: number;
  modified: number;
  extension: string;
}

export interface RawSlot {
  kind: RawKind;
  label: string;
  purpose: string;
  feeds: ArtifactName[];
  path: string;
  exists: boolean;
  files: RawFile[];
  bytes: number;
}

export interface RawListing {
  supported_extensions: string[];
  max_bytes: number;
  slots: RawSlot[];
}

export interface RawUpload {
  added: { name: string; bytes: number; renamed: boolean }[];
  rejected: { name: string; reason: string }[];
  slot: RawSlot;
}

/* Content profile ------------------------------------------------------------------ */

export interface FieldSpec {
  schema: Record<string, any>;
  description?: string;
  guidance?: { extraction?: string; generation?: string };
  /** Who chooses the value. Absent means "model": only "user" fields are asked for. */
  decided_by?: "user" | "model";
}

/** One modality of exercise: its own fields, its own primary and its own rules. */
export interface ItemTypeSpec {
  label?: string;
  description?: string;
  primary_field: string;
  /** Fields read together to decide which concept the item practises. Defaults to
   *  [primary_field]; the solution is deliberately never in it. */
  embed_fields?: string[];
  general_generation_rules?: string[];
  fields: Record<string, FieldSpec>;
}

export interface ContentProfile {
  /** Shared by every modality: it describes the subject, not the exercise. */
  content_context: Record<string, string>;
  item_types: Record<string, ItemTypeSpec>;
}

export interface GenerateParams {
  n: number;
  concepts: string[];
  item_type?: string;
  fixed?: Record<string, unknown>;
  curriculum?: string[];
  instructions?: string;
}

export interface ProfilePayload {
  exists: boolean;
  profile: ContentProfile | null;
  path: string | null;
  is_autogenerated?: boolean;
}

/* Knowledge graph ------------------------------------------------------------------ */

export interface KgConcept {
  name: string;
  domain: string;
  taggable: boolean;
  degree: number;
  description: string | null;
  exemplars: number;
}

export interface KgSummary {
  path: string;
  domains: { name: string; concepts: string[] }[];
  concepts: KgConcept[];
  relations: { name: string; details: Record<string, any>; edges: number }[];
  totals: {
    domains: number;
    concepts: number;
    taggable: number;
    described: number;
    with_exemplars: number;
  };
}

export interface GraphRelation {
  /** The verbose label, which is also the name the edit endpoints speak. */
  key: string;
  verbose?: string;
  /** Schema key when the relation is one the builder knows about: what fixes its colour. */
  type?: string;
  directed: boolean;
  acyclic?: boolean;
  use_in_embedding?: boolean;
  prerequisite?: boolean;
  count: number;
}

export interface GraphView {
  meta: {
    title: string;
    kind: string;
    generated: string;
    isolated: number;
    /** Index into `relations` of the prerequisite relation, or null when there is none. */
    prerequisite?: number | null;
  };
  relations: GraphRelation[];
  groups: { name: string; count: number }[];
  /** [name, groupIndex, nonTaggable] */
  nodes: [string, number, number][];
  /** [sourceIndex, targetIndex, relationIndex] */
  links: [number, number, number][];
}

/* Exemplars bank ------------------------------------------------------------------- */

export interface TaggingTrace {
  candidates: [string, number][];
  method:
    | "single_dominant"
    | "llm"
    | "llm_thinking"
    | "llm_wide"
    | "llm_wide_thinking"
    | "rejected"
    | "failed"
    | "no_candidates"
    | "manual";
  model?: string;
  threshold?: number;
}

export interface BankItem {
  id: string;
  source?: string;
  item_type?: string;
  concepts?: string[];
  primary_concept?: string | null;
  _tagging?: TaggingTrace;
  [field: string]: unknown;
}

export interface BankItemType {
  key: string;
  label: string;
  description: string;
  primary_field: string;
  embed_fields: string[];
  fields: string[];
  count: number;
}

/** One exemplar exactly as it went into the few-shot block of the prompt. */
export interface FewShotExemplar {
  id: string;
  item: Record<string, unknown>;
}

export interface BankListing {
  items: BankItem[];
  total: number;
  page: number;
  page_size: number;
  item_types: BankItemType[];
  default_type: string;
  sources: string[];
  totals: { items: number; tagged: number; untagged: number };
  thresholds: { similarity: number; top_k: number };
}

export interface Coverage {
  counts: Record<string, number>;
  covered: number;
  total: number;
  without_exemplars: string[];
}

/* Evaluation ----------------------------------------------------------------------- */

export type EvaluationArm = "naive" | "rag" | "system";

export type ArmStatus = "ok" | "failed" | "unavailable";

/**
 * One proposal, as the server chooses to describe it.
 *
 * Before the choice everything past `item` is absent — and that is not the client being
 * polite: the server never sends it. `status` is narrowed to "ok" | "no_item" too,
 * because "unavailable" would point at the commercial arm before a card is read.
 */
export interface EvaluationPosition {
  position: number;
  status: ArmStatus | "no_item";
  item: Record<string, unknown> | null;
  arm?: EvaluationArm;
  arm_label?: string;
  model?: string;
  provider?: string;
  prompt?: string;
  raw_response?: string;
  exemplar_ids?: string[];
  elapsed_ms?: number;
  error?: string | null;
}

export type Usability = "as_is" | "with_edits" | "no";

export interface EvaluationRating {
  arm: string;
  originality?: number;
  complexity?: number;
  concept_fit?: number;
  soundness?: number;
  usability?: Usability;
  comment?: string;
  rated_at?: number;
}

export interface EvaluationSessionHead {
  id: string;
  created_at: number;
  job_id: string | null;
  concepts: string[];
  item_type: string;
  fixed: Record<string, unknown>;
  curriculum: string[];
  instructions: string;
  revealed: boolean;
  choice: number | null;
  choice_arm: EvaluationArm | null;
  chosen_at: number | null;
  evaluator_note: string | null;
  rating: EvaluationRating | null;
  seed: number | null;
}

export interface EvaluationDetail {
  session: EvaluationSessionHead;
  positions: EvaluationPosition[];
}

export interface EvaluationSummary {
  id: string;
  created_at: number;
  concepts: string[];
  item_type: string;
  instructions: string;
  choice: number | null;
  choice_arm: EvaluationArm | null;
  chosen_at: number | null;
  rated: boolean;
  /** Empty until the session is judged: before that it would name the blind cards. */
  arm_status: Partial<Record<EvaluationArm, ArmStatus>>;
  without_item: number;
}

export interface EvaluationAggregates {
  sessions: number;
  decided: number;
  rated: number;
  preferences: Record<string, number>;
  arm_status: Record<string, Record<string, number>>;
  rubric: {
    n: number;
    usability?: Record<Usability, number>;
    [dimension: string]: any;
  };
}

export interface EvaluationListing {
  sessions: EvaluationSummary[];
  total: number;
  limit: number;
  offset: number;
  aggregates: EvaluationAggregates;
  arms: { key: EvaluationArm; label: string }[];
  external: { provider: string; model: string; configured: boolean; reason: string | null };
}

export interface EvaluationParams {
  concepts: string[];
  item_type?: string;
  fixed?: Record<string, unknown>;
  curriculum?: string[];
  instructions?: string;
}

/* Events --------------------------------------------------------------------------- */

export interface VgEvent {
  seq: number;
  ts: number;
  job_id: string | null;
  kind: string;
  [payload: string]: any;
}
