export type ArtifactName = "exemplars_profile" | "knowledge_graph" | "exemplars_bank";

export type ArtifactStatus = "missing" | "building" | "draft" | "approved" | "stale";

export type JobKind =
  | "build_profile"
  | "build_kg"
  | "build_bank"
  | "describe_concepts"
  | "index"
  | "warm_models"
  | "tag"
  | "review_taggability"
  | "generate"
  | "evaluate";

export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";

export interface StaleCause {
  artifact: ArtifactName;
  label: string;
  reason: string;
}

export interface StageState {
  artifact: ArtifactName;
  label: string;
  status: ArtifactStatus;
  hash: string | null;
  path: string | null;
  is_autogenerated: boolean;
  approved_at: string | null;
  stale_because: StaleCause[];
  blocked_by: string[];
  blocked_reason: string | null;
  build_job: JobKind;
}

export interface Pipeline {
  stages: StageState[];
  generation_unlocked: boolean;
  /** The running job **of this workspace**; null when the GPU is busy with someone else's. */
  current_job: Job | null;
  queued: number;
  queue_length: number;
  queue_ahead: number | null;
  /** Somebody, anybody, is holding the one GPU. The honest reason a job has not started. */
  engine_busy: boolean;
  engine_busy_elsewhere: boolean;
}

/**
 * One phase of a build: what it is called and what share of the bar it owns.
 *
 * A weight is a share of the WORK, not of the clock. There is no time estimate anywhere
 * any more: what a phase costs depends on which models the instance is pointed at, and
 * those change — a figure measured against one set of models is a claim about that set,
 * so it goes stale silently the moment the config does.
 */
export interface BuildPhase {
  key: string;
  label: string;
  weight: number;
}

export interface BuildPlans {
  artifacts: Record<ArtifactName, BuildPhase[]>;
  /** Plans of jobs that write no artifact and still have phases. */
  jobs: Partial<Record<JobKind, BuildPhase[]>>;
}

/**
 * What the free-text field of a commission may and may not ask for.
 *
 * Derived by the server from this instance's own artifacts, so another workspace answers
 * something else without a line changing here. The terms each owner decides stay on the
 * server: the screen names the control, never its values.
 */
export interface CommissionScope {
  slots: { key: string; label: string; example: string }[];
  owners: { key: string; label: string; where: string }[];
  facts: { key: string; value: string }[];
}

export interface Job {
  id: string;
  kind: JobKind;
  workspace: string;
  user_id: number | null;
  user_name: string | null;
  params: Record<string, unknown>;
  status: JobStatus;
  created_at: number;
  started_at: number | null;
  finished_at: number | null;
  error: string | null;
  result: Record<string, any> | null;
  label: string;
  artifact: ArtifactName | null;
  elapsed_ms: number | null;
  /** 1-based place in the shared queue; 0 or absent means "not waiting". */
  queue_position?: number;
}

/**
 * A model resident in the engine RIGHT NOW, as `/api/ps` reports it.
 *
 * It is the only real measure of what the machine is using: `required` only says what
 * `config.py` names, and a named constant is not a loaded model. `expires_at` is what tells
 * a VRAM eviction from the residency timer running out.
 */
export interface RunningModel {
  model: string;
  size: number | null;
  size_vram: number | null;
  context_length: number | null;
  expires_at: string | null;
}

export interface Health {
  engine: string;
  host: string;
  available: boolean;
  models: {
    required: Record<string, string>;
    installed: string[];
    missing: string[];
    /** Required models a remote provider serves: never on this disk, never «sin instalar». */
    remote: string[];
    running: RunningModel[];
  };
  context_ready: boolean;
  paths: {
    instance: string;
    raw_exemplars: string;
    raw_corpus: string;
    raw_exemplars_exists: boolean;
    raw_corpus_exists: boolean;
  };
  busy: boolean;
}

/* Raw source data ------------------------------------------------------------------ */

export type RawKind = "corpus" | "exemplars";

export interface RawFile {
  name: string;
  bytes: number;
  modified: number;
  extension: string;
}

export interface RawSlot {
  kind: RawKind;
  label: string;
  purpose: string;
  feeds: ArtifactName[];
  path: string;
  exists: boolean;
  files: RawFile[];
  bytes: number;
}

export interface RawListing {
  supported_extensions: string[];
  max_bytes: number;
  slots: RawSlot[];
}

export interface RawUpload {
  added: { name: string; bytes: number; renamed: boolean }[];
  rejected: { name: string; reason: string }[];
  slot: RawSlot;
}

/* Exemplars profile ------------------------------------------------------------------ */

export interface FieldSpec {
  schema: Record<string, any>;
  description?: string;
  guidance?: { extraction?: string; generation?: string };
  /** Who chooses the value. Absent means "model": only "user" fields are asked for. */
  decided_by?: "user" | "model";
}

/** One modality of exercise: its own fields, its own primary and its own rules. */
export interface ItemTypeSpec {
  label?: string;
  description?: string;
  primary_field: string;
  /** Fields read together to decide which concept the item practises. Defaults to
   *  [primary_field]; the solution is deliberately never in it. */
  embed_fields?: string[];
  general_generation_rules?: string[];
  fields: Record<string, FieldSpec>;
}

export interface ExemplarsProfile {
  /** Shared by every modality: it describes the subject, not the exercise. */
  item_types: Record<string, ItemTypeSpec>;
}

export interface GenerateParams {
  n: number;
  concepts: string[];
  item_type?: string;
  fixed?: Record<string, unknown>;
  curriculum?: string[];
  instructions?: string;
  /** Whether the model deliberates before writing: `false` is off, a string names the
   *  effort level, and absent means yes at the default level, as it always did. */
  think?: boolean | string;
}

export interface ProfilePayload {
  exists: boolean;
  profile: ExemplarsProfile | null;
  path: string | null;
  is_autogenerated?: boolean;
  pending_draft?: import("@/features/profile/drift").ProfilePendingDraft | null;
}

/* Knowledge graph ------------------------------------------------------------------ */

export interface KgConcept {
  name: string;
  domain: string;
  taggable: boolean;
  degree: number;
  description: string | null;
  exemplars: number;
  /** Only the modalities the bank's items declare; an untyped item is in `exemplars` alone. */
  exemplars_by_type: Record<string, number>;
}

export interface KgSummary {
  path: string;
  domains: { name: string; concepts: string[] }[];
  concepts: KgConcept[];
  relations: { name: string; details: Record<string, any>; edges: number }[];
  totals: {
    domains: number;
    concepts: number;
    taggable: number;
    described: number;
    with_exemplars: number;
    taggability_reviewed: boolean;
  };
}

/**
 * Where a concept came from: the literal piece of the theory corpus it appears in.
 *
 * The graph build writes it and the prompt that composes the description reads it, so it is
 * also what to look at to judge the description: whether the text describes the material or
 * what the model already knew about the topic.
 */
export interface ConceptSource {
  document: string;
  location: string;
  text: string;
}

export interface GraphRelation {
  /** The verbose label, which is also the name the edit endpoints speak. */
  key: string;
  verbose?: string;
  /** Schema key when the relation is one the builder knows about: what fixes its colour. */
  type?: string;
  directed: boolean;
  acyclic?: boolean;
  use_in_embedding?: boolean;
  prerequisite?: boolean;
  count: number;
}

export interface GraphView {
  meta: {
    title: string;
    kind: string;
    generated: string;
    isolated: number;
    /** Index into `relations` of the prerequisite relation, or null when there is none. */
    prerequisite?: number | null;
  };
  relations: GraphRelation[];
  groups: { name: string; count: number }[];
  /** [name, groupIndex, nonTaggable] */
  nodes: [string, number, number][];
  /** [sourceIndex, targetIndex, relationIndex] */
  links: [number, number, number][];
}

/**
 * `dropped` is computed against the whole graph, not the taggable set: a curriculum
 * declares coverage, so a non-taggable concept in it is legitimate and only a concept
 * the graph no longer has at all stops counting.
 */
export interface CurriculumState {
  concepts: string[];
  updated_at: string | null;
  dropped: string[];
}

/* Exemplars bank ------------------------------------------------------------------- */

export interface TaggingTrace {
  candidates: [string, number][];
  method:
    | "single_dominant"
    | "llm"
    | "llm_thinking"
    | "llm_wide"
    | "llm_wide_thinking"
    | "rejected"
    | "failed"
    | "no_candidates"
    | "manual";
  model?: string;
  threshold?: number;
}

export interface BankItem {
  id: string;
  source?: string;
  item_type?: string;
  concepts?: string[];
  primary_concept?: string | null;
  _tagging?: TaggingTrace;
  [field: string]: unknown;
}

export interface BankItemType {
  key: string;
  label: string;
  description: string;
  primary_field: string;
  embed_fields: string[];
  fields: string[];
  count: number;
}

/** One exemplar exactly as it went into the few-shot block of the prompt. */
export interface FewShotExemplar {
  id: string;
  item: Record<string, unknown>;
  /** `neighbour` is an exemplar of a direct prerequisite, shown as form and not as objective. */
  origin?: "primary" | "secondary" | "neighbour";
}

export interface BankListing {
  items: BankItem[];
  total: number;
  page: number;
  page_size: number;
  item_types: BankItemType[];
  default_type: string;
  sources: string[];
  totals: { items: number; tagged: number; untagged: number };
  thresholds: { similarity: number; top_k: number };
}

export interface Coverage {
  counts: Record<string, number>;
  covered: number;
  total: number;
  without_exemplars: string[];
}

/* Identity ------------------------------------------------------------------------- */

export type Role = "viewer" | "editor" | "owner";

export interface CurrentUser {
  id: number;
  /** What you type to enter, and how you are named everywhere in the app. */
  username: string;
  /** Optional: a delivery address for a link, never an identity. */
  email: string | null;
  name: string;
  is_admin: boolean;
}

export interface WorkspaceMembership {
  slug: string;
  name: string;
  role: Role;
  active: boolean;
}

/** A live login of this account: what the profile screen lists so you can spot one you
 *  do not recognise. Never another account's — this is only ever your own. */
export interface Session {
  user: CurrentUser;
  workspaces: WorkspaceMembership[];
  /** Where this account lands when a tab has no preference of its own. */
  active_workspace: string | null;
  /** Role in that workspace; null when the account is a member of nothing at all. */
  role: Role | null;
}

/* Workspaces ----------------------------------------------------------------------- */

export interface WorkspaceRow {
  slug: string;
  name: string;
  role: Role | null;
  active: boolean;
  /** Listed only because the account administers the installation, not by membership. */
  as_admin: boolean;
}

export interface WorkspaceListing {
  workspaces: WorkspaceRow[];
  active: string | null;
  can_create: boolean;
}

export interface WorkspaceSummary {
  slug: string;
  name: string;
  role: Role;
  stages: { artifact: ArtifactName; label: string; status: ArtifactStatus }[];
  ready: boolean;
  generations: number;
}

/* Saved variants -------------------------------------------------------------------- */

export interface GenerationAuthor {
  id: number | null;
  name: string | null;
  username: string | null;
}

export interface ItemChecks {
  forbidden: string[];
  similarity: { to: string; score: number; high: boolean } | null;
  tagger?: {
    primary: string | null;
    concepts: string[];
    method: string | null;
    on_target: boolean;
    targets_found: string[];
  };
  flags: string[];
  /** The two hard signals alone (a forbidden mention, a near copy) ask for a retry. */
  verdict?: "accept" | "retry";
  reasons?: string[];
}

export interface GenerationRow {
  id: number;
  created_at: number;
  job_id: string | null;
  item_type: string;
  concepts: string[];
  curriculum: string[];
  fixed: Record<string, unknown>;
  instructions: string;
  think: boolean;
  author: GenerationAuthor;
  promoted_item_id: string | null;
  item: Record<string, unknown>;
  checks?: ItemChecks | null;
}

export interface GenerationListing {
  generations: GenerationRow[];
  total: number;
  limit: number;
  offset: number;
  scope: "mine" | "workspace";
}

export interface GenerationDetail {
  generation: GenerationRow & { thinking: string | null };
}

/* Administration -------------------------------------------------------------------- */

export interface AdminAccount {
  id: number;
  username: string;
  name: string;
  is_admin: boolean;
  disabled: boolean;
  created_at: string | null;
  workspaces: { slug: string; role: Role }[];
  generations: number;
  evaluations: number;
  decided: number;
  /** Sessions usable right now: not revoked and not past either expiry. */
  sessions: number;
  /** Seconds the login rate limiter still refuses this account; 0 when it is not locked. */
  locked_seconds: number;
  email: string | null;
}

export interface DiskUsage {
  raw: number;
  instance: number;
  cache: number;
  history: number;
  total: number;
}

export interface AdminWorkspace {
  id: number;
  slug: string;
  name: string;
  created_at: string | null;
  members: number;
  generations: number;
  /** Its pipeline context is in memory right now: what the LRU registry is holding. */
  warm: boolean;
  /** Its chain, so a stage can be emptied without switching to that instance. */
  stages: {
    artifact: ArtifactName;
    label: string;
    status: ArtifactStatus;
    is_autogenerated: boolean;
  }[];
  disk: DiskUsage;
}

export interface AdminOverview {
  totals: {
    users: number;
    workspaces: number;
    generations: number;
    evaluations: number;
    decided: number;
  };
  accounts: AdminAccount[];
  workspaces: AdminWorkspace[];
  engine: {
    busy: boolean;
    job: Job | null;
    queued: number;
    warm_contexts: string[];
  };
}

export interface AdminJobQueue {
  running: Job | null;
  queued: (Job & { queue_position: number })[];
}

export interface TunnelStatus {
  configured: boolean;
  host: string;
  local_port: number | null;
  remote_port: number;
  autostart: boolean;
  /** The administrator asked for it; `running` says whether `ssh` is alive right now. */
  wanted: boolean;
  running: boolean;
  pid: number | null;
  since: number | null;
  attempts: number;
  last_error: string | null;
  stderr: string[];
}

export interface PullStatus {
  model: string;
  status: "running" | "succeeded" | "failed";
  completed: number;
  total: number;
  started_at: number;
  finished_at: number | null;
  error: string | null;
  user: string | null;
}

export type ModelResidency = "cargado" | "en disco" | "sin instalar" | "remoto";

/** One rolling window of one model's Cerebras quota. `resets_in` is when the oldest call
 *  inside it ages out — the API sends no `reset` header, so the window is reconstructed
 *  from our own timestamps. */
export interface CerebrasWindow {
  requests_used: number;
  requests_limit: number;
  requests_remaining: number;
  tokens_used: number;
  tokens_limit: number;
  tokens_remaining: number;
  resets_in: number;
}

export interface CerebrasPhase {
  phase: string;
  requests: number;
  prompt_tokens: number;
  completion_tokens: number;
  tokens: number;
}

export interface CerebrasModel {
  model: string;
  windows: { minute: CerebrasWindow; day: CerebrasWindow };
  phases: CerebrasPhase[];
}

export interface CerebrasState {
  /** The active engine routes to Cerebras; false means the card is history, not live. */
  active: boolean;
  configured: boolean;
  /** What the configuration sends to Cerebras. */
  routed: string[];
  max_wait: number;
  /** What has actually been spent — empty until the first call, and not the same set. */
  usage: CerebrasModel[];
  inflight: {
    model: string;
    phase: string | null;
    since: number;
    elapsed: number;
    /** Set only while the throttle is holding the call back. */
    waiting_until: number | null;
  } | null;
}

export interface AdminEngine {
  engine: string;
  host: string;
  available: boolean;
  running: RunningModel[];
  installed: (InstalledModel & { asked_by: string[] })[];
  required: { model: string; asked_by: string[]; state: ModelResidency }[];
  idle: { seconds: number; threshold: number; poll: number };
  busy: boolean;
  contexts: string[];
  pulls: PullStatus[];
  tunnel: TunnelStatus;
  /** Absent when the API is older than this client: version skew must not blank the tab. */
  cerebras?: CerebrasState;
}

export interface AdminSystem {
  database: {
    location: string;
    revision: string | null;
    head: string | null;
    tables: Record<string, number>;
  };
  process: { started_at: number; uptime_seconds: number; log_level: string };
}

export interface InvitePreview {
  role: Role;
  workspace: string | null;
  expires_at: string;
}

export interface InviteRow {
  id: number;
  role: Role;
  workspace: string | null;
  workspace_slug: string | null;
  created_at: string;
  expires_at: string;
  created_by: string | null;
}

/* Events --------------------------------------------------------------------------- */

export interface VgEvent {
  seq: number;
  ts: number;
  job_id: string | null;
  kind: string;
  [payload: string]: any;
}

/** The subject's context: prose plus the three facts the naive arm reads by name. */
export interface ContentContextState {
  exists: boolean;
  narrative: string;
  facts: Record<string, string>;
  block: string;
  source: "curated" | "draft" | null;
  path: string | null;
  /** The text the last build synthesised and the curated one is covering. */
  pending_draft: string | null;
  canonical_keys: string[];
}

/* Configuration ---------------------------------------------------------------------- */

export type ConfigSource = "default" | "file" | "env";
export type ConfigImpact = "none" | "engine" | "contexts" | "reindex" | "locked";

export type ConfigSetting = {
  key: string;
  name: string;
  kind: string;
  group: string;
  doc: string;
  impact: ConfigImpact;
  editable: boolean;
  source: ConfigSource;
  env: string | null;
  choices: string[] | null;
  minimum: number | null;
  maximum: number | null;
  nullable: boolean;
  secret: boolean;
  value?: unknown;
  default?: unknown;
  state?: "configurada" | "ausente";
};

export interface InstalledModel {
  model: string;
  /** Served by a remote provider (Cerebras): listable and selectable, never on this disk. */
  remote?: boolean;
  /** Bytes on disk, as Ollama reports them: an approximation of what it will take resident. */
  size: number | null;
}

export type ReasoningFixed = "grammar" | "commission" | "model";

export type ReasoningPhase = {
  key: string;
  label: string;
  model: string;
  setting: string | null;
  effort: string | null;
  fixed: ReasoningFixed | null;
  note: string;
};

export type ReasoningLane = { key: string; label: string; phases: ReasoningPhase[] };

export type ConfigPayload = {
  groups: string[];
  settings: ConfigSetting[];
  pipeline: ReasoningLane[];
  /** What the engine offers; both empty when it is unreachable. */
  models: { installed: InstalledModel[]; running: RunningModel[] };
  applied?: string[];
};

export type CerebrasCatalog = {
  models: string[];
  source: "api" | "config";
  error: string | null;
};
