"""Which file each instance artifact is read from, and which of them are missing.

Curated over draft, everywhere: a build only ever writes the `_autogenerated` file, and a
hand-curated one beside it wins. Every path is derived from a `Workspace` that the caller
had to name — nothing here falls back to an instance nobody asked for.
"""

import json
from pathlib import Path

from ..core.workspace import Workspace
from ..instance.content_context import ContentContext, load_for, resolve_path

EXEMPLARS_PROFILE = "exemplars_profile"
KNOWLEDGE_GRAPH = "knowledge_graph"
EXEMPLARS_BANK = "exemplars_bank"


class MissingArtifactError(Exception):
    """Raised when a stage needs an artifact the workspace has not built."""

    def __init__(self, artifact: str):
        """Name the artifact on the exception, so a caller can act on which one it was."""
        self.artifact = artifact
        super().__init__(f"Missing instance artifact '{artifact}'")


def missing_artifacts(ws: Workspace) -> list[str]:
    """Return the artifacts still to be built, in the order they have to be built in."""
    missing = []
    if exemplars_profile_path(ws) is None:
        missing.append(EXEMPLARS_PROFILE)
    if knowledge_graph_path(ws) is None:
        missing.append(KNOWLEDGE_GRAPH)
    if not ws.exemplars_bank_path.is_file():
        missing.append(EXEMPLARS_BANK)
    return missing


def exemplars_profile_path(ws: Workspace) -> Path | None:
    """Return the curated profile, else the draft, else None."""
    if ws.exemplars_profile_path.is_file():
        return ws.exemplars_profile_path
    if ws.exemplars_profile_autogenerated_path.is_file():
        return ws.exemplars_profile_autogenerated_path
    return None


def knowledge_graph_path(ws: Workspace) -> Path | None:
    """Return the curated graph, else the draft, else None.

    A file only counts once it declares `concepts_by_domains`: half a build, or a stub,
    is not a graph.
    """
    if _json_has_key(ws.kg_path, "concepts_by_domains"):
        return ws.kg_path
    if _json_has_key(ws.kg_autogenerated_path, "concepts_by_domains"):
        return ws.kg_autogenerated_path
    return None


def content_context_path(ws: Workspace) -> Path | None:
    """Return the curated subject context, else the draft, else None.

    Deliberately absent from `missing_artifacts`: the context has no builder and no `raw/`
    slot, so "absent" is never a step somebody skipped — it is what a workspace looks like
    before either of the other builds has run.
    """
    return resolve_path(ws)


def load_content_context(ws: Workspace) -> ContentContext:
    """Load the workspace's subject context, curated over draft."""
    return load_for(ws)


def _json_has_key(path: str | Path, key: str) -> bool:
    """Return whether a readable JSON object at `path` declares `key`."""
    path = Path(path)
    if not path.is_file():
        return False
    try:
        with path.open(encoding="utf-8") as f:
            return key in json.load(f)
    except (json.JSONDecodeError, OSError):
        return False
