"""Phase 0 — authoring the instance artifacts from `raw/`.

The only entry point that imports a BUILDER, which is what keeps Docling and torch out
of every other import path. A build writes exactly one artifact, and always the `_autogenerated`
one: curating it is a separate, manual act.
"""

from pathlib import Path

from loguru import logger

from ..builders import (
    exemplars_bank_builder,
    exemplars_profile_builder,
    knowledge_graph_builder,
)
from ..builders.exemplars_bank_builder import ExemplarsBankBuilder
from ..builders.exemplars_profile_builder import ExemplarsProfileBuilder
from ..builders.knowledge_graph_builder import KnowledgeGraphBuilder
from ..core import progress
from ..core.json_io import write_json
from ..core.workspace import Workspace
from ..instance.exemplars_profile import ExemplarsProfile
from ..instance.knowledge_graph import KnowledgeGraph
from . import _artifacts
from .initialize import make_embedder, make_tagger


def build_exemplars_profile(ws: Workspace) -> dict:
    """Infer a draft exemplars profile from the raw exemplars."""
    logger.info("Building the exemplars profile draft")

    profile = ExemplarsProfileBuilder(workspace=ws).build(
        ws.raw_exemplars_dir, ws.exemplars_profile_autogenerated_path
    )

    if not profile:
        raise RuntimeError(f"Could not draft a exemplars profile from {ws.raw_exemplars_dir}")

    return profile


def build_knowledge_graph(ws: Workspace) -> dict:
    """Extract, clean and curate a draft knowledge graph from the raw corpus."""
    logger.info("Building the knowledge graph draft")
    return KnowledgeGraphBuilder(workspace=ws).build(ws.raw_corpus_dir)


def build_exemplars_bank(
    ws: Workspace,
    exemplars_profile: ExemplarsProfile | None = None,
) -> dict:
    """Extract the exemplars bank, tagging each document as it leaves the extractor.

    Extracting and tagging are one job: an untagged bank is useless for generating and for
    indexing alike. Tagging per document also gives the warm start its within-build form —
    document 3's items are tagged against an index already holding 1 and 2.
    """
    if exemplars_profile is None:
        path = _artifacts.exemplars_profile_path(ws)
        if path is None:
            raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_PROFILE)
        exemplars_profile = ExemplarsProfile(path)

    logger.info("Building the exemplars bank")
    bank = ExemplarsBankBuilder(
        exemplars_profile,
        workspace=ws,
        content_context=_artifacts.load_content_context(ws),
    ).build(
        ws.raw_exemplars_dir,
        ws.exemplars_bank_path,
        ws.exemplars_bank_building_path,
        on_items=_tagging_hook(ws, exemplars_profile, ws.exemplars_bank_building_path),
    )
    if not bank:
        raise RuntimeError(f"Could not build an exemplars bank from {ws.raw_exemplars_dir}")
    return bank


def _tagging_hook(ws: Workspace, exemplars_profile: ExemplarsProfile, path: Path):
    """Return the callback that tags each freshly extracted document, or None.

    Without a graph there is nothing to tag with, and that is not an error: the bank is
    extracted anyway and stays pending for `entrypoints.tag_bank`.

    `path` is the file the build is writing, which is not the artifact: the tags land where
    the items they belong to are, and reach `exemplars_bank.json` when the build promotes
    what it has made.
    """
    kg_path = _artifacts.knowledge_graph_path(ws)
    if kg_path is None:
        logger.warning(
            "No knowledge graph: the items are extracted untagged"
        )
        return None

    # Lazy: building the `Embedder` indexes every concept and writes the missing
    # descriptions, which is minutes. Doing it here would put that BEFORE the plan's first
    # phase, with the bar stuck at 0 %.
    state: dict = {}

    def ready():
        """Build the embedder and tagger on first use, then reuse them."""
        if not state:
            content_context = _artifacts.load_content_context(ws)
            embedder = make_embedder(
                ws, exemplars_profile, KnowledgeGraph(kg_path), content_context
            )
            state["embedder"] = embedder
            state["tagger"] = make_tagger(ws, embedder, exemplars_profile, content_context)
        return state["embedder"], state["tagger"]

    def annotate(bank: dict, new_ids: list[str]) -> dict:
        """Tag the newly extracted items against an index refreshed with the whole bank."""
        embedder, tagger = ready()
        # The whole bank first: it embeds only what is new and re-merges the centroids,
        # which is what makes the previous documents' tags count.
        embedder.enrich_index_with_content(bank)
        working = dict(bank)

        def checkpoint(item_id: str, item: dict) -> None:
            """Persist after every item, so a document's tags are never half in memory."""
            working[item_id] = item
            write_json(path, working)

        try:
            return tagger.tag_all(bank, ids=new_ids, on_item=checkpoint)
        except BaseException:
            write_json(path, working)
            raise

    return annotate


_BUILDERS = {
    _artifacts.EXEMPLARS_PROFILE: build_exemplars_profile,
    _artifacts.KNOWLEDGE_GRAPH: build_knowledge_graph,
    _artifacts.EXEMPLARS_BANK: build_exemplars_bank,
}


_LABELS = {
    _artifacts.EXEMPLARS_PROFILE: "Exemplars profile",
    _artifacts.KNOWLEDGE_GRAPH: "Knowledge graph",
    _artifacts.EXEMPLARS_BANK: "Exemplars bank",
}

# Each builder declares what its phases cost; installing the plan here is what turns
# "some step is running" into a percentage of the whole build, for all three alike.
_PHASES = {
    _artifacts.EXEMPLARS_PROFILE: exemplars_profile_builder.BUILD_PHASES,
    _artifacts.KNOWLEDGE_GRAPH: knowledge_graph_builder.BUILD_PHASES,
    _artifacts.EXEMPLARS_BANK: exemplars_bank_builder.BUILD_PHASES,
}


def build_phases(artifact: str) -> tuple[tuple[str, str, int], ...]:
    """Return the `(key, label, weight)` plan a build of this artifact will run through."""
    if artifact not in _PHASES:
        raise ValueError(f"Unknown artifact '{artifact}'; expected one of {list(_PHASES)}")
    return _PHASES[artifact]


_MODELS = {
    _artifacts.EXEMPLARS_PROFILE: exemplars_profile_builder.build_models,
    _artifacts.KNOWLEDGE_GRAPH: knowledge_graph_builder.build_models,
    _artifacts.EXEMPLARS_BANK: exemplars_bank_builder.build_models,
}


def build_models(artifact: str) -> list[str]:
    """Return the models a build of this artifact will call, in order and without repeats.

    The builder's own declaration, not a second copy: it is what the queue reserves a lane
    from and what `ensure_models` checks before the first phase.
    """
    if artifact not in _MODELS:
        raise ValueError(f"Unknown artifact '{artifact}'; expected one of {list(_MODELS)}")
    return list(dict.fromkeys(_MODELS[artifact]()))


def build_missing(ws: Workspace) -> list[str]:
    """Build every artifact the workspace lacks, and return which ones those were.

    `missing_artifacts` orders the profile before the bank, because the bank builder needs
    the profile.
    """
    missing = _artifacts.missing_artifacts(ws)
    for artifact in missing:
        progress.checkpoint()
        build_artifact(artifact, ws)
    return missing


def build_artifact(artifact: str, ws: Workspace) -> dict:
    """Build one artifact, with its phase plan installed so progress is a percentage."""
    if artifact not in _BUILDERS:
        raise ValueError(f"Unknown artifact '{artifact}'; expected one of {list(_BUILDERS)}")

    with progress.step(f"build_{artifact}", f"Building: {_LABELS[artifact]}"), progress.overall(_PHASES[artifact]):
        return _BUILDERS[artifact](ws=ws)
