import json

import pytest

from variant_generator import config
from variant_generator.builders import _context
from variant_generator.core.workspace import Workspace
from variant_generator.instance.content_context import ContentContext


class FakeResponse:
    def __init__(self, response: str):
        self.response = response


@pytest.fixture
def answer(monkeypatch):
    """Pin what the model replies, and record the prompt it was given."""
    seen: dict = {}

    def install(payload: dict):
        def fake_generate(**kwargs):
            seen.update(kwargs)
            return FakeResponse(json.dumps(payload, ensure_ascii=False))

        monkeypatch.setattr(_context.inference, "generate", fake_generate)
        return seen

    return install


def payload(narrative: str, **extra) -> dict:
    return {
        "narrative": narrative,
        "subject": extra.get("subject", "Programación I"),
        "educational_level": extra.get("educational_level", "primer curso"),
        "language_of_instruction": extra.get("language_of_instruction", "español"),
    }


def test_the_synthesis_writes_the_draft(tmp_path, answer):
    ws = Workspace(root=tmp_path, slug="t")
    answer(payload("Programación I, primer curso, en español."))

    result = _context.synthesize(ws, "- Fundamentos\n- Bucles", "EL GRAFO", "m")

    assert result.narrative == "Programación I, primer curso, en español."
    assert ws.content_context_autogenerated_path.is_file()
    assert ContentContext.load(ws.content_context_autogenerated_path).subject == "Programación I"


# The point of the draft/curated pair: a build must never overwrite what a person wrote.
# Without this, every rebuild would paraphrase the curated text one more time, which is
# the drift the pair exists to stop.
def test_the_synthesis_never_touches_the_curated_file(tmp_path, answer):
    ws = Workspace(root=tmp_path, slug="t")
    ws.instance_dir.mkdir(parents=True, exist_ok=True)
    ContentContext({"narrative": "Lo escribí yo."}).save(ws.content_context_path)
    answer(payload("Lo reescribió el modelo."))

    _context.synthesize(ws, "- Fundamentos", "EL GRAFO", "m")

    assert ContentContext.load(ws.content_context_path).narrative == "Lo escribí yo."
    assert (
        ContentContext.load(ws.content_context_autogenerated_path).narrative
        == "Lo reescribió el modelo."
    )


# The call is a MERGE, so what is already there has to reach the prompt. A synthesis that
# never saw the previous text could only ever replace it.
def test_the_existing_context_reaches_the_prompt(tmp_path, answer):
    ws = Workspace(root=tmp_path, slug="t")
    ws.instance_dir.mkdir(parents=True, exist_ok=True)
    ContentContext({"narrative": "Se usa la convención OBJ/PRE."}).save(ws.content_context_path)
    seen = answer(payload("Cualquier cosa."))

    _context.synthesize(ws, "- Fundamentos", "EL GRAFO", "m")

    assert "Se usa la convención OBJ/PRE." in seen["prompt"]
    assert "- Fundamentos" in seen["prompt"]
    assert "EL GRAFO" in seen["prompt"]


def test_the_first_synthesis_says_there_is_nothing_yet(tmp_path, answer):
    ws = Workspace(root=tmp_path, slug="t")
    seen = answer(payload("Primera vez."))

    _context.synthesize(ws, "- Fundamentos", "EL PERFIL", "m")

    assert "Ninguno todavía" in seen["prompt"]


# Grammar and reasoning are not compatible on this stack, and with the channel closed a
# reasoning model deliberates into the answer -- which here would be saved as the subject.
def test_the_call_is_constrained_and_does_not_think(tmp_path, answer):
    ws = Workspace(root=tmp_path, slug="t")
    seen = answer(payload("Prosa."))

    _context.synthesize(ws, "- Fundamentos", "EL GRAFO", "m")

    assert seen["think"] is False
    assert seen["format"] == _context.CONTENT_CONTEXT_SCHEMA


def test_an_unusable_answer_keeps_what_was_there(tmp_path, answer, monkeypatch):
    ws = Workspace(root=tmp_path, slug="t")
    ws.instance_dir.mkdir(parents=True, exist_ok=True)
    ContentContext({"narrative": "Lo que había."}).save(ws.content_context_autogenerated_path)
    monkeypatch.setattr(config, "MAX_JSON_REPAIR_TRIES", 0)
    answer({"narrative": "   "})

    assert _context.synthesize(ws, "- Fundamentos", "EL GRAFO", "m") is None
    assert (
        ContentContext.load(ws.content_context_autogenerated_path).narrative == "Lo que había."
    )


def test_the_narrative_is_capped_on_a_sentence(tmp_path, answer, monkeypatch):
    ws = Workspace(root=tmp_path, slug="t")
    monkeypatch.setattr(config, "CONTENT_CONTEXT_MAX_CHARS", 40)
    answer(payload("Una frase corta. Y otra que ya se pasa del techo impuesto."))

    result = _context.synthesize(ws, "- Fundamentos", "EL GRAFO", "m")

    assert result.narrative == "Una frase corta."


def test_clipping_falls_back_to_a_word_boundary_not_a_character(tmp_path):
    assert _context._clip("palabras sueltas sin punto final", 20) == "palabras sueltas…"


def test_text_under_the_cap_is_untouched(tmp_path):
    assert _context._clip("Cabe entero.", 900) == "Cabe entero."
