import json

from variant_generator.core.workspace import Workspace
from variant_generator.instance.content_context import ContentContext
from variant_generator.stages import _artifacts


def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")


def test_absent_context_is_falsy_and_renders_nothing(tmp_path):
    context = ContentContext.load(tmp_path / "nope.json")
    assert not context
    assert context.prompt_block() == ""


def test_narrative_is_the_prompt_block_verbatim(tmp_path):
    path = tmp_path / "content_context.json"
    prose = "Introducción a la Programación, primer curso de grado. Todo el código es Python 3."
    write(path, {"narrative": prose, "subject": "Introducción a la Programación"})

    context = ContentContext.load(path)

    assert context
    assert context.prompt_block() == prose


def test_canonical_fields_are_readable_by_name(tmp_path):
    path = tmp_path / "content_context.json"
    write(
        path,
        {
            "narrative": "Da igual lo que diga la prosa.",
            "subject": "Introducción a la Programación",
            "educational_level": "Primer curso de grado",
            "language_of_instruction": "español",
        },
    )

    context = ContentContext.load(path)

    assert context.subject == "Introducción a la Programación"
    assert context.educational_level == "Primer curso de grado"
    assert context.language_of_instruction == "español"


def test_missing_canonical_fields_are_empty_strings_not_none(tmp_path):
    path = tmp_path / "content_context.json"
    write(path, {"narrative": "Sólo prosa."})

    context = ContentContext.load(path)

    assert context.subject == ""
    assert context.educational_level == ""
    assert context.language_of_instruction == ""


# The legacy shape is the flat key->value dict that lived under the profile's
# `content_context`. Every prompt rendered it as `- key: value`, so that is what a context
# with no narrative still has to produce: an instance that has not been migrated must read
# exactly as it did before, or moving the file changes what every prompt says.
def test_legacy_flat_dict_renders_as_it_always_did(tmp_path):
    path = tmp_path / "content_context.json"
    legacy = {
        "subject": "Introducción a la Programación",
        "educational_level": "Primer curso de grado",
        "language_of_instruction": "español",
        "programming_language": "Python",
    }
    write(path, legacy)

    context = ContentContext.load(path)

    assert context
    assert context.prompt_block() == "\n".join(f"- {k}: {v}" for k, v in legacy.items())
    assert context.subject == "Introducción a la Programación"


def test_from_legacy_keeps_the_keys_that_are_not_canonical(tmp_path):
    context = ContentContext.from_legacy(
        {"subject": "Física", "programming_language": "Python", "notacion": "SI"}
    )

    block = context.prompt_block()
    assert "programming_language: Python" in block
    assert "notacion: SI" in block


def test_narrative_wins_over_the_field_listing(tmp_path):
    path = tmp_path / "content_context.json"
    write(path, {"narrative": "La prosa manda.", "subject": "Física", "otro": "dato"})

    assert ContentContext.load(path).prompt_block() == "La prosa manda."


def test_round_trip_through_save(tmp_path):
    path = tmp_path / "content_context.json"
    original = ContentContext.from_legacy({"subject": "Física", "unidad": "SI"})
    original.narrative = "Física de primero, en español."
    original.save(path)

    reloaded = ContentContext.load(path)

    assert reloaded.narrative == "Física de primero, en español."
    assert reloaded.subject == "Física"
    assert reloaded.prompt_block() == "Física de primero, en español."


# Same rule as the graph and the profile: the hand-curated file wins, and the draft is
# what a build writes. Without it, rebuilding the graph would overwrite the text somebody
# corrected -- which is the whole reason the pair exists.
def test_curated_wins_over_draft(tmp_path):
    ws = Workspace(root=tmp_path, slug="t")
    write(ws.content_context_autogenerated_path, {"narrative": "borrador"})
    write(ws.content_context_path, {"narrative": "curado"})

    assert _artifacts.content_context_path(ws) == ws.content_context_path
    assert _artifacts.load_content_context(ws).narrative == "curado"


def test_draft_is_used_when_there_is_no_curated_file(tmp_path):
    ws = Workspace(root=tmp_path, slug="t")
    write(ws.content_context_autogenerated_path, {"narrative": "borrador"})

    assert _artifacts.content_context_path(ws) == ws.content_context_autogenerated_path
    assert _artifacts.load_content_context(ws).narrative == "borrador"


def test_no_context_at_all_loads_as_empty_rather_than_raising(tmp_path):
    ws = Workspace(root=tmp_path, slug="t")

    assert _artifacts.content_context_path(ws) is None
    assert not _artifacts.load_content_context(ws)
