"""Knowledge-graph extraction: corpus → the curated draft at `kg_autogenerated_path`.

`KnowledgeGraphBuilder` is the whole public surface, and it is a facade over three phase
modules that hand each other plain dicts in memory:

    extraction.run(corpus) → staging
    cleaning.run(staging)  → cleaned
    curation.run(cleaned)  → curated: the artifact, and its cached derivations

A build writes exactly one ARTIFACT, at `kg_autogenerated_path`, plus one derivation in
`cache/`: the corpus anchoring at `concept_sources_path`. There are no intermediate files —
a build is ~15 min and repeating it is cheaper than the machinery of checkpointing it.

The three phases stay separately callable, but on DATA and not on a path — `clean(staging)`,
`curate(cleaned)` — which is also what lets each be exercised with recorded model answers
instead of a GPU.
"""

from pathlib import Path

from loguru import logger

from ... import config
from ... import prompts as prompts_pkg
from ...core import progress
from ...core.inference import ensure_models
from ...core.workspace import Workspace
from ...instance import locale
from ...instance.relations import RelationSchema
from .. import _context, _source_docs
from . import blocks, cleaning, curation, extraction, parsing, schemas

__all__ = [
    "BUILD_PHASES",
    "KnowledgeGraphBuilder",
    "blocks",
    "build_models",
    "cleaning",
    "curation",
    "extraction",
    "parsing",
    "schemas",
]

# Shares of a whole build, from a timed run: extraction was guessed at 48 % for being the
# only per-chunk phase and measured 8 %, while the handful of calls that reason over the
# whole inventory — merging, linking — are where the hour goes. Extraction's 16 is that 8
# doubled, for the gleaning pass reading each chunk a second time. Typing the relations and
# writing the context are one call each and carry a weight only so the bar does not jump.
#
# `convert`'s 40 IS AN ESTIMATE and the only number here that is not measured: the phase is
# one model call per page of the corpus plus a short one per seam, which sits above a single
# extraction pass and below the whole-inventory reasoning after it. On later builds it flies
# past, because the page cache answers instead of the model.
BUILD_PHASES = (
    ("convert", "Transcribiendo los documentos del corpus", 40),
    ("extract", "Extrayendo conceptos y relaciones", 16),
    ("clean", "Fusionando duplicados y normalizando nombres", 25),
    ("domains", "Agrupando los conceptos en dominios", 9),
    ("link", "Enlazando conceptos y ordenando el temario", 26),
    ("curate", "Tipando las relaciones y rompiendo ciclos", 1),
    ("context", "Poniendo por escrito de qué asignatura es esto", 1), # Last because it needs the names of the blocks, which no earlier phase has yet.
)

def build_models() -> list[str]:
    """Every model a graph build calls, so they can be checked before the first phase."""
    return [
        config.TRANSCRIBE_MODEL,
        config.TRANSCRIBE_SEAM_MODEL,
        config.KG_EXTRACT_MODEL,
        config.EMBEDDING_LLM,
        config.KG_CLEAN_MERGE_MODEL,
        config.KG_CLEAN_DROP_MODEL,
        config.KG_UNITS_MODEL,
        config.KG_DOMAINS_MODEL,
        config.KG_DOMAINS_LEFTOVERS_MODEL,
        config.KG_LINK_DOMAIN_MODEL,
        config.KG_LINK_CROSS_DOMAIN_MODEL,
        config.KG_CONTEXT_MODEL,
        config.REPAIR_LLM,
    ]


class KnowledgeGraphBuilder:
    """The three extraction phases, wired to one workspace's paths, prompts and schema."""

    def __init__(
        self,
        workspace: Workspace,
        schema: RelationSchema | None = None,
        verbose: bool = True,
    ):
        """Resolve the workspace's prompt set, its relation vocabulary and the converter."""
        self.workspace = workspace
        # Both resolved from the same place, because they have to agree: the catalogue the
        # prompts interpolate is prose written in the schema's language, and its slot names
        # are the two words the prompts' own text uses.
        self.prompts = prompts_pkg.of(locale.prompt_language(workspace))
        self.schema = schema or locale.relation_schema(workspace)
        self.max_repair_attempts = config.MAX_JSON_REPAIR_TRIES
        self.chunk_size = config.KG_BUILDER_CHUNK_SIZE

        logger.enable(__name__) if verbose else logger.disable(__name__)

        # Only `.docx` ever reaches it: a PDF goes through the page-transcription route and
        # plain text needs no conversion, so on the usual corpus Docling is never built.
        self.converter = _source_docs.LazyConverter(table_structure=False)

    # PUBLIC API ----------------------------------------------------------------------------------

    def bootstrap(self) -> None:
        """Check every model of the build is installed, so a failure comes at second zero."""
        ensure_models(build_models(), "knowledge graph")

    def build(self, input_dir: str | Path) -> dict:
        """Run the whole build over a corpus directory and return the curated draft."""
        self.bootstrap()

        staging = self.extract(input_dir)
        if not staging:
            raise RuntimeError(f"No knowledge graph could be extracted from: {input_dir}")

        progress.checkpoint()
        cleaned = self.clean(staging)

        progress.checkpoint()
        graph = self.curate(cleaned)

        # After `curate` and not inside it: `curate(cleaned)` is separately callable and
        # promises to be a transform from data to data, while this writes a second file.
        progress.checkpoint()
        self.synthesize_context(graph)
        return graph

    def synthesize_context(self, graph: dict) -> None:
        """Write the subject-context draft from what the graph alone knows about the subject.

        The names of the blocks the syllabus is divided into, and how big it is — NOT the
        concepts themselves: the prompt forbids enumerating them, and the graph is right
        there for whoever wants the list.
        """
        progress.phase("context")
        domains = list(graph.get("concepts_by_domains") or {})
        if not domains:
            return
        total = sum(len(members) for members in graph["concepts_by_domains"].values())
        evidence = "\n".join(
            [
                (f"El temario se divide en {len(domains)} bloque(s), con {total} concepto(s) en total. Se llaman:"),
                *(f"- {domain}" for domain in domains),
            ]
        )
        _context.synthesize(
            self.workspace,
            evidence,
            "EL GRAFO DEL TEMARIO",
            config.KG_CONTEXT_MODEL,
            think=config.THINK_KG_CONTEXT,
        )
        progress.advance(1.0)

    def extract(self, input_dir: str | Path, recursive: bool = False) -> dict:
        """Phase 1: the corpus as a raw inventory of concepts and relation triples."""
        return extraction.run(
            input_dir,
            converter=self.converter,
            schema=self.schema,
            chunk_size=self.chunk_size,
            cache_dir=self.workspace.markdown_cache_dir,
            max_attempts=self.max_repair_attempts,
            prompts=self.prompts,
            recursive=recursive,
        )

    def clean(self, staging: dict) -> dict:
        """Phase 2: the same inventory, deduplicated and denoised. Nothing reaches disk."""
        return cleaning.run(
            staging,
            schema=self.schema,
            max_attempts=self.max_repair_attempts,
            prompts=self.prompts,
        )

    def curate(
        self,
        cleaned: dict,
        output_path: str | Path | None = None,
        sources_path: str | Path | None = None,
    ) -> dict:
        """Phase 3: domains, the syllabus order, and the one artifact a build writes."""
        return curation.run(
            cleaned,
            output_path or self.workspace.kg_autogenerated_path,
            sources_path or self.workspace.concept_sources_path,
            schema=self.schema,
            max_attempts=self.max_repair_attempts,
            prompts=self.prompts,
        )
