"""What each job kind actually does. One place, so the runner stays generic.

Every handler resolves its paths from `job.workspace` and nothing else: the runner is one
queue for the whole installation, so a handler reading a process-wide workspace would write
one person's build into another's directory.
"""

from loguru import logger

from variatio import config, prompts, stages
from variatio.concept_tagger import ConceptTagger
from variatio.core import progress
from variatio.core.workspace import Workspace
from variatio.instance import locale
from variatio.instance.exemplars_profile import ExemplarsProfile
from variatio.instance.knowledge_graph import KnowledgeGraph

from .. import curriculum as curriculum_store
from .. import deps, review, settings, storage
from ..db import generations, mirror, repository, session_scope
from ..editors import kg_edit
from .build_process import run_build
from .models import Job
from .runner import JobControl


_EFFORT_LEVELS = ("low", "medium", "high", "max")


def _workspace(job: Job) -> Workspace:
    """Resolve the workspace a job names, which is the only one it may touch."""
    return settings.workspace_for(job.workspace)


def _build(artifact: str):
    """Make the handler that builds one artifact out of process and files the result."""

    def handler(job: Job, control: JobControl) -> dict:
        """Build the artifact, mirror what came out, and drop the stale in-memory context."""
        ws = _workspace(job)
        working = review.working_path(ws, artifact)
        if working is not None:
            # The one artifact a build replaces in place: snapshot it before, because the
            # process that replaces it is another one and cannot reach the history.
            storage.backup(ws, review.canonical_path(ws, artifact), artifact)
        try:
            result = run_build(artifact, control)
        except BaseException:
            # A cancel kills the worker five seconds after asking it to stop, so what it
            # had half written is normally left for this process to remove.
            if working is not None:
                working.unlink(missing_ok=True)
            raise
        review.retire_curated(ws, artifact)
        mirror.mirror_file(
            ws, review.autogenerated_path(ws, artifact) or review.canonical_path(ws, artifact)
        )
        # The build ran in another process, so this one's context still speaks of the
        # previous artifact: without the drop, whatever follows — tagging, indexing,
        # generating, the chain — would reuse the graph or bank just replaced.
        deps.invalidate(job.workspace, f"'{artifact}' reconstruido")
        return result

    return handler


def context_for(job: Job, reload: bool = False):
    """Return the workspace's pipeline context, warming the indices if they are cold.

    Warming embeds every concept description and the whole bank — minutes of silence the
    first time — so it gets a step of its own that says what it costs.
    """
    ws = _workspace(job)
    if deps.is_ready(ws.slug) and not reload:
        logger.info("Índices ya calientes en memoria; se reutilizan")
        return deps.get_context(ws)

    label = (
        "Reconstruyendo el contexto: instancia + índices"
        if reload
        else "Preparando el contexto: cargando la instancia e indexando"
    )
    with progress.step("context", label):
        logger.info(f"Cargando la instancia e indexando con '{config.EMBEDDING_LLM}'")
        context = deps.reload_context(ws) if reload else deps.get_context(ws)
    logger.success(
        f"Contexto listo: {len(context.embedder.concepts_index)} concepto(s) indexado(s), "
        f"{len(context.exemplars_bank)} ítem(s) del banco"
    )
    return context


_SLOTS = ("corpus", "exemplars")


def handle_transcribe(job: Job, control: JobControl) -> dict:
    """Transcribe one raw slot into the markdown cache the three builders read.

    An accelerator and never a gate: nothing is chained after it and nothing waits for it —
    a build finding no cache transcribes on its own, exactly as it would have.
    """
    deps.require_inference()
    ws = _workspace(job)
    slot = job.params.get("slot") or ""
    if slot not in _SLOTS:
        raise ValueError(f"Ranura desconocida: '{slot}'; esperaba una de {list(_SLOTS)}")

    from variatio.stages import transcribe_slot

    logger.info(f"Transcribiendo los documentos de «{slot}» en «{ws.slug}»")
    return transcribe_slot(ws, slot)


def handle_describe_concepts(job: Job, control: JobControl) -> dict:
    """Write the concept descriptions the index is built on, all of them or a selection."""
    deps.require_inference()
    ws = _workspace(job)
    concepts = job.params.get("concepts")
    overwrite = bool(job.params.get("overwrite"))
    logger.info(
        f"Escribiendo descripciones con '{config.DESCRIPTION_GENERATION_LLM}': "
        + (
            f"{len(concepts)} concepto(s) seleccionado(s)"
            if concepts
            else "todos los conceptos etiquetables"
        )
        + (", reescribiendo las existentes" if overwrite else ", solo las que faltan")
    )
    descriptions = stages.describe_concepts(concepts=concepts, overwrite=overwrite, ws=ws)
    # New prose means new embeddings; the cached context would keep matching the old.
    deps.invalidate(ws.slug, "descripciones de conceptos regeneradas")
    return {"described": len(descriptions)}


def handle_index(job: Job, control: JobControl) -> dict:
    """Rebuild the concepts and bank indices from scratch."""
    deps.require_inference()
    context = context_for(job, reload=True)
    return {
        "concepts": len(context.embedder.concepts_index),
        "items": len(context.exemplars_bank),
    }


def handle_tag(job: Job, control: JobControl) -> dict:
    """Tag bank items with graph concepts: the ids asked for, all of them, or the pending."""
    deps.require_inference()
    context = context_for(job)
    ids = job.params.get("ids") or None
    if job.params.get("all"):
        ids = list(context.exemplars_bank)
    pending = ids if ids is not None else ConceptTagger.pending_ids(context.exemplars_bank)
    logger.info(
        f"A etiquetar: {len(pending)} de {len(context.exemplars_bank)} ítem(s), "
        f"verificados con '{config.CONCEPT_TAGGER_LLM}'"
    )
    bank = stages.tag_bank(context, ids=ids)
    untagged = [i for i, item in bank.items() if not item.get("concepts")]
    logger.success(
        f"Banco etiquetado: {len(bank) - len(untagged)} con conceptos, {len(untagged)} sin ellos"
    )
    return {
        "items": len(bank),
        "tagged": len(bank) - len(untagged),
        "untagged": len(untagged),
    }


def handle_review_taggability(job: Job, control: JobControl) -> dict:
    """Decide which graph concepts work as labels, judged against the profile and the bank.

    Needs a built profile: a concept is useless as a label only relative to the shapes of
    item this instance sets, so the graph alone cannot answer it.
    """
    deps.require_inference()
    ws = _workspace(job)

    profile_path = stages.exemplars_profile_path(ws)
    if profile_path is None:
        raise ValueError(
            "La etiquetabilidad se decide contra el perfil de ejemplares, y esta "
            "asignatura no lo tiene todavía: constrúyelo antes."
        )

    graph_path = stages.knowledge_graph_path(ws)
    if graph_path is None:
        raise ValueError("No hay grafo de conocimiento que revisar.")

    from variatio import taggability

    profile = ExemplarsProfile(profile_path)
    graph = KnowledgeGraph(graph_path)
    bank = storage.read_json(ws.exemplars_bank_path) or {}

    with progress.overall(taggability.BUILD_PHASES):
        progress.phase("taggable")
        non_taggable = taggability.review(
            graph,
            profile,
            prompts.of(locale.prompt_language(ws)),
            bank,
            stages.load_content_context(ws),
        )

    result = kg_edit.set_non_taggable(ws, non_taggable)
    return {"non_taggable": result["non_taggable"], "concepts": len(graph.all_concepts)}


def _commission_detail(fixed, curriculum, instructions, think) -> list[str]:
    """Spell out the parts of a commission that are not the concepts, for the log line."""
    detail = []
    if fixed:
        detail.append("campos fijados " + ", ".join(f"{k}={v}" for k, v in fixed.items()))
    if curriculum:
        detail.append(f"currículo de {len(curriculum)} concepto(s)")
    if instructions:
        detail.append(f"instrucciones «{instructions}»")
    if isinstance(think, str):
        detail.append(f"con razonamiento ({think})")
    else:
        detail.append("con razonamiento" if think else "sin razonamiento")
    return detail


def handle_generate(job: Job, control: JobControl) -> dict:
    """Generate `n` items on commission, saving each one the moment it validates.

    The curriculum is resolved FIRST and what is stored is the one that ran, never the one
    that was asked for, so a saved variant is reproducible from its own row. `on_accepted`
    persists item by item, so a run cancelled after the third keeps three rows.
    """
    deps.require_inference()
    context = context_for(job)
    params = job.params
    # `or 1` was wrong on a falsy zero: «genera 0» produced one item and then recorded
    # `requested: 1`, falsifying the very thing the `generations` row exists to keep. An
    # absent `n` still means one; a zero travels as itself and the generator refuses it.
    n = 1 if params.get("n") is None else int(params["n"])
    concepts = params.get("concepts") or None
    item_type = params.get("item_type") or None
    fixed = params.get("fixed") or None
    curriculum = curriculum_store.resolve(
        context.workspace, context.knowledge_graph, params.get("curriculum")
    )
    instructions = params.get("instructions") or None
    # Absent means «as it always was»: a caller predating the switch reasons at the default
    # effort. A recognised level travels as itself; anything else collapses to a bool.
    raw_think = params.get("think", True)
    think = raw_think if raw_think in _EFFORT_LEVELS else bool(raw_think)
    # Resolved here rather than deeper down because three things need the same answer: the
    # log line, the row saved beside each item, and the call itself. An unoffered name
    # raises and the job fails with it said in one sentence — the submit route refused it
    # already, so getting here means the offered list changed under a queued job.
    model = stages.resolve_generation_model(params.get("model"))

    resolved_type = context.exemplars_profile.item_type(item_type)
    detail = _commission_detail(fixed, curriculum, instructions, think)
    logger.info(
        f"Generando {n} ítem(s) de tipo «{resolved_type.label}» con "
        f"'{model}' sobre "
        + (", ".join(concepts) if concepts else "los conceptos más frecuentes del banco")
        + " — "
        + "; ".join(detail)
    )

    avoid = _recent_scenarios(job, resolved_type, concepts)
    if avoid:
        logger.info(
            f"{len(avoid)} escenario(s) de variantes guardadas entran en el prompt para no repetirse"
        )

    saved_ids: dict[int, int] = {}

    def remember(result, index: int) -> None:
        """Persist one accepted item and tell the screen which row it became."""
        row_id = _remember_one(job, result, resolved_type.key, curriculum, model)
        if row_id is None:
            return
        saved_ids[index] = row_id
        progress.emit("item.saved", index=index, id=row_id)

    results = stages.generate(
        context,
        concepts=concepts,
        item_type=resolved_type.key,
        n=n,
        fixed=fixed,
        curriculum=curriculum,
        instructions=instructions,
        think=think,
        model=model,
        avoid=avoid,
        on_accepted=remember,
    )
    if len(results) < n:
        logger.warning(f"{len(results)}/{n} ítem(s) validados; el resto no pasó el esquema")
    else:
        logger.success(f"{len(results)}/{n} ítem(s) generados y validados")

    items = [
        {
            "item": r.item.model_dump(mode="json"),
            "item_type": r.item_type,
            "thinking": r.thinking,
            "checks": r.checks,
            "retried": r.retried,
            "saved_id": saved_ids.get(i + 1),
        }
        for i, r in enumerate(results)
    ]
    return {
        "requested": n,
        "produced": len(results),
        "item_type": resolved_type.key,
        "model": model,
        "saved": len(saved_ids),
        "items": items,
    }


def _recent_scenarios(job: Job, item_type, concepts: list[str] | None) -> list[str]:
    """Read the statements of this account's last saved variants, so the prompt can avoid them.

    Its OWN, never the instance's: a generated exercise is private to whoever asked for it,
    and reading a colleague's statement into somebody's prompt is that same reading through
    another door. A reminder and nothing more, so an unreadable database costs the run
    nothing but this.
    """
    limit = int(config.GENERATION_AVOID_RECENT)
    if limit < 1:
        return []
    try:
        with session_scope() as session:
            workspace = repository.get_workspace(session, job.workspace)
            if workspace is None:
                return []
            items = generations.recent_items(
                session,
                workspace.id,
                item_type=item_type.key,
                concepts=concepts,
                limit=limit,
                author=job.user_id,
            )
    except Exception as exc:  # noqa: BLE001 - the run matters more than the reminder
        logger.warning(f"No se pudieron leer las variantes guardadas recientes: {exc}")
        return []

    texts: list[str] = []
    for item in items:
        try:
            text = item_type.primary_text(item).strip()
        except (ValueError, AttributeError):
            continue
        if text:
            texts.append(text)
    return texts


def _remember_one(
    job: Job, result, item_type: str, curriculum: list[str] | None, model: str
) -> int | None:
    """Save one validated item with its commission, and return its row id or `None`.

    Its own short session, so a run cancelled after the third item keeps three rows.
    Best-effort on purpose: a database briefly away must not turn a minute of GPU into a
    failed job — the item is already in the event stream and on screen, and only the record
    is lost.
    """
    params = job.params
    try:
        with session_scope() as session:
            workspace = repository.get_workspace(session, job.workspace)
            if workspace is None:
                return None
            row = generations.save_generation(
                session,
                workspace_id=workspace.id,
                user_id=job.user_id,
                job_id=job.id,
                item_type=result.item_type or item_type,
                item=result.item.model_dump(mode="json"),
                concepts=params.get("concepts") or [],
                curriculum=curriculum or [],
                fixed=params.get("fixed") or {},
                instructions=params.get("instructions"),
                think=bool(params.get("think", True)),
                model=model,
                thinking=result.thinking,
                checks=result.checks,
            )
            return row.id
    except Exception as exc:  # noqa: BLE001 - the item is on screen; only its record is lost
        logger.warning(f"No se pudo guardar la variante en la base de datos: {exc}")
        return None


HANDLERS = {
    "build_profile": _build(review.EXEMPLARS_PROFILE),
    "build_kg": _build(review.KNOWLEDGE_GRAPH),
    "build_bank": _build(review.EXEMPLARS_BANK),
    "transcribe": handle_transcribe,
    "describe_concepts": handle_describe_concepts,
    "index": handle_index,
    "tag": handle_tag,
    "review_taggability": handle_review_taggability,
    "generate": handle_generate,
}
