"""Reading and editing the subject's context.

Not a stage, so not in `review.ARTIFACTS`: it has no `raw/` slot and no build of its own.
The two builders synthesise it as the last thing they do, each from what its own artifact
knows about the subject, and each writes the DRAFT. What is edited here is the CURATED
file, which is what wins on read -- that pair is what stops a rebuild from paraphrasing
somebody's words one more time.
"""

from variatio.core.workspace import Workspace
from variatio.instance.content_context import ContentContext

from .. import storage


def load(ws: Workspace) -> dict:
    curated = ws.content_context_path
    draft = ws.content_context_autogenerated_path
    has_curated = curated.is_file()
    has_draft = draft.is_file()
    context = ContentContext.load(curated if has_curated else draft if has_draft else None)

    return {
        "exists": has_curated or has_draft,
        "narrative": context.narrative,
        "facts": dict(context.facts),
        "block": context.prompt_block(),
        "source": "curated" if has_curated else "draft" if has_draft else None,
        "path": str(curated if has_curated else draft) if (has_curated or has_draft) else None,
        # A build always writes the draft, so once the context is curated a newer synthesis
        # sits there unread. Saying so is the whole point of keeping both: otherwise a
        # rebuild would look like it did nothing to the context.
        "pending_draft": (
            ContentContext.load(draft).narrative if has_curated and has_draft else None
        ),
    }


def save(ws: Workspace, narrative: str, facts: dict[str, str]) -> dict:
    context = ContentContext({"narrative": narrative, **facts})
    # Through `storage`, not `ContentContext.save`, so the edit gets a history snapshot
    # like every other artifact edit does.
    storage.write_json(ws.content_context_path, context.as_dict())
    return load(ws)


# Promoting the draft is a save of the draft's own text: from here on it is the curated
# file, and the next build writes a new draft beside it rather than over it.
def adopt_draft(ws: Workspace) -> dict:
    draft = ContentContext.load(ws.content_context_autogenerated_path)
    if not draft:
        raise ValueError("No hay ningún borrador de contexto que adoptar.")
    return save(ws, draft.narrative, dict(draft.facts))
