"""Editing the content profile.

Validation is delegated to `ContentProfile` itself — the class that will have to load
the file at runtime is the only honest judge of whether an edit is valid, and the user
gets the exact error the pipeline would raise.
"""

from variant_generator.content_profile import ContentProfile

from .. import deps, review, storage

ARTIFACT = review.CONTENT_PROFILE


def load() -> dict:
    path = review.current_path(ARTIFACT)
    if path is None:
        return {"exists": False, "profile": None, "path": None}
    return {
        "exists": True,
        "profile": storage.read_json(path),
        "path": str(path),
        "is_autogenerated": str(path) != str(review.canonical_path(ARTIFACT)),
    }


def validate(raw: dict) -> str | None:
    try:
        ContentProfile.validate_raw(raw)
    except (ValueError, KeyError, TypeError) as exc:
        return f"{type(exc).__name__}: {exc}"
    return None


def save(raw: dict) -> dict:
    error = validate(raw)
    if error:
        raise ValueError(error)

    # An edited draft becomes the curated artifact: that is what reviewing it means.
    target = review.canonical_path(ARTIFACT)
    storage.write_json(target, raw, artifact=ARTIFACT)
    review.ReviewState().invalidate(ARTIFACT)
    deps.invalidate("perfil de contenido editado")
    return {"path": str(target), "hash": storage.sha256_of(target)}
