"""Editing the exemplars profile.

Validation is delegated to `ExemplarsProfile` itself — the class that will have to load
the file at runtime is the only honest judge of whether an edit is valid, and the user
gets the exact error the pipeline would raise.
"""

from variant_generator.core.workspace import Workspace
from variant_generator.instance.exemplars_profile import ExemplarsProfile

from .. import deps, review, storage

ARTIFACT = review.EXEMPLARS_PROFILE


def load(ws: Workspace) -> dict:
    path = review.current_path(ws, ARTIFACT)
    if path is None:
        return {"exists": False, "profile": None, "path": None}
    return {
        "exists": True,
        "profile": storage.read_json(path),
        "path": str(path),
        "is_autogenerated": str(path) != str(review.canonical_path(ws, ARTIFACT)),
    }


def validate(raw: dict) -> str | None:
    try:
        ExemplarsProfile.validate_raw(raw)
    except (ValueError, KeyError, TypeError) as exc:
        return f"{type(exc).__name__}: {exc}"
    return None


def save(ws: Workspace, raw: dict) -> dict:
    error = validate(raw)
    if error:
        raise ValueError(error)

    # An edited draft becomes the curated artifact: that is what reviewing it means.
    target = review.canonical_path(ws, ARTIFACT)
    storage.write_json(target, raw, ws=ws, artifact=ARTIFACT)
    review.ReviewState(ws).invalidate(ARTIFACT)
    deps.invalidate(ws.slug, "perfil de ejemplares editado")
    return {"path": str(target), "hash": storage.sha256_of(target)}
