"""What subject an instance is about, as prose plus three named facts.

Every prompt in the system interpolates `prompt_block()` to fix the materia, the level, the
language and the conventions of whatever it writes. It is an artifact with no builder of
its own: the graph and profile builders each synthesise it from what they know.
"""

import json
from pathlib import Path

from ..core.json_io import write_json
from ..core.workspace import Workspace

CANONICAL_KEYS = ("subject", "educational_level", "language_of_instruction")

NARRATIVE_KEY = "narrative"


class ContentContext:
    """The subject's narrative and its addressable facts."""

    def __init__(self, raw: dict | None = None):
        """Split a stored context into its narrative and the scalar facts beside it."""
        raw = dict(raw or {})
        self.narrative: str = str(raw.pop(NARRATIVE_KEY, "") or "").strip()
        self.facts: dict[str, str] = {
            key: str(value).strip()
            for key, value in raw.items()
            if isinstance(value, (str, int, float)) and str(value).strip()
        }

    @classmethod
    def load(cls, path: str | Path | None) -> "ContentContext":
        """Read a context from disk; an absent or unreadable file yields an empty one."""
        if path is None:
            return cls()
        path = Path(path)
        if not path.is_file():
            return cls()
        try:
            with path.open(encoding="utf-8") as f:
                return cls(json.load(f))
        except (json.JSONDecodeError, OSError):
            return cls()

    @classmethod
    def from_legacy(cls, flat: dict) -> "ContentContext":
        """Adopt the flat map a pre-artifact profile carried under `content_context`.

        Lossless and free: every key stays a fact, so a workspace that has not been through
        a build reads exactly as it did before.
        """
        return cls(flat)

    def save(self, path: str | Path) -> None:
        """Write the context to disk."""
        write_json(path, self.as_dict())

    def as_dict(self) -> dict:
        """Return the stored form: the narrative, if any, followed by the facts."""
        data: dict[str, str] = {}
        if self.narrative:
            data[NARRATIVE_KEY] = self.narrative
        data.update(self.facts)
        return data

    @property
    def subject(self) -> str:
        """The materia. Addressable by name because the naive arm composes a sentence."""
        return self.facts.get("subject", "")

    @property
    def educational_level(self) -> str:
        """The level. Addressable for the same reason as `subject`."""
        return self.facts.get("educational_level", "")

    @property
    def language_of_instruction(self) -> str:
        """The language the generated material is written in."""
        return self.facts.get("language_of_instruction", "")

    def prompt_block(self) -> str:
        """Render the context for a prompt — the only renderer of it in the project.

        The `- key: value` listing is the fallback and is byte-identical to the five copies
        it replaced, so a workspace whose context has not been synthesised reads as before.
        """
        if self.narrative:
            return self.narrative
        return "\n".join(f"- {key}: {value}" for key, value in self.facts.items())

    def __bool__(self) -> bool:
        """Return whether anything about the subject is declared at all."""
        return bool(self.narrative or self.facts)


def resolve_path(ws: Workspace) -> Path | None:
    """Return the curated context if there is one, else the draft, else None.

    It lives here rather than in `stages/_artifacts` — which re-exports it — because the
    builders synthesise the context and a builder may not import a stage.
    """
    if ws.content_context_path.is_file():
        return ws.content_context_path
    if ws.content_context_autogenerated_path.is_file():
        return ws.content_context_autogenerated_path
    return None


def load_for(ws: Workspace) -> ContentContext:
    """Load a workspace's context, curated over draft."""
    return ContentContext.load(resolve_path(ws))
