import os
from pathlib import Path

from .relations import BUILTIN_SCHEMAS

# File Paths & Cache ----------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
INSTANCE_DIR = PROJECT_ROOT / "instance"
CACHE_DIR = PROJECT_ROOT / "cache"
RAW_BASE_DATA_DIR = PROJECT_ROOT / "raw_data_1"

RAW_EXEMPLARS_BANK_DIR = RAW_BASE_DATA_DIR / "raw_exemplars_bank"
RAW_CORPUS_DIR = RAW_BASE_DATA_DIR / "raw_corpus"

KG_PATH = INSTANCE_DIR / "knowledge_graph.json"
KG_AUTOGENERATED_PATH = INSTANCE_DIR / "knowledge_graph_autogenerated.json"
EXEMPLARS_BANK_PATH = INSTANCE_DIR / "exemplars_bank.json"
CONTENT_PROFILE_PATH = INSTANCE_DIR / "content_profile.json"
CONTENT_PROFILE_AUTOGENERATED_PATH = INSTANCE_DIR / "content_profile_autogenerated.json"

MARKDOWN_CACHE_DIR = CACHE_DIR / "markdown"
CONCEPT_DESCRIPTIONS_PATH = CACHE_DIR / "concept_descriptions.json"
CONCEPTS_EMBEDDINGS_PATH = CACHE_DIR / "embeddings" / "concepts_embeddings.npz"
EXEMPLARS_BANK_EMBEDDINGS_PATH = CACHE_DIR / "embeddings" / "exemplars_bank_embeddings.npz"


# Inference ----------------------------------------------
INFERENCE_ENGINE = "ollama"

_OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "localhost:13434")
OLLAMA_HOST = (
    _OLLAMA_HOST if _OLLAMA_HOST.startswith(("http://", "https://")) else f"http://{_OLLAMA_HOST}"
)


# CP = Content Profile
# EB = Exemplars Bank
# KG = Knowledge Graph

# Models ----------------------------------------------

# Content profile builder
CP_INFER_MODEL = "qwen3.6:35b-a3b-q8_0"

# Exemplars bank builder
EB_EXTRACT_MODEL = "qwen3.6:35b-a3b-q8_0"

# Knowledge graph builder
KG_EXTRACT_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_CLEAN_EMBEDDING_MODEL = "qwen3-embedding:4b"
KG_CLEAN_MERGE_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_CLEAN_DROP_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_DOMAINS_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_DOMAINS_LEFTOVERS_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_LINK_DOMAIN_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_LINK_CROSS_DOMAIN_MODEL = "qwen3.6:35b-a3b-q8_0"
KG_TAGGABLE_MODEL = "qwen3.6:35b-a3b-q8_0"

# Runtime pipeline
EMBEDDING_LLM = "qwen3-embedding:4b"
DESCRIPTION_GENERATION_LLM = "qwen3.6:35b-a3b-q8_0"
CONCEPT_TAGGER_LLM = "qwen3.6:35b-a3b-q8_0"
CONTENT_GENERATION_LLM = "gemma4:31b-it-q4_K_M"

REPAIR_LLM = "qwen3.6:35b-a3b-q8_0"

EMBEDDING_MODELS = (EMBEDDING_LLM, KG_CLEAN_EMBEDDING_MODEL)


# Builders ----------------------------------------------
CP_SCHEMA_INFERENCE_BUDGET = 32_000
EB_CHUNK_SIZE = 12_000

KG_BUILDER_CHUNK_SIZE = 12_000
KG_MAX_EVIDENCE_RELATIONS = 6
KG_BUILDER_PLURAL_SUFFIXES = ("s",)
KG_BUILDER_MERGE_QUALIFIER_PATTERN = r"\s+en (python|java)\b"
KG_BUILDER_UNCLASSIFIED_DOMAIN = "Sin clasificar"

KG_RELATION_SCHEMA = "es"
RELATION_SCHEMA = BUILTIN_SCHEMAS[KG_RELATION_SCHEMA]
KG_PREREQUISITE_RELATION = RELATION_SCHEMA.prerequisite_verbose


# Embedding & Retrieval ----------------------------------------------
EMBEDDING_QUERY_PREFIX = "Instruct: Dado el enunciado de un ejercicio, recupera la descripción del concepto del currículo que el ejercicio hace practicar al alumno, no la de los que solo usa como herramienta\nQuery: "

EMBEDDING_DOCUMENT_PREFIX = ""
EMBEDDING_BATCH_SIZE = 16

EMBEDDER_SIMILARITY_THRESHOLD = 0.40
EMBEDDER_DESCRIPTION_WEIGHT = 0.5

DESCRIPTION_SIBLINGS_TOP_K = 8
DESCRIPTION_COLLISION_SIMILARITY = 0.85


# Tagging & Generation ----------------------------------------------
KG_BUILDER_MERGE_SIMILARITY = 0.80
KG_BUILDER_MAX_MERGE_GROUP = 8
KG_BUILDER_MERGE_GROUPS_PER_CALL = 10
KG_BUILDER_CLEAN_BATCH_SIZE = 60
KG_BUILDER_DOMAIN_BATCH_SIZE = 20
KG_BUILDER_DOMAIN_ROUNDS = 3

TAGGER_TOP_K_CANDIDATES = 10
TAGGER_FALLBACK_TOP_K = 30
MAX_FEW_SHOT_EXAMPLES = 4
MAX_JSON_REPAIR_TRIES = 3


# Logging ----------------------------------------------
NOISY_LOGGERS = ("docling", "docling_core", "docling_ibm_models", "PIL")
NOISY_WARNING_MODULES = (r"docling.*", r"PIL.*")
