from dataclasses import dataclass
from pathlib import Path

INSTANCE_DIRNAME = "instance"
CACHE_DIRNAME = "cache"
RAW_DIRNAME = "raw"

DEFAULT_SLUG = "default"


# `raw_dirname` was a constructor field until 2026-08-17, and it existed for exactly one
# value: the raw directory of the repo's old single-user layout. With `default` moved into
# `workspaces/`, every instance names that directory `raw`, so what looked like
# configurability is one more way for two workspaces to disagree about where a corpus lives.
@dataclass(frozen=True)
class Workspace:
    root: Path
    slug: str = DEFAULT_SLUG

    def __post_init__(self) -> None:
        object.__setattr__(self, "root", Path(self.root).resolve())

    # DIRECTORIES -------------------------------------------------------------------------

    @property
    def instance_dir(self) -> Path:
        return self.root / INSTANCE_DIRNAME

    @property
    def cache_dir(self) -> Path:
        return self.root / CACHE_DIRNAME

    @property
    def raw_dir(self) -> Path:
        return self.root / RAW_DIRNAME

    @property
    def raw_corpus_dir(self) -> Path:
        return self.raw_dir / "raw_corpus"

    @property
    def raw_exemplars_dir(self) -> Path:
        return self.raw_dir / "raw_exemplars_bank"

    # INSTANCE ARTIFACTS ------------------------------------------------------------------

    @property
    def kg_path(self) -> Path:
        return self.instance_dir / "knowledge_graph.json"

    @property
    def kg_autogenerated_path(self) -> Path:
        return self.instance_dir / "knowledge_graph_autogenerated.json"

    @property
    def exemplars_bank_path(self) -> Path:
        return self.instance_dir / "exemplars_bank.json"

    @property
    def exemplars_profile_path(self) -> Path:
        return self.instance_dir / "exemplars_profile.json"

    @property
    def exemplars_profile_autogenerated_path(self) -> Path:
        return self.instance_dir / "exemplars_profile_autogenerated.json"

    # REGENERABLE DERIVATIONS -------------------------------------------------------------

    @property
    def markdown_cache_dir(self) -> Path:
        return self.cache_dir / "markdown"

    @property
    def concept_descriptions_path(self) -> Path:
        return self.cache_dir / "concept_descriptions.json"

    # De qué trozo del corpus de teoría salió cada concepto. Es una derivación del corpus,
    # como el markdown de al lado, y no parte del artefacto: el grafo curado se edita a
    # mano y no debe engordar con cientos de KB de citas. Se reescribe entero en cada
    # construcción del grafo; sin él las descripciones se redactan solo con las relaciones,
    # que es como se redactaban antes.
    @property
    def concept_sources_path(self) -> Path:
        return self.cache_dir / "concept_sources.json"

    # How much each concept demands, and the observable threshold that proves it was reached.
    # It lives here and not in the artifact for the same reason as the descriptions and the
    # corpus anchoring: it is derived from the graph, regenerated by a build, and the curated
    # graph is hand-edited. It is also what keeps the graph depending on nothing: the tier is
    # computed from the graph's own structure and a model judgement, without reading the
    # profile or the bank.
    @property
    def concept_difficulty_path(self) -> Path:
        return self.cache_dir / "concept_difficulty.json"

    @property
    def concepts_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "concepts_embeddings.npz"

    @property
    def exemplars_bank_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "exemplars_bank_embeddings.npz"

    @property
    def eval_rag_bank_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "eval_rag_bank.npz"

    # HOST STATE --------------------------------------------------------------------------

    @property
    def history_dir(self) -> Path:
        return self.instance_dir / ".history"

    @property
    def runs_dir(self) -> Path:
        return self.instance_dir / ".runs"

    @property
    def review_state_path(self) -> Path:
        return self.instance_dir / ".review_state.json"

    @property
    def eval_sessions_dir(self) -> Path:
        return self.instance_dir / ".evaluations"
