from dataclasses import dataclass
from pathlib import Path

INSTANCE_DIRNAME = "instance"
CACHE_DIRNAME = "cache"
RAW_DIRNAME = "raw"

DEFAULT_SLUG = "default"


@dataclass(frozen=True)
class Workspace:
    root: Path
    slug: str = DEFAULT_SLUG
    raw_dirname: str = RAW_DIRNAME

    def __post_init__(self) -> None:
        object.__setattr__(self, "root", Path(self.root).resolve())

    # DIRECTORIES -------------------------------------------------------------------------

    @property
    def instance_dir(self) -> Path:
        return self.root / INSTANCE_DIRNAME

    @property
    def cache_dir(self) -> Path:
        return self.root / CACHE_DIRNAME

    @property
    def raw_dir(self) -> Path:
        return self.root / self.raw_dirname

    @property
    def raw_corpus_dir(self) -> Path:
        return self.raw_dir / "raw_corpus"

    @property
    def raw_exemplars_dir(self) -> Path:
        return self.raw_dir / "raw_exemplars_bank"

    # INSTANCE ARTIFACTS ------------------------------------------------------------------

    @property
    def kg_path(self) -> Path:
        return self.instance_dir / "knowledge_graph.json"

    @property
    def kg_autogenerated_path(self) -> Path:
        return self.instance_dir / "knowledge_graph_autogenerated.json"

    @property
    def exemplars_bank_path(self) -> Path:
        return self.instance_dir / "exemplars_bank.json"

    @property
    def exemplars_profile_path(self) -> Path:
        return self.instance_dir / "exemplars_profile.json"

    @property
    def exemplars_profile_autogenerated_path(self) -> Path:
        return self.instance_dir / "exemplars_profile_autogenerated.json"

    # REGENERABLE DERIVATIONS -------------------------------------------------------------

    @property
    def markdown_cache_dir(self) -> Path:
        return self.cache_dir / "markdown"

    @property
    def concept_descriptions_path(self) -> Path:
        return self.cache_dir / "concept_descriptions.json"

    @property
    def concepts_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "concepts_embeddings.npz"

    @property
    def exemplars_bank_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "exemplars_bank_embeddings.npz"

    @property
    def eval_rag_bank_embeddings_path(self) -> Path:
        return self.cache_dir / "embeddings" / "eval_rag_bank.npz"

    # HOST STATE --------------------------------------------------------------------------

    @property
    def history_dir(self) -> Path:
        return self.instance_dir / ".history"

    @property
    def runs_dir(self) -> Path:
        return self.instance_dir / ".runs"

    @property
    def review_state_path(self) -> Path:
        return self.instance_dir / ".review_state.json"

    @property
    def eval_sessions_dir(self) -> Path:
        return self.instance_dir / ".evaluations"
