"""The chain of artifacts and its approval gates.

Each artifact is built, reviewed and approved before the next one is unlocked. Approving
records the artifact's own hash AND the hash of everything it was derived from; if an
upstream later changes, the downstream is marked stale and the UI can offer to redo that
step. Nothing repairs itself behind the user's back.

The raw documents are an upstream too, and the one the builders read directly: a build
records what its slot held (`record_built`), and a stage whose slot no longer holds that
reads stale with the documents named, built or closed — the artifact was made from fewer,
or other, documents than the ones now on disk. The record is the build's and not the
approval's, because a document uploaded between the two would otherwise never be noticed.

Not a "review": it is the record of what has been APPROVED, which is why it is not named
after the construction questionnaire or the taggability pass. `.review_state.json` and
`Workspace.review_state_path` keep their names, being the operational truth on disk.
"""

import json
from collections.abc import Callable
from datetime import datetime
from operator import attrgetter
from pathlib import Path

from loguru import logger

from variatio import entrypoints
from variatio.builders.source_docs import SUPPORTED_EXTS
from variatio.core import json_io
from variatio.core.workspace import Workspace

from . import storage
from .db import mirror

EXEMPLARS_PROFILE = entrypoints.EXEMPLARS_PROFILE
KNOWLEDGE_GRAPH = entrypoints.KNOWLEDGE_GRAPH
EXEMPLARS_BANK = entrypoints.EXEMPLARS_BANK

# The chain as the screens draw it: the navbar and the panel's cards read this tuple, so it
# is the order a person works in. The profile leads because finishing the graph needs an
# APPROVED profile — `routers/jobs.NEEDS_APPROVED` gates the taggability review on it.
ARTIFACTS: tuple[str, ...] = (EXEMPLARS_PROFILE, KNOWLEDGE_GRAPH, EXEMPLARS_BANK)

# `UPSTREAM[KNOWLEDGE_GRAPH]` is `()` and must stay so: a graph build reads only the raw
# corpus, so a read path that makes its screen depend on the profile fails in exactly the
# state a new workspace starts in. The bank's two ARE forced — it needs the profile's schema
# to extract and the graph's concepts to tag.
UPSTREAM: dict[str, tuple[str, ...]] = {
    KNOWLEDGE_GRAPH: (),
    EXEMPLARS_PROFILE: (),
    EXEMPLARS_BANK: (EXEMPLARS_PROFILE, KNOWLEDGE_GRAPH),
}

# The raw slot each artifact is built from — the one table of it, which `raw_data.SLOTS`
# derives its `feeds` from. The graph reads the corpus; the profile and the bank both read
# the exemplars, which is why adding an exercise sheet stales two stages at once.
RAW_SOURCE: dict[str, str] = {
    EXEMPLARS_PROFILE: "exemplars",
    KNOWLEDGE_GRAPH: "corpus",
    EXEMPLARS_BANK: "exemplars",
}

_RAW_DIR: dict[str, Callable[[Workspace], Path]] = {
    "corpus": attrgetter("raw_corpus_dir"),
    "exemplars": attrgetter("raw_exemplars_dir"),
}

# How the fallback sentence names a slot: the client translates the cause by its `slot`
# key, so these only reach a bundle older than the API.
_RAW_WORDS = {"corpus": "los apuntes", "exemplars": "los ejercicios"}

# What a stage is CALLED, and it is display copy rather than an identifier: these strings
# reach a person inside sentences the server composes ("before generating you have to
# approve: …"), where the client has no key to translate by. They are the names the bar
# uses, so the
# one place the server names a stage says what every screen says.
LABELS = {
    EXEMPLARS_PROFILE: "Tipos de ejercicio",
    KNOWLEDGE_GRAPH: "El temario",
    EXEMPLARS_BANK: "Etiquetado",
}

STALE_ACTION = {
    (EXEMPLARS_BANK, EXEMPLARS_PROFILE): (
        "Los tipos de ejercicio cambiaron: estos se recogieron con los anteriores."
    ),
    (EXEMPLARS_BANK, KNOWLEDGE_GRAPH): (
        "El temario cambió: las etiquetas puestas apuntan a conceptos anteriores."
    ),
}


def canonical_path(ws: Workspace, artifact: str) -> Path:
    """Where an edit is written. Editing a draft promotes it to the curated file."""
    return {
        EXEMPLARS_PROFILE: ws.exemplars_profile_path,
        KNOWLEDGE_GRAPH: ws.kg_path,
        EXEMPLARS_BANK: ws.exemplars_bank_path,
    }[artifact]


def autogenerated_path(ws: Workspace, artifact: str) -> Path | None:
    """Where a build leaves its draft, for the two artifacts that have one."""
    return {
        EXEMPLARS_PROFILE: ws.exemplars_profile_autogenerated_path,
        KNOWLEDGE_GRAPH: ws.kg_autogenerated_path,
    }.get(artifact)


def working_path(ws: Workspace, artifact: str) -> Path | None:
    """Where a build keeps an artifact it has not finished, for the one that has such a file.

    Only the bank does: it is the artifact a build replaces in place, having no draft to
    land beside, so it is written aside and put in place whole. `None` for the other two.
    """
    return {EXEMPLARS_BANK: ws.exemplars_bank_building_path}.get(artifact)


def current_path(ws: Workspace, artifact: str) -> Path | None:
    """The file actually read for an artifact: the curated one, else its draft."""
    if artifact == EXEMPLARS_PROFILE:
        return entrypoints.exemplars_profile_path(ws)
    if artifact == KNOWLEDGE_GRAPH:
        return entrypoints.knowledge_graph_path(ws)
    path = ws.exemplars_bank_path
    return path if path.is_file() else None


# What stops making sense once the artifact is gone: regenerable derivations, never user
# data, deleted so the next build does not start on the cache of a graph that no longer
# exists. The evaluation's RAG index is NOT here — it derives from the raw documents and not
# from the bank, so emptying a stage leaves it alone.
DERIVED: dict[str, tuple[Callable[[Workspace], Path], ...]] = {
    KNOWLEDGE_GRAPH: (
        attrgetter("concept_descriptions_path"),
        attrgetter("concept_sources_path"),
        attrgetter("concepts_embeddings_path"),
    ),
    EXEMPLARS_PROFILE: (),
    EXEMPLARS_BANK: (attrgetter("exemplars_bank_embeddings_path"),),
}


def raw_directory(ws: Workspace, slot: str) -> Path:
    """Return the directory one raw slot writes into; `KeyError` for a slot nobody declared."""
    return _RAW_DIR[slot](ws)


def raw_documents(ws: Workspace, slot: str) -> dict[str, dict]:
    """Describe what a slot holds right now, by name: the size and the mtime of each document.

    That pair is the document's signature here rather than a content hash, and it is
    enough: nothing the API does rewrites a document in place — an upload lands under a
    free name and a deletion unlinks — so a document that changed is one with another
    size or another mtime, and a stat per file is what `/api/pipeline` can afford on every
    poll where hashing a slot of up to four gigabytes is not.
    """
    path = raw_directory(ws, slot)
    if not path.is_dir():
        return {}
    out: dict[str, dict] = {}
    for entry in sorted(path.iterdir(), key=lambda p: p.name.lower()):
        if not entry.is_file() or entry.suffix.lower() not in SUPPORTED_EXTS:
            continue
        stat = entry.stat()
        out[entry.name] = {"bytes": stat.st_size, "modified": stat.st_mtime_ns}
    return out


def record_built(ws: Workspace, artifact: str, documents: dict[str, dict]) -> None:
    """Write down which documents a build of `artifact` read, replacing any earlier record."""
    data = _read_built(ws)
    data[artifact] = {
        "slot": RAW_SOURCE[artifact],
        "documents": documents,
        "at": datetime.now().isoformat(timespec="seconds"),
    }
    json_io.write_json(ws.built_from_path, data)


def forget_built(ws: Workspace, artifact: str) -> None:
    """Drop an artifact's build record, for when the artifact itself is gone."""
    data = _read_built(ws)
    if artifact in data:
        del data[artifact]
        json_io.write_json(ws.built_from_path, data)


def built_from(ws: Workspace, artifact: str) -> dict | None:
    """Return what the last build of `artifact` read, or nothing for one never built here.

    A build the CLI ran, or an instance that arrived through `import-instance`, has no
    record: with nothing to compare against the stage cannot read stale for its documents,
    and does not.
    """
    record = _read_built(ws).get(artifact)
    return record if isinstance(record, dict) else None


def _read_built(ws: Workspace) -> dict:
    """Read the build records, treating a missing or corrupt file as none."""
    if not ws.built_from_path.is_file():
        return {}
    try:
        with ws.built_from_path.open(encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def raw_drift(ws: Workspace, artifact: str) -> dict | None:
    """Name the documents that changed in an artifact's slot since it was built, or nothing.

    The answer carries the slot and three sorted lists — `added`, `removed`, `changed` —
    and is `None` both when nothing moved and when there is no record to move from.
    """
    record = built_from(ws, artifact)
    if record is None:
        return None
    slot = record.get("slot") or RAW_SOURCE[artifact]
    then = record.get("documents") or {}
    now = raw_documents(ws, slot)
    added = sorted(name for name in now if name not in then)
    removed = sorted(name for name in then if name not in now)
    changed = sorted(name for name in now if name in then and now[name] != then[name])
    if not (added or removed or changed):
        return None
    return {"slot": slot, "added": added, "removed": removed, "changed": changed}


def _raw_cause(drift: dict) -> dict:
    """Shape a raw drift as a stale cause, with a Spanish sentence for a client without the key."""
    parts = []
    for key, word in (("added", "nuevo"), ("removed", "eliminado"), ("changed", "modificado")):
        names = drift[key]
        if names:
            n = len(names)
            parts.append(f"{n} {word}{'s' if n != 1 else ''} ({', '.join(names)})")
    return {
        "slot": drift["slot"],
        "label": _RAW_WORDS[drift["slot"]],
        "reason": (
            f"Desde que se construyó han cambiado {_RAW_WORDS[drift['slot']]}: "
            f"{'; '.join(parts)}."
        ),
        "added": drift["added"],
        "removed": drift["removed"],
        "changed": drift["changed"],
    }


def discard(ws: Workspace, artifact: str) -> dict:
    """Empty a stage: the artifact goes back to "missing" and can be rebuilt.

    It does NOT touch `.history/`, which is how a mistaken deletion is undone.
    """
    files = artifact_files(ws, artifact)
    derived = _derived_files(ws, artifact)
    for path in files + derived:
        path.unlink(missing_ok=True)
    # What a build was writing goes too, or the listing would keep reading a bank the
    # workspace no longer has.
    working = working_path(ws, artifact)
    if working is not None:
        working.unlink(missing_ok=True)
    forget_built(ws, artifact)
    Approvals(ws).reopen(artifact)
    return {
        "artifact": artifact,
        "removed": [str(path) for path in files],
        "derived": [str(path) for path in derived],
    }


def artifact_files(ws: Workspace, artifact: str) -> list[Path]:
    """The files that ARE the artifact: the curated one and, if there is one, its draft."""
    draft = autogenerated_path(ws, artifact)
    paths = [canonical_path(ws, artifact)] + ([draft] if draft else [])
    return [path for path in paths if path.is_file()]


def _derived_files(ws: Workspace, artifact: str) -> list[Path]:
    """The regenerable files an artifact leaves behind, each with its `.fingerprints` twin.

    The twin is collected by adjacency rather than named, so only the describer knows the
    convention.
    """
    paths: list[Path] = []
    for resolve in DERIVED[artifact]:
        path = resolve(ws)
        paths += [path, path.with_suffix(f".fingerprints{path.suffix}")]
    return [path for path in paths if path.is_file()]


def retire_curated(ws: Workspace, artifact: str) -> bool:
    """Send the curated file to the history so a fresh draft becomes the artifact."""
    draft = autogenerated_path(ws, artifact)
    curated = canonical_path(ws, artifact)
    if draft is None or not draft.is_file() or not curated.is_file():
        return False
    storage.backup(ws, curated, artifact)
    curated.unlink()
    Approvals(ws).reopen(artifact)
    logger.info(
        f"[revisión] «{LABELS[artifact]}» curado anterior retirado al historial; "
        "el borrador recién construido pasa a ser el artefacto"
    )
    return True


class Approvals:
    """One workspace's approvals, read from and written to its `.review_state.json`.

    Constructed where it is needed rather than kept as a singleton: it holds a path and a
    small JSON, so a shared one would only answer for whichever workspace was read last.
    """

    def __init__(self, ws: Workspace, path: Path | None = None):
        """Bind to a workspace and, optionally, to a state file other than its own."""
        self.ws = ws
        self.path = Path(path or ws.review_state_path)

    # PERSISTENCE ---------------------------------------------------------------------------

    def _load(self) -> dict:
        """Read the approvals, treating a missing or corrupt file as none."""
        if not self.path.is_file():
            return {}
        try:
            with self.path.open(encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}

    def _save(self, data: dict) -> None:
        """Write the approvals back."""
        json_io.write_json(self.path, data)

    # TRANSITIONS ---------------------------------------------------------------------------

    def approve(self, artifact: str) -> dict:
        """Record an artifact's own hash and its upstreams', so a later drift reads stale.

        Raises FileNotFoundError when there is nothing built to approve.
        """
        path = current_path(self.ws, artifact)
        digest = storage.sha256_of(path)
        if digest is None:
            raise FileNotFoundError(f"'{artifact}' does not exist yet")

        data = self._load()
        data[artifact] = {
            "status": "approved",
            "hash": digest,
            "upstream": {
                up: storage.sha256_of(current_path(self.ws, up)) for up in UPSTREAM[artifact]
            },
            "at": datetime.now().isoformat(timespec="seconds"),
        }
        self._save(data)
        mirror.mirror_approval(self.ws.slug, artifact, True, UPSTREAM[artifact])
        return data[artifact]

    def invalidate(self, artifact: str) -> None:
        """Called after an edit: the artifact goes back to draft, gates close behind it."""
        self.reopen(artifact)

    def reopen(self, artifact: str) -> None:
        """Withdraw an artifact's approval, closing the gates behind it."""
        data = self._load()
        data.pop(artifact, None)
        self._save(data)
        mirror.mirror_approval(self.ws.slug, artifact, False)

    # READ ----------------------------------------------------------------------------------

    def snapshot(self, building: set[str] | None = None) -> list[dict]:
        """Report the whole chain, each stage carrying what still blocks it."""
        states = {a: self.state(a, building) for a in ARTIFACTS}
        result = []
        for artifact in ARTIFACTS:
            state = states[artifact]
            blockers = [
                LABELS[up]
                for up in UPSTREAM[artifact]
                if states[up]["status"] != "approved"
            ]
            state["blocked_by"] = blockers
            state["blocked_reason"] = (
                f"Antes hay que dar por bueno: {', '.join(blockers)}." if blockers else None
            )
            result.append(state)
        return result

    def gate_open(self, artifact: str) -> bool:
        """True when everything this artifact depends on has been approved."""
        return all(self.state(up)["status"] == "approved" for up in UPSTREAM[artifact])

    def generation_unlocked(self) -> bool:
        """True when every artifact of the chain is approved."""
        return all(self.state(a)["status"] == "approved" for a in ARTIFACTS)

    def state(self, artifact: str, building: set[str] | None = None) -> dict:
        """Report one artifact's state as the screens draw it."""
        path = current_path(self.ws, artifact)
        digest = storage.sha256_of(path)
        record = self._load().get(artifact)

        status = _status(artifact, building or set(), digest, record)
        stale_because = self._stale_because(artifact, record) if status == "approved" else []
        # The documents are an upstream of a DRAFT too: a stage built from fewer documents
        # than its slot now holds is stale whether or not anybody closed it, and the way
        # out is the same — build it again, or close it as it is.
        if status in ("draft", "approved"):
            drift = raw_drift(self.ws, artifact)
            if drift is not None:
                stale_because.append(_raw_cause(drift))
        if stale_because:
            status = "stale"

        draft_path = autogenerated_path(self.ws, artifact)
        return {
            "artifact": artifact,
            "label": LABELS[artifact],
            "status": status,
            "hash": digest,
            "path": str(path) if path else None,
            "is_autogenerated": bool(path and draft_path and Path(path) == draft_path),
            "approved_at": record.get("at") if record else None,
            "stale_because": stale_because,
        }

    def _stale_because(self, artifact: str, record: dict) -> list[dict]:
        """Name every upstream ARTIFACT whose file no longer hashes to what the approval recorded.

        The raw documents are checked by `state` itself, off the build record rather than
        the approval's.
        """
        out: list[dict] = []
        for upstream in UPSTREAM[artifact]:
            recorded = (record.get("upstream") or {}).get(upstream)
            if recorded != storage.sha256_of(current_path(self.ws, upstream)):
                out.append(
                    {
                        "artifact": upstream,
                        "label": LABELS[upstream],
                        "reason": STALE_ACTION.get(
                            (artifact, upstream), f"{LABELS[upstream]} cambió."
                        ),
                    }
                )
        return out


def _status(artifact: str, building: set[str], digest: str | None, record: dict | None) -> str:
    """Read an artifact's state off its digest and its approval record.

    Staleness is not decided here: it needs the upstreams' digests and only applies to
    something already approved.
    """
    if artifact in building:
        return "building"
    if digest is None:
        return "missing"
    if record is None or record.get("status") != "approved":
        return "draft"
    if record.get("hash") != digest:
        return "draft"
    return "approved"
