"""The chain of artifacts and its approval gates.

Each artifact is built, reviewed and approved before the next one is unlocked.
Approving records the artifact's own hash *and* the hash of everything it was
derived from; if an upstream later changes, the downstream is marked stale and
the UI can offer to redo that step. Nothing repairs itself behind the user's back.
"""

import json
from datetime import datetime
from pathlib import Path

from variant_generator import stages
from variant_generator.workspace import Workspace

from . import storage

EXEMPLARS_PROFILE = stages.EXEMPLARS_PROFILE
KNOWLEDGE_GRAPH = stages.KNOWLEDGE_GRAPH
EXEMPLARS_BANK = stages.EXEMPLARS_BANK

ARTIFACTS: tuple[str, ...] = (KNOWLEDGE_GRAPH, EXEMPLARS_PROFILE, EXEMPLARS_BANK)

# Verified against the code, not assumed: the profile only reads the raw exemplars,
# the KG only reads the raw corpus, and the bank needs both (schema for extraction,
# concepts for tagging). The first two are independent of each other, so the order
# `ARTIFACTS` lists them in is a presentation choice — it is the navbar's — and only the
# bank coming last is forced.
UPSTREAM: dict[str, tuple[str, ...]] = {
    KNOWLEDGE_GRAPH: (),
    EXEMPLARS_PROFILE: (),
    EXEMPLARS_BANK: (EXEMPLARS_PROFILE, KNOWLEDGE_GRAPH),
}

LABELS = {
    EXEMPLARS_PROFILE: "Perfil de ejemplares",
    KNOWLEDGE_GRAPH: "Grafo de conocimiento",
    EXEMPLARS_BANK: "Banco de ejemplares",
}

STALE_ACTION = {
    (EXEMPLARS_BANK, EXEMPLARS_PROFILE): "El esquema cambió: los ítems se extrajeron con el anterior.",
    (EXEMPLARS_BANK, KNOWLEDGE_GRAPH): "El grafo cambió: las etiquetas apuntan a conceptos anteriores.",
}


def canonical_path(ws: Workspace, artifact: str) -> Path:
    """Where an edit is written. Editing a draft promotes it to the curated file."""
    return {
        EXEMPLARS_PROFILE: ws.exemplars_profile_path,
        KNOWLEDGE_GRAPH: ws.kg_path,
        EXEMPLARS_BANK: ws.exemplars_bank_path,
    }[artifact]


def autogenerated_path(ws: Workspace, artifact: str) -> Path | None:
    return {
        EXEMPLARS_PROFILE: ws.exemplars_profile_autogenerated_path,
        KNOWLEDGE_GRAPH: ws.kg_autogenerated_path,
    }.get(artifact)


def current_path(ws: Workspace, artifact: str) -> Path | None:
    if artifact == EXEMPLARS_PROFILE:
        return stages.exemplars_profile_path(ws)
    if artifact == KNOWLEDGE_GRAPH:
        return stages.knowledge_graph_path(ws)
    path = ws.exemplars_bank_path
    return path if path.is_file() else None


# Lo que deja de tener sentido en cuanto el artefacto desaparece. Son derivaciones
# regenerables, no datos del usuario: los `.npz` se reconstruyen indexando y las
# descripciones se vuelven a redactar. Borrarlas es lo que impide que la siguiente
# construcción arranque con la caché de un grafo que ya no existe.
DERIVED: dict[str, tuple[str, ...]] = {
    KNOWLEDGE_GRAPH: ("concept_descriptions_path", "concepts_embeddings_path"),
    EXEMPLARS_PROFILE: (),
    EXEMPLARS_BANK: ("exemplars_bank_embeddings_path", "eval_rag_bank_embeddings_path"),
}


def artifact_files(ws: Workspace, artifact: str) -> list[Path]:
    """Los ficheros que SON el artefacto: el curado y, si lo hay, su borrador."""
    draft = autogenerated_path(ws, artifact)
    paths = [canonical_path(ws, artifact)] + ([draft] if draft else [])
    return [path for path in paths if path.is_file()]


def _derived_files(ws: Workspace, artifact: str) -> list[Path]:
    paths: list[Path] = []
    for attribute in DERIVED[artifact]:
        path = getattr(ws, attribute)
        # `concept_descriptions.fingerprints.json` vive al lado del fichero que describe y
        # solo lo nombra el describer; se recoge por vecindad para no duplicar esa regla.
        paths += [path, path.with_suffix(f".fingerprints{path.suffix}")]
    return [path for path in paths if path.is_file()]


# Vacía una etapa: el artefacto vuelve a «missing» y se puede reconstruir. NO toca
# `.history/`, que es justamente por dónde se deshace un borrado equivocado.
def discard(ws: Workspace, artifact: str) -> dict:
    files = artifact_files(ws, artifact)
    derived = _derived_files(ws, artifact)
    for path in files + derived:
        path.unlink(missing_ok=True)
    ReviewState(ws).reopen(artifact)
    return {
        "artifact": artifact,
        "removed": [str(path) for path in files],
        "derived": [str(path) for path in derived],
    }


# One instance per workspace, constructed where it is needed rather than kept as a
# singleton: it holds a path and reads a small JSON, so there is nothing to cache and
# nothing to keep in sync between two instances of two different workspaces.
class ReviewState:
    def __init__(self, ws: Workspace, path: Path | None = None):
        self.ws = ws
        self.path = Path(path or ws.review_state_path)

    # PERSISTENCE ---------------------------------------------------------------------------

    def _load(self) -> dict:
        if not self.path.is_file():
            return {}
        try:
            with self.path.open(encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}

    def _save(self, data: dict) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix(".json.tmp")
        with tmp.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        tmp.replace(self.path)

    # TRANSITIONS ---------------------------------------------------------------------------

    def approve(self, artifact: str) -> dict:
        path = current_path(self.ws, artifact)
        digest = storage.sha256_of(path)
        if digest is None:
            raise FileNotFoundError(f"'{artifact}' does not exist yet")

        data = self._load()
        data[artifact] = {
            "status": "approved",
            "hash": digest,
            "upstream": {
                up: storage.sha256_of(current_path(self.ws, up)) for up in UPSTREAM[artifact]
            },
            "at": datetime.now().isoformat(timespec="seconds"),
        }
        self._save(data)
        return data[artifact]

    def reopen(self, artifact: str) -> None:
        data = self._load()
        data.pop(artifact, None)
        self._save(data)

    def invalidate(self, artifact: str) -> None:
        """Called after an edit: the artifact goes back to draft, gates close behind it."""
        self.reopen(artifact)

    # READ ----------------------------------------------------------------------------------

    def state(self, artifact: str, building: set[str] | None = None) -> dict:
        building = building or set()
        path = current_path(self.ws, artifact)
        digest = storage.sha256_of(path)
        record = self._load().get(artifact)

        if artifact in building:
            status = "building"
        elif digest is None:
            status = "missing"
        elif record is None or record.get("status") != "approved":
            status = "draft"
        elif record.get("hash") != digest:
            status = "draft"
        else:
            status = "approved"

        stale_because: list[dict] = []
        if status == "approved":
            for upstream in UPSTREAM[artifact]:
                recorded = (record.get("upstream") or {}).get(upstream)
                if recorded != storage.sha256_of(current_path(self.ws, upstream)):
                    stale_because.append(
                        {
                            "artifact": upstream,
                            "label": LABELS[upstream],
                            "reason": STALE_ACTION.get(
                                (artifact, upstream), f"{LABELS[upstream]} cambió."
                            ),
                        }
                    )
            if stale_because:
                status = "stale"

        draft_path = autogenerated_path(self.ws, artifact)
        return {
            "artifact": artifact,
            "label": LABELS[artifact],
            "status": status,
            "hash": digest,
            "path": str(path) if path else None,
            "is_autogenerated": bool(path and draft_path and Path(path) == draft_path),
            "approved_at": record.get("at") if record else None,
            "stale_because": stale_because,
        }

    def snapshot(self, building: set[str] | None = None) -> list[dict]:
        states = {a: self.state(a, building) for a in ARTIFACTS}
        result = []
        for artifact in ARTIFACTS:
            state = states[artifact]
            blockers = [
                LABELS[up]
                for up in UPSTREAM[artifact]
                if states[up]["status"] != "approved"
            ]
            state["blocked_by"] = blockers
            state["blocked_reason"] = (
                f"Aprueba primero: {', '.join(blockers)}." if blockers else None
            )
            result.append(state)
        return result

    def gate_open(self, artifact: str) -> bool:
        """True when everything this artifact depends on has been approved."""
        return all(self.state(up)["status"] == "approved" for up in UPSTREAM[artifact])

    def generation_unlocked(self) -> bool:
        return all(self.state(a)["status"] == "approved" for a in ARTIFACTS)
