"""The chain of artifacts and its approval gates.

Each artifact is built, reviewed and approved before the next one is unlocked.
Approving records the artifact's own hash *and* the hash of everything it was
derived from; if an upstream later changes, the downstream is marked stale and
the UI can offer to redo that step. Nothing repairs itself behind the user's back.
"""

import json
from datetime import datetime
from pathlib import Path

from variant_generator import config, stages

from . import settings, storage

CONTENT_PROFILE = stages.CONTENT_PROFILE
KNOWLEDGE_GRAPH = stages.KNOWLEDGE_GRAPH
EXEMPLARS_BANK = stages.EXEMPLARS_BANK

ARTIFACTS: tuple[str, ...] = (CONTENT_PROFILE, KNOWLEDGE_GRAPH, EXEMPLARS_BANK)

# Verified against the code, not assumed: the profile only reads the raw exemplars,
# the KG only reads the raw corpus, and the bank needs both (schema for extraction,
# concepts for tagging). Reviewing in this order is the topological order.
UPSTREAM: dict[str, tuple[str, ...]] = {
    CONTENT_PROFILE: (),
    KNOWLEDGE_GRAPH: (),
    EXEMPLARS_BANK: (CONTENT_PROFILE, KNOWLEDGE_GRAPH),
}

LABELS = {
    CONTENT_PROFILE: "Perfil de contenido",
    KNOWLEDGE_GRAPH: "Grafo de conocimiento",
    EXEMPLARS_BANK: "Banco de ejemplos",
}

STALE_ACTION = {
    (EXEMPLARS_BANK, CONTENT_PROFILE): "El esquema cambió: los ítems se extrajeron con el anterior.",
    (EXEMPLARS_BANK, KNOWLEDGE_GRAPH): "El grafo cambió: las etiquetas apuntan a conceptos anteriores.",
}

_CANONICAL = {
    CONTENT_PROFILE: config.CONTENT_PROFILE_PATH,
    KNOWLEDGE_GRAPH: config.KG_PATH,
    EXEMPLARS_BANK: config.EXEMPLARS_BANK_PATH,
}

_AUTOGENERATED = {
    CONTENT_PROFILE: config.CONTENT_PROFILE_AUTOGENERATED_PATH,
    KNOWLEDGE_GRAPH: config.KG_AUTOGENERATED_PATH,
}


def canonical_path(artifact: str) -> Path:
    """Where an edit is written. Editing a draft promotes it to the curated file."""
    return _CANONICAL[artifact]


def current_path(artifact: str) -> Path | None:
    if artifact == CONTENT_PROFILE:
        return stages.content_profile_path()
    if artifact == KNOWLEDGE_GRAPH:
        return stages.knowledge_graph_path()
    path = config.EXEMPLARS_BANK_PATH
    return path if path.is_file() else None


class ReviewState:
    def __init__(self, path: Path = settings.REVIEW_STATE_PATH):
        self.path = Path(path)

    # PERSISTENCE ---------------------------------------------------------------------------

    def _load(self) -> dict:
        if not self.path.is_file():
            return {}
        try:
            with self.path.open(encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}

    def _save(self, data: dict) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.path.with_suffix(".json.tmp")
        with tmp.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        tmp.replace(self.path)

    # TRANSITIONS ---------------------------------------------------------------------------

    def approve(self, artifact: str) -> dict:
        path = current_path(artifact)
        digest = storage.sha256_of(path)
        if digest is None:
            raise FileNotFoundError(f"'{artifact}' does not exist yet")

        data = self._load()
        data[artifact] = {
            "status": "approved",
            "hash": digest,
            "upstream": {up: storage.sha256_of(current_path(up)) for up in UPSTREAM[artifact]},
            "at": datetime.now().isoformat(timespec="seconds"),
        }
        self._save(data)
        return data[artifact]

    def reopen(self, artifact: str) -> None:
        data = self._load()
        data.pop(artifact, None)
        self._save(data)

    def invalidate(self, artifact: str) -> None:
        """Called after an edit: the artifact goes back to draft, gates close behind it."""
        self.reopen(artifact)

    # READ ----------------------------------------------------------------------------------

    def state(self, artifact: str, building: set[str] | None = None) -> dict:
        building = building or set()
        path = current_path(artifact)
        digest = storage.sha256_of(path)
        record = self._load().get(artifact)

        if artifact in building:
            status = "building"
        elif digest is None:
            status = "missing"
        elif record is None or record.get("status") != "approved":
            status = "draft"
        elif record.get("hash") != digest:
            status = "draft"
        else:
            status = "approved"

        stale_because: list[dict] = []
        if status == "approved":
            for upstream in UPSTREAM[artifact]:
                recorded = (record.get("upstream") or {}).get(upstream)
                if recorded != storage.sha256_of(current_path(upstream)):
                    stale_because.append(
                        {
                            "artifact": upstream,
                            "label": LABELS[upstream],
                            "reason": STALE_ACTION.get(
                                (artifact, upstream), f"{LABELS[upstream]} cambió."
                            ),
                        }
                    )
            if stale_because:
                status = "stale"

        autogenerated_path = _AUTOGENERATED.get(artifact)
        return {
            "artifact": artifact,
            "label": LABELS[artifact],
            "status": status,
            "hash": digest,
            "path": str(path) if path else None,
            "is_autogenerated": bool(
                path and autogenerated_path and Path(path) == autogenerated_path
            ),
            "approved_at": record.get("at") if record else None,
            "stale_because": stale_because,
        }

    def snapshot(self, building: set[str] | None = None) -> list[dict]:
        states = {a: self.state(a, building) for a in ARTIFACTS}
        result = []
        for artifact in ARTIFACTS:
            state = states[artifact]
            blockers = [
                LABELS[up]
                for up in UPSTREAM[artifact]
                if states[up]["status"] != "approved"
            ]
            state["blocked_by"] = blockers
            state["blocked_reason"] = (
                f"Aprueba primero: {', '.join(blockers)}." if blockers else None
            )
            result.append(state)
        return result

    def gate_open(self, artifact: str) -> bool:
        """True when everything this artifact depends on has been approved."""
        return all(self.state(up)["status"] == "approved" for up in UPSTREAM[artifact])

    def generation_unlocked(self) -> bool:
        return all(self.state(a)["status"] == "approved" for a in ARTIFACTS)
