"""The chain of artifacts and its approval gates.

Each artifact is built, reviewed and approved before the next one is unlocked.
Approving records the artifact's own hash *and* the hash of everything it was
derived from; if an upstream later changes, the downstream is marked stale and
the UI can offer to redo that step. Nothing repairs itself behind the user's back.
"""

import json
from collections.abc import Callable
from datetime import datetime
from operator import attrgetter
from pathlib import Path

from loguru import logger

from variatio import stages
from variatio.core import json_io
from variatio.core.workspace import Workspace

from . import storage
from .db import mirror

# The study is optional to this module the way it is to the settings registry: it is
# reached by name, never by import direction, and its absence costs one derived file.
try:
    from study import rag_index_path

    _STUDY_DERIVED: tuple[Callable[[Workspace], Path], ...] = (rag_index_path,)
except ImportError:
    _STUDY_DERIVED = ()

EXEMPLARS_PROFILE = stages.EXEMPLARS_PROFILE
KNOWLEDGE_GRAPH = stages.KNOWLEDGE_GRAPH
EXEMPLARS_BANK = stages.EXEMPLARS_BANK

# The chain as the screens draw it: the navbar and the panel's cards read this tuple, so it
# is the order a person works in. The profile leads because finishing the graph needs an
# APPROVED profile — `routers/jobs.NEEDS_APPROVED` gates the taggability review on it.
ARTIFACTS: tuple[str, ...] = (EXEMPLARS_PROFILE, KNOWLEDGE_GRAPH, EXEMPLARS_BANK)

# `UPSTREAM[KNOWLEDGE_GRAPH]` is `()` and must stay so: a graph build reads only the raw
# corpus, so a read path that makes its screen depend on the profile fails in exactly the
# state a new workspace starts in. The bank's two ARE forced — it needs the profile's schema
# to extract and the graph's concepts to tag.
UPSTREAM: dict[str, tuple[str, ...]] = {
    KNOWLEDGE_GRAPH: (),
    EXEMPLARS_PROFILE: (),
    EXEMPLARS_BANK: (EXEMPLARS_PROFILE, KNOWLEDGE_GRAPH),
}

LABELS = {
    EXEMPLARS_PROFILE: "Perfil de ejemplares",
    KNOWLEDGE_GRAPH: "Grafo de conocimiento",
    EXEMPLARS_BANK: "Banco de ejemplares",
}

STALE_ACTION = {
    (EXEMPLARS_BANK, EXEMPLARS_PROFILE): "El esquema cambió: los ítems se extrajeron con el anterior.",
    (EXEMPLARS_BANK, KNOWLEDGE_GRAPH): "El grafo cambió: las etiquetas apuntan a conceptos anteriores.",
}


def canonical_path(ws: Workspace, artifact: str) -> Path:
    """Where an edit is written. Editing a draft promotes it to the curated file."""
    return {
        EXEMPLARS_PROFILE: ws.exemplars_profile_path,
        KNOWLEDGE_GRAPH: ws.kg_path,
        EXEMPLARS_BANK: ws.exemplars_bank_path,
    }[artifact]


def autogenerated_path(ws: Workspace, artifact: str) -> Path | None:
    """Where a build leaves its draft, for the two artifacts that have one."""
    return {
        EXEMPLARS_PROFILE: ws.exemplars_profile_autogenerated_path,
        KNOWLEDGE_GRAPH: ws.kg_autogenerated_path,
    }.get(artifact)


def current_path(ws: Workspace, artifact: str) -> Path | None:
    """The file actually read for an artifact: the curated one, else its draft."""
    if artifact == EXEMPLARS_PROFILE:
        return stages.exemplars_profile_path(ws)
    if artifact == KNOWLEDGE_GRAPH:
        return stages.knowledge_graph_path(ws)
    path = ws.exemplars_bank_path
    return path if path.is_file() else None


# What stops making sense once the artifact is gone: regenerable derivations, not user
# data, deleted so the next build does not start on the cache of a graph that no longer
# exists. Resolvers and not attribute names, because the rag arm's index is the study's
# file and `Workspace` does not name it.
DERIVED: dict[str, tuple[Callable[[Workspace], Path], ...]] = {
    KNOWLEDGE_GRAPH: (
        attrgetter("concept_descriptions_path"),
        attrgetter("concept_sources_path"),
        attrgetter("concepts_embeddings_path"),
    ),
    EXEMPLARS_PROFILE: (),
    EXEMPLARS_BANK: (attrgetter("exemplars_bank_embeddings_path"),) + _STUDY_DERIVED,
}


def artifact_files(ws: Workspace, artifact: str) -> list[Path]:
    """The files that ARE the artifact: the curated one and, if there is one, its draft."""
    draft = autogenerated_path(ws, artifact)
    paths = [canonical_path(ws, artifact)] + ([draft] if draft else [])
    return [path for path in paths if path.is_file()]


def _derived_files(ws: Workspace, artifact: str) -> list[Path]:
    """The regenerable files an artifact leaves behind, each with its `.fingerprints` twin.

    The twin is collected by adjacency rather than named, so only the describer knows the
    convention.
    """
    paths: list[Path] = []
    for resolve in DERIVED[artifact]:
        path = resolve(ws)
        paths += [path, path.with_suffix(f".fingerprints{path.suffix}")]
    return [path for path in paths if path.is_file()]


def discard(ws: Workspace, artifact: str) -> dict:
    """Empty a stage: the artifact goes back to «missing» and can be rebuilt.

    It does NOT touch `.history/`, which is how a mistaken deletion is undone.
    """
    files = artifact_files(ws, artifact)
    derived = _derived_files(ws, artifact)
    for path in files + derived:
        path.unlink(missing_ok=True)
    ReviewState(ws).reopen(artifact)
    return {
        "artifact": artifact,
        "removed": [str(path) for path in files],
        "derived": [str(path) for path in derived],
    }


def retire_curated(ws: Workspace, artifact: str) -> bool:
    """Send the curated file to the history so a fresh draft becomes the artifact."""
    draft = autogenerated_path(ws, artifact)
    curated = canonical_path(ws, artifact)
    if draft is None or not draft.is_file() or not curated.is_file():
        return False
    storage.backup(ws, curated, artifact)
    curated.unlink()
    ReviewState(ws).reopen(artifact)
    logger.info(
        f"[revisión] «{LABELS[artifact]}» curado anterior retirado al historial; "
        "el borrador recién construido pasa a ser el artefacto"
    )
    return True


def _status(artifact: str, building: set[str], digest: str | None, record: dict | None) -> str:
    """Read an artifact's state off its digest and its approval record.

    Staleness is not decided here: it needs the upstreams' digests and only applies to
    something already approved.
    """
    if artifact in building:
        return "building"
    if digest is None:
        return "missing"
    if record is None or record.get("status") != "approved":
        return "draft"
    if record.get("hash") != digest:
        return "draft"
    return "approved"


class ReviewState:
    """One workspace's approvals, read from and written to its `.review_state.json`.

    Constructed where it is needed rather than kept as a singleton: it holds a path and a
    small JSON, so a shared one would only answer for whichever workspace was read last.
    """

    def __init__(self, ws: Workspace, path: Path | None = None):
        """Bind to a workspace and, optionally, to a state file other than its own."""
        self.ws = ws
        self.path = Path(path or ws.review_state_path)

    # PERSISTENCE ---------------------------------------------------------------------------

    def _load(self) -> dict:
        """Read the approvals, treating a missing or corrupt file as none."""
        if not self.path.is_file():
            return {}
        try:
            with self.path.open(encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}

    def _save(self, data: dict) -> None:
        """Write the approvals back."""
        json_io.write_json(self.path, data)

    # TRANSITIONS ---------------------------------------------------------------------------

    def approve(self, artifact: str) -> dict:
        """Record an artifact's own hash and its upstreams', so a later drift reads stale.

        Raises FileNotFoundError when there is nothing built to approve.
        """
        path = current_path(self.ws, artifact)
        digest = storage.sha256_of(path)
        if digest is None:
            raise FileNotFoundError(f"'{artifact}' does not exist yet")

        data = self._load()
        data[artifact] = {
            "status": "approved",
            "hash": digest,
            "upstream": {
                up: storage.sha256_of(current_path(self.ws, up)) for up in UPSTREAM[artifact]
            },
            "at": datetime.now().isoformat(timespec="seconds"),
        }
        self._save(data)
        mirror.mirror_approval(self.ws.slug, artifact, True, UPSTREAM[artifact])
        return data[artifact]

    def reopen(self, artifact: str) -> None:
        """Withdraw an artifact's approval, closing the gates behind it."""
        data = self._load()
        data.pop(artifact, None)
        self._save(data)
        mirror.mirror_approval(self.ws.slug, artifact, False)

    def invalidate(self, artifact: str) -> None:
        """Called after an edit: the artifact goes back to draft, gates close behind it."""
        self.reopen(artifact)

    # READ ----------------------------------------------------------------------------------

    def _stale_because(self, artifact: str, record: dict) -> list[dict]:
        """Name every upstream whose file no longer hashes to what the approval recorded."""
        out: list[dict] = []
        for upstream in UPSTREAM[artifact]:
            recorded = (record.get("upstream") or {}).get(upstream)
            if recorded != storage.sha256_of(current_path(self.ws, upstream)):
                out.append(
                    {
                        "artifact": upstream,
                        "label": LABELS[upstream],
                        "reason": STALE_ACTION.get(
                            (artifact, upstream), f"{LABELS[upstream]} cambió."
                        ),
                    }
                )
        return out

    def state(self, artifact: str, building: set[str] | None = None) -> dict:
        """Report one artifact's state as the screens draw it."""
        path = current_path(self.ws, artifact)
        digest = storage.sha256_of(path)
        record = self._load().get(artifact)

        status = _status(artifact, building or set(), digest, record)
        stale_because = self._stale_because(artifact, record) if status == "approved" else []
        if stale_because:
            status = "stale"

        draft_path = autogenerated_path(self.ws, artifact)
        return {
            "artifact": artifact,
            "label": LABELS[artifact],
            "status": status,
            "hash": digest,
            "path": str(path) if path else None,
            "is_autogenerated": bool(path and draft_path and Path(path) == draft_path),
            "approved_at": record.get("at") if record else None,
            "stale_because": stale_because,
        }

    def snapshot(self, building: set[str] | None = None) -> list[dict]:
        """Report the whole chain, each stage carrying what still blocks it."""
        states = {a: self.state(a, building) for a in ARTIFACTS}
        result = []
        for artifact in ARTIFACTS:
            state = states[artifact]
            blockers = [
                LABELS[up]
                for up in UPSTREAM[artifact]
                if states[up]["status"] != "approved"
            ]
            state["blocked_by"] = blockers
            state["blocked_reason"] = (
                f"Aprueba primero: {', '.join(blockers)}." if blockers else None
            )
            result.append(state)
        return result

    def gate_open(self, artifact: str) -> bool:
        """True when everything this artifact depends on has been approved."""
        return all(self.state(up)["status"] == "approved" for up in UPSTREAM[artifact])

    def generation_unlocked(self) -> bool:
        """True when every artifact of the chain is approved."""
        return all(self.state(a)["status"] == "approved" for a in ARTIFACTS)
