"""The subject's teaching criteria, the one artifact of the tutor's own.

Two files, as every artifact of the chain: `tutor_criteria_autogenerated.json` is what the
last build drafted (`criteria_builder`), `tutor_criteria.json` is a teacher's curation, and
the curated file wins whenever it exists. A build writes the draft only, so a teacher's work
is never overwritten by a model; the server retires the curated file to the history when a
rebuild is asked for, which is the same contract the graph and the profile keep.

Read against the graph, as the curriculum is: a unit or a concept the graph no longer has is
dropped with a warning rather than trusted, so a rebuilt graph never makes the tutor quote a
unit that is gone. The same `normalize` cleans what a build drafts and what a teacher saves,
so the two cannot disagree about what a criterion is.

What a criterion is NOT: the method. Guiding with questions, never handing over a solution
and citing the notes are the system's rules (`tutor.prompts`), hold in every subject, and no
file can switch them off.
"""

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from loguru import logger

from variatio.core.lexicon import fold
from variatio.core.workspace import Workspace

from . import paths

MUST = "must"
SHOULD = "should"
STRENGTHS = (MUST, SHOULD)

CURATED = "curated"
DRAFT = "draft"
MISSING = "missing"

# A criterion is one or two sentences and a term one word or two; anything longer is a pasted
# document, and the card that carries it has a budget of its own.
_TEXT_MAX = 600
_TERM_MAX = 60
_REPLY_MAX = 600


@dataclass(frozen=True)
class Criterion:
    """One rule of the subject: what it says, how firmly, what it is about and who says so."""

    text: str
    strength: str = SHOULD
    concepts: tuple[str, ...] = ()
    sources: tuple[dict, ...] = ()


@dataclass(frozen=True)
class ForbiddenTerm:
    """A statement or function the material does not use, which the tutor never suggests."""

    term: str
    reason: str = ""
    sources: tuple[dict, ...] = ()


@dataclass(frozen=True)
class Criteria:
    """The subject's criteria as one turn reads them, already validated against the graph."""

    general: tuple[Criterion, ...] = ()
    units: dict[str, tuple[Criterion, ...]] = field(default_factory=dict)
    forbidden_terms: tuple[ForbiddenTerm, ...] = ()
    administrative_reply: str = ""
    origin: str = MISSING

    def for_focus(self, unit: str | None, concepts: list[str], max_chars: int) -> list[Criterion]:
        """Return what one turn carries: the general rules, then the focus's, within a budget.

        Within the unit, a criterion naming a focus concept goes before one that does not, and
        an obligation before a recommendation; a criterion of another unit enters only when it
        names a focus concept. What does not fit the budget stays out whole, never cut.
        """
        wanted = set(concepts)
        local = list(self.units.get(unit, ())) if unit else []
        elsewhere = [
            criterion
            for name, listed in self.units.items()
            if name != unit
            for criterion in listed
            if wanted.intersection(criterion.concepts)
        ]
        local.sort(key=lambda c: (not wanted.intersection(c.concepts), c.strength != MUST))
        picked: list[Criterion] = []
        spent = 0
        for criterion in [*self.general, *local, *elsewhere]:
            if criterion in picked:
                continue
            if spent + len(criterion.text) > max_chars:
                continue
            picked.append(criterion)
            spent += len(criterion.text)
        return picked

    def terms(self) -> list[str]:
        """Return the forbidden terms by name, in the order they were declared."""
        return [term.term for term in self.forbidden_terms]


def load(ws: Workspace, knowledge_graph, default_reply: str) -> Criteria:
    """Return the criteria a turn reads: the curated file, else the draft, else none at all."""
    data, origin = read(ws)
    if data is None:
        return Criteria(administrative_reply=default_reply, origin=MISSING)
    clean, warnings = normalize(data, knowledge_graph, default_reply)
    for warning in warnings:
        logger.warning(f"[tutor] Criterios de «{ws.slug}»: {warning}")
    return Criteria(
        general=tuple(_criterion(entry) for entry in clean["general"]),
        units={
            unit: tuple(_criterion(entry) for entry in listed)
            for unit, listed in clean["units"].items()
        },
        forbidden_terms=tuple(
            ForbiddenTerm(
                term=entry["term"], reason=entry["reason"], sources=tuple(entry["sources"])
            )
            for entry in clean["forbidden_terms"]
        ),
        administrative_reply=clean["administrative_reply"],
        origin=origin,
    )


def read(ws: Workspace) -> tuple[dict | None, str]:
    """Return the raw criteria in force and where they came from, or `(None, MISSING)`."""
    for path, origin in ((paths.criteria_path(ws), CURATED), (paths.criteria_draft_path(ws), DRAFT)):
        data = _read_json(path)
        if data is not None:
            return data, origin
    return None, MISSING


def normalize(data: dict, knowledge_graph, default_reply: str) -> tuple[dict, list[str]]:
    """Clean a criteria document against the graph, returning it and what had to be dropped.

    Unknown units and concepts go, empty or overlong texts go, a strength outside the two
    known becomes a recommendation, and repeated texts and terms collapse into their first
    occurrence. The draft's build record travels untouched: it is what the screen shows as
    "drafted on … by …".
    """
    warnings: list[str] = []
    known_units = set(getattr(knowledge_graph, "domains", []) or [])
    known_concepts = set(getattr(knowledge_graph, "all_concepts", []) or [])

    def clean_list(entries, where: str) -> list[dict]:
        """Clean one list of criteria, dropping repeats within it."""
        kept: list[dict] = []
        seen: set[str] = set()
        for entry in entries if isinstance(entries, list) else []:
            criterion = _clean_criterion(entry, known_concepts, warnings, where)
            if criterion is None or fold(criterion["text"]) in seen:
                continue
            seen.add(fold(criterion["text"]))
            kept.append(criterion)
        return kept

    units: dict[str, list[dict]] = {}
    raw_units = data.get("units") if isinstance(data.get("units"), dict) else {}
    for unit, entries in raw_units.items():
        if known_units and unit not in known_units:
            warnings.append(f"la unidad «{unit}» ya no está en el temario y se ignora")
            continue
        units[unit] = clean_list(entries, f"«{unit}»")

    clean = {
        "general": clean_list(data.get("general"), "generales"),
        "units": units,
        "forbidden_terms": _clean_terms(data.get("forbidden_terms")),
        "administrative_reply": _clip(data.get("administrative_reply"), _REPLY_MAX) or default_reply,
    }
    if isinstance(data.get("built"), dict):
        clean["built"] = data["built"]
    return clean, warnings


def empty(default_reply: str) -> dict:
    """Return a criteria document with nothing in it but the administrative reply."""
    return {"general": [], "units": {}, "forbidden_terms": [], "administrative_reply": default_reply}


def _clean_criterion(entry, known_concepts: set[str], warnings: list[str], where: str) -> dict | None:
    """Return one criterion cleaned, or None when it has no text worth keeping."""
    if not isinstance(entry, dict):
        return None
    text = _clip(entry.get("text"), _TEXT_MAX)
    if not text:
        return None
    strength = entry.get("strength") if entry.get("strength") in STRENGTHS else SHOULD
    concepts: list[str] = []
    for name in entry.get("concepts") or []:
        if not isinstance(name, str) or name in concepts:
            continue
        if known_concepts and name not in known_concepts:
            warnings.append(f"el concepto «{name}» de un criterio {where} ya no está en el grafo")
            continue
        concepts.append(name)
    return {"text": text, "strength": strength, "concepts": concepts, "sources": _sources(entry)}


def _clean_terms(entries) -> list[dict]:
    """Clean the forbidden terms, dropping empty ones, repeats regardless of case, and symbols.

    A term with no letter (`/`, `*`) is an operator, and an operator cannot be checked in a
    reply: the demo subject's draft vetoed `*`, and every reply that set a heading in bold
    failed as one that suggested it.
    """
    kept: list[dict] = []
    seen: set[str] = set()
    for entry in entries if isinstance(entries, list) else []:
        if isinstance(entry, str):
            entry = {"term": entry}
        if not isinstance(entry, dict):
            continue
        term = _clip(entry.get("term"), _TERM_MAX)
        if not term or not re.search(r"[^\W\d_]", term) or fold(term) in seen:
            continue
        seen.add(fold(term))
        kept.append(
            {"term": term, "reason": _clip(entry.get("reason"), _TEXT_MAX), "sources": _sources(entry)}
        )
    return kept


def _sources(entry: dict) -> list[dict]:
    """Return an entry's sources as `{document, location}` pairs of plain strings."""
    found: list[dict] = []
    for source in entry.get("sources") or []:
        if not isinstance(source, dict):
            continue
        pair = {
            "document": _clip(source.get("document"), 200),
            "location": _clip(source.get("location"), 300),
        }
        if (pair["document"] or pair["location"]) and pair not in found:
            found.append(pair)
    return found


def _criterion(entry: dict) -> Criterion:
    """Return one cleaned criterion as the frozen value a card carries."""
    return Criterion(
        text=entry["text"],
        strength=entry["strength"],
        concepts=tuple(entry["concepts"]),
        sources=tuple(entry["sources"]),
    )


def _clip(value, limit: int) -> str:
    """Return a value as stripped text no longer than `limit`, or empty for anything else."""
    return value.strip()[:limit] if isinstance(value, str) else ""


def _read_json(path: Path) -> dict | None:
    """Read one criteria file, or None when it is absent or unreadable — said once per read."""
    if not path.is_file():
        return None
    try:
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning(f"[tutor] No se pudo leer '{path}': {exc}")
        return None
    return data if isinstance(data, dict) else None
