"""Where the tutor keeps what it reads and writes inside a workspace.

Derived here and not on `Workspace`: these are the tutor's files, and `variatio` must not
know the tutor exists. Each path sits where its kind already lives — the criteria beside the
other artifacts in `instance/` (so `export-instance` and the history treat them alike), the
passage index under `cache/embeddings/` (so emptying the cache takes it), and the
conversations in a directory of their own, one per author, as the generated exercises are.
"""

from pathlib import Path

from variatio.core.workspace import Workspace

CRITERIA_STEM = "tutor_criteria"


def criteria_path(ws: Workspace) -> Path:
    """The teacher's curated criteria, which win over the draft whenever they exist."""
    return ws.instance_dir / f"{CRITERIA_STEM}.json"


def criteria_draft_path(ws: Workspace) -> Path:
    """The criteria as the last build drafted them."""
    return ws.instance_dir / f"{CRITERIA_STEM}_autogenerated.json"


def conversations_dir(ws: Workspace) -> Path:
    """The tutor's conversations, one directory per author."""
    return ws.root / "tutor"


def passages_cache_path(ws: Workspace) -> Path:
    """The embedded passages of the notes, regenerable from the page cache."""
    return ws.cache_dir / "embeddings" / "tutor_passages.npz"


def corpus_pages_dir(ws: Workspace) -> Path:
    """The transcribed pages of the corpus, one directory per document."""
    return ws.markdown_cache_dir / ws.raw_corpus_dir.name
