from ..types import Impact, Setting

SETTINGS: list[Setting] = [
    Setting(key="generation.tagger_top_k", name="TAGGER_TOP_K_CANDIDATES", kind="int",
            default=10, group="Etiquetado y generación", impact=Impact.CONTEXTS, minimum=1,
            doc="""La banda fija de candidatos que el embedder entrega al verificador LLM; lo que el prefiltro descarta el LLM nunca puede recuperarlo, así que este valor es el techo de todo el etiquetado."""),
    Setting(key="generation.tagger_fallback_top_k", name="TAGGER_FALLBACK_TOP_K", kind="int",
            default=30, group="Etiquetado y generación", impact=Impact.CONTEXTS, minimum=1,
            doc="""La banda más amplia con la que se reintenta una sola vez cuando el verificador rechaza todos los candidatos de TAGGER_TOP_K_CANDIDATES."""),
    Setting(key="generation.max_few_shot_examples", name="MAX_FEW_SHOT_EXAMPLES", kind="int",
            default=4, group="Etiquetado y generación", impact=Impact.NONE, minimum=1,
            doc="""El número de ítems del banco de ejemplares que se muestran al generador como ejemplos few-shot en el prompt de generación."""),
    Setting(key="generation.max_json_repair_tries", name="MAX_JSON_REPAIR_TRIES", kind="int",
            default=3, group="Etiquetado y generación", impact=Impact.NONE, minimum=0,
            doc="""Acota el bucle de reintentos de parse_with_repair al reparar una respuesta JSON del modelo que llega mal formada."""),
    Setting(key="generation.check_similarity_threshold", name="CHECK_SIMILARITY_THRESHOLD",
            kind="float", default=0.85, group="Etiquetado y generación", impact=Impact.NONE,
            minimum=0.0, maximum=1.0,
            doc="""Por encima de este parecido, el aviso de similitud entre variantes se marca como alto. Lo lee checks.py al comparar una variante recién generada con las que ya existen. No está medido contra un corpus: es un umbral de presentación, no de decisión — nada se descarta por cruzarlo."""),
    Setting(key="generation.instructions_max_chars", name="GENERATION_INSTRUCTIONS_MAX_CHARS",
            kind="int", default=600, group="Etiquetado y generación", impact=Impact.NONE,
            minimum=1,
            doc="""Acota el texto libre de instrucciones que puede llevar una comisión, y es lo que lee el modelo guardarraíl — por lo que la ventana de contexto del guardarraíl puede quedarse pequeña."""),
    Setting(key="generation.content_context_max_chars", name="CONTENT_CONTEXT_MAX_CHARS",
            kind="int", default=900, group="Etiquetado y generación", impact=Impact.REINDEX,
            minimum=1,
            doc="""El contexto de la asignatura entra en TODOS los prompts del sistema, así que su coste se paga una vez por llamada y en cada una de ellas. 900 caracteres son ~250 tokens: espacio de sobra para decir qué materia es, a qué nivel, en qué idioma y con qué convenciones, y poco suficiente como para que no compita con el material que el prompt lleva de verdad. También es lo que acota la síntesis: sin techo, cada reconstrucción añadiría un matiz más."""),
    Setting(key="generation.guardrail_criteria", name="GUARDRAIL_CRITERIA", kind="list[str]",
            default=["harm", "jailbreak"], group="Etiquetado y generación", impact=Impact.NONE,
            doc="""Los criterios contra los que el modelo guardarraíl examina una comisión antes de que el generador escriba la variante."""),
]
