"""Phase 3 — domains, the syllabus order, and the one file a build writes.

The result is still a DRAFT. The final curation into `instance/knowledge_graph.json`
(draining the unclassified bucket, fixing dubious directions) is manual.
"""

from collections import Counter, defaultdict
from pathlib import Path

import networkx as nx
from loguru import logger

from ... import config
from ...core import inference, progress
from ...core.json_io import write_json
from ...core.lexicon import fold
from ...prompts import (
    assign_leftover_concepts_prompt,
    curate_graph_domains_prompt,
    link_cross_domain_relations_prompt,
    link_domain_relations_prompt,
    segment_syllabus_prompt,
)
from . import blocks, parsing
from .schemas import DOMAIN_NAMES_SCHEMA, DOMAINS_SCHEMA, LINK_SCHEMA, UNITS_SCHEMA


def run(
    cleaned: dict,
    output_path: str | Path,
    sources_path: str | Path,
    *,
    schema,
    max_attempts: int,
) -> dict:
    concepts = cleaned["entities"]
    relations = cleaned["relations"]
    logger.info(f"Curando {len(concepts)} concepto(s) y {len(relations)} relación(es)")

    positions = cleaned.get("positions") or {}
    definitions = cleaned.get("definitions") or {}

    progress.phase("domains", f"clasificando {len(concepts)} concepto(s)")
    with progress.step("kg_domains", "Agrupando los conceptos en dominios"):
        progress.checkpoint()
        concepts_by_domains, units = curate_units(cleaned, max_attempts=max_attempts)
        if not concepts_by_domains:
            concepts_by_domains = order_domains(
                curate_domains(
                    concepts,
                    relations,
                    cleaned.get("documents") or [],
                    cleaned.get("origins") or {},
                    definitions,
                    max_attempts=max_attempts,
                ),
                positions,
            )
        logger.info(f"Dominios: {len(concepts_by_domains)}")
    progress.advance(1.0, f"{len(concepts_by_domains)} dominio(s)")

    relations = link_relations(
        concepts_by_domains,
        relations,
        definitions,
        schema=schema,
        max_attempts=max_attempts,
    )

    progress.phase("curate")
    with progress.step("kg_curate", "Tipando las relaciones y rompiendo ciclos"):
        universe = {c for cs in concepts_by_domains.values() for c in cs}
        typed = build_typed_relations(relations, universe, schema)
        report_against_order(typed, positions, schema.prerequisite_verbose)
        typed = break_cycles(typed, positions, schema.prerequisite_verbose)
        logger.info(
            f"Relaciones: {len(typed)} grupo(s) tipados sobre {len(universe)} concepto(s)"
        )
    progress.advance(1.0)

    curated = {
        "concepts_by_domains": concepts_by_domains,
        "generic_non_taggable_concepts": [],
        "taggability_reviewed": False,
        "relations": typed,
    }
    write_json(output_path, curated)
    write_sources(sources_path, cleaned, universe, units)
    logger.success(
        f"Borrador curado en {Path(output_path).name}: {len(universe)} concepto(s), "
        f"{len(typed)} grupo(s) de relación; falta revisar la etiquetabilidad"
    )
    return curated


# ANCLAJE AL CORPUS -----------------------------------------------------------------------


# The second — and last — file a graph build writes, and not one of the intermediate
# stages that were removed: it is each concept's anchoring to the corpus, in `cache/`,
# beside the descriptions that read it. It is kept apart from the artifact on purpose. The
# curated graph is edited by hand and this is hundreds of KB of quotations; and it is
# regenerated by a build, like the markdown next to it, so it is not user data.
#
# `documents` keeps the whole corpus list because a prompt decision comes from it: naming
# each passage's document only makes sense when there is more than one.
def write_sources(
    path: str | Path, cleaned: dict, universe: set, units: list[dict] | None = None
) -> None:
    passages = cleaned.get("passages") or {}
    definitions = cleaned.get("definitions") or {}
    documents = [d.get("name", "") for d in (cleaned.get("documents") or [])]
    anchored = {c: passages[c] for c in sorted(universe) if passages.get(c)}
    defined = {c: definitions[c] for c in sorted(universe) if definitions.get(c)}
    payload = {"documents": documents, "concepts": anchored, "definitions": defined}
    if cleaned.get("outline"):
        payload["outline"] = cleaned["outline"]
    if units:
        payload["units"] = units
    write_json(path, payload)

    orphans = len(universe) - len(anchored)
    if orphans:
        logger.warning(f"{orphans} concepto(s) sin pasaje del corpus que los respalde")
    logger.info(
        f"Anclaje al corpus: {len(anchored)} de {len(universe)} concepto(s) con cita "
        f"en {Path(path).name}"
    )


# UNITS -----------------------------------------------------------------------------------


MIN_UNITS = 2


def segment_syllabus(
    outline: list[dict], documents: list[dict], *, max_attempts: int
) -> list[dict]:
    if not outline:
        logger.info(
            "El corpus no tiene índice de encabezados; los dominios se nombran sin mirar "
            "la estructura del material"
        )
        return []
    prompt = segment_syllabus_prompt(blocks.outline_block(outline, documents))
    response = inference.generate(
        model=config.KG_UNITS_MODEL,
        prompt=prompt,
        think=config.THINK_KG_UNITS,
        format=None if config.THINK_KG_UNITS else UNITS_SCHEMA,
        temperature=inference.judgement_temperature(config.THINK_KG_UNITS),
    ).response
    raw = parsing.parse_object(response, "[units] ", UNITS_SCHEMA, max_attempts) or {}
    units = accept_units(raw.get("units") or [], outline)
    if not units:
        logger.warning(
            f"El modelo no segmentó el temario sobre {len(outline)} encabezado(s); "
            "se nombran los dominios sin mirar la estructura del material"
        )
        return []
    logger.success(
        f"Temario: {len(units)} unidad(es) sobre {len(outline)} encabezado(s) — "
        + " · ".join(unit["name"] for unit in units)
    )
    return units


def accept_units(proposed: list, outline: list[dict]) -> list[dict]:
    unclassified = config.KG_BUILDER_UNCLASSIFIED_DOMAIN
    units: list[dict] = []
    seen_positions: set[int] = set()
    seen_names: set[str] = set()
    seen_chunks: set[int] = set()

    for entry in proposed:
        if not isinstance(entry, dict):
            continue
        raw_name = entry.get("name")
        name = raw_name.strip() if isinstance(raw_name, str) else ""
        position = entry.get("opens_at")
        if not name or fold(name) == fold(unclassified):
            continue
        if not isinstance(position, int) or isinstance(position, bool):
            continue
        if not 1 <= position <= len(outline):
            continue
        if position in seen_positions or name.casefold() in seen_names:
            continue
        anchor = outline[position - 1]
        if anchor["chunk"] in seen_chunks:
            continue
        seen_positions.add(position)
        seen_names.add(name.casefold())
        seen_chunks.add(anchor["chunk"])
        units.append({"name": name, "heading": anchor["heading"], "chunk": anchor["chunk"]})

    units.sort(key=lambda unit: unit["chunk"])
    return units if len(units) >= MIN_UNITS else []


def unit_at(units: list[dict], chunk: int) -> str | None:
    found = None
    for unit in units:
        if unit["chunk"] > chunk:
            break
        found = unit["name"]
    return found


def unit_of(units: list[dict], chunks: list[int]) -> str | None:
    order = {unit["name"]: index for index, unit in enumerate(units)}
    votes: Counter = Counter()
    for chunk in chunks:
        name = unit_at(units, chunk)
        if name is not None:
            votes[name] += 1
    if not votes:
        return None
    return min(votes, key=lambda name: (-votes[name], order[name]))


def assign_to_units(
    units: list[dict], concepts: list[str], occurrences: dict
) -> tuple[dict, list[str]]:
    by_unit: dict[str, list[str]] = {unit["name"]: [] for unit in units}
    leftovers: list[str] = []
    for concept in concepts:
        name = unit_of(units, occurrences.get(concept) or [])
        if name is None:
            leftovers.append(concept)
        else:
            by_unit[name].append(concept)
    return by_unit, leftovers


def curate_units(cleaned: dict, *, max_attempts: int) -> tuple[dict, list[dict]]:
    outline = cleaned.get("outline") or []
    units = segment_syllabus(
        outline, cleaned.get("documents") or [], max_attempts=max_attempts
    )
    if not units:
        return {}, []

    concepts = sorted(cleaned["entities"])
    by_unit, leftovers = assign_to_units(units, concepts, cleaned.get("occurrences") or {})
    logger.info(
        f"Temario: {len(concepts) - len(leftovers)} de {len(concepts)} concepto(s) "
        f"colocados por el corpus; {len(leftovers)} para la repesca"
    )
    if leftovers:
        by_unit[config.KG_BUILDER_UNCLASSIFIED_DOMAIN] = sorted(leftovers)

    placed = place_leftovers(
        by_unit,
        cleaned.get("relations") or [],
        cleaned.get("definitions") or {},
        max_attempts=max_attempts,
    )
    positions = cleaned.get("positions") or {}
    return {d: blocks.ordered(m, positions) for d, m in placed.items()}, units


# DOMAINS ---------------------------------------------------------------------------------


# This call names the blocks and places nothing, so it is shown every concept — the units
# of a syllabus cannot be named from a sample — but NOT the relation evidence: that is what
# justifies WHERE a concept goes, which is `assign_round`'s question and where the evidence
# is shown. It is also most of what used to make this the largest prompt in the pipeline.
#
# `think=False` with the grammar, and here that is load-bearing rather than a default. Asked
# to partition the whole inventory, this call turned the reasoning channel into the answer:
# measured over 203 concepts with `qwen3.8:27b-q4_K_M` at `low`, it enumerated
# «24. Colecciones → Domain 5 ✓» for 36 929 characters, hit its stop token at concept 60 and
# returned `response == ""` with `done_reason: "stop"` — indistinguishable upstream from a
# real answer, and every concept would have landed in `Sin clasificar`, silently. The prompt
# no longer asks for the partition, but a handful of names is exactly what a grammar pins
# down, and the enumeration is one prompt edit away.
def curate_domains(
    concepts: list[str],
    relations: list[list],
    documents: list[dict],
    origins: dict[str, list[int]],
    definitions: dict[str, str] | None = None,
    *,
    max_attempts: int,
) -> dict:
    prompt = curate_graph_domains_prompt(
        blocks.nodes_block(concepts, [], {}, origins),
        blocks.documents_block(documents),
    )
    response = inference.generate(
        model=config.KG_DOMAINS_MODEL,
        prompt=prompt,
        think=config.THINK_KG_DOMAINS,
        format=None if config.THINK_KG_DOMAINS else DOMAIN_NAMES_SCHEMA,
        temperature=inference.judgement_temperature(config.THINK_KG_DOMAINS),
    ).response
    raw = parsing.parse_object(response, "[domains] ", DOMAIN_NAMES_SCHEMA, max_attempts) or {}

    named: list[str] = []
    for domain in raw.get("domains") or []:
        name = domain.strip() if isinstance(domain, str) else ""
        if name and fold(name) != fold(config.KG_BUILDER_UNCLASSIFIED_DOMAIN) and name not in named:
            named.append(name)
    if not named:
        logger.warning("El modelo no nombró ningún dominio; todo queda sin clasificar")
        return {config.KG_BUILDER_UNCLASSIFIED_DOMAIN: sorted(concepts)}

    logger.info(f"{len(named)} dominio(s) nombrados; asignando {len(concepts)} concepto(s) por lotes")
    by_domain = {domain: [] for domain in named}
    remaining = assign_round(
        sorted(concepts), by_domain, relations, definitions, max_attempts=max_attempts
    )

    for domain in by_domain:
        by_domain[domain] = sorted(set(by_domain[domain]))
    if remaining:
        by_domain[config.KG_BUILDER_UNCLASSIFIED_DOMAIN] = sorted(remaining)
    return place_leftovers(by_domain, relations, definitions, max_attempts=max_attempts)


# A concept parked in the unclassified bucket is not a concept the model judged hard to
# place — it is one it never reached. It keeps its relations, so it still works as
# scaffolding, but it gets no domain-level review: neither the per-domain linking nor
# the taggability pass can reason about a bucket that shares no theme. Asking again,
# with only the leftovers and the domains already fixed, is a much smaller question.
def place_leftovers(
    by_domain: dict,
    relations: list[list],
    definitions: dict[str, str] | None = None,
    *,
    max_attempts: int,
) -> dict:
    unclassified = config.KG_BUILDER_UNCLASSIFIED_DOMAIN
    leftovers = by_domain.get(unclassified)
    if not leftovers:
        return by_domain

    placed = {d: list(m) for d, m in by_domain.items() if d != unclassified}
    if not placed:
        return by_domain

    logger.info(f"Colocando {len(leftovers)} concepto(s) sueltos en {len(placed)} dominio(s)")
    remaining = list(leftovers)
    # Small batches and repeated rounds, because the failure being repaired here is
    # "forgot to answer", not "could not decide": at 60 names a call the model placed 24
    # of 84, and the ones it skipped are not the hard ones — asked again, in a shorter
    # list, most of them get placed. Rounds stop as soon as one adds nothing, so a
    # genuinely unplaceable concept costs one extra call and not three.
    for _ in range(config.KG_BUILDER_DOMAIN_ROUNDS):
        before = len(remaining)
        remaining = assign_round(
            remaining, placed, relations, definitions, max_attempts=max_attempts
        )
        if not remaining or len(remaining) == before:
            break

    for domain in placed:
        placed[domain] = sorted(set(placed[domain]))
    if remaining:
        placed[unclassified] = sorted(remaining)
    logger.info(
        f"Sueltos: {len(leftovers) - len(remaining)} colocados, "
        f"{len(remaining)} sin clasificar"
    )
    return placed


def assign_round(
    pending: list[str],
    placed: dict,
    relations: list[list],
    definitions: dict[str, str] | None = None,
    *,
    max_attempts: int,
) -> list[str]:
    size = config.KG_BUILDER_DOMAIN_BATCH_SIZE
    batches = [pending[i : i + size] for i in range(0, len(pending), size)]
    unplaced = set(pending)

    for idx, batch in enumerate(batches, 1):
        progress.checkpoint()
        progress.advance(
            0.5 + 0.45 * (idx - 1) / len(batches), f"sin dominio: {len(unplaced)} concepto(s)"
        )
        prompt = assign_leftover_concepts_prompt(
            blocks.domains_block(placed),
            blocks.nodes_block(batch, relations, {}, definitions=definitions),
        )
        response = inference.generate(
            model=config.KG_DOMAINS_LEFTOVERS_MODEL,
            prompt=prompt,
            think=config.THINK_KG_DOMAINS_LEFTOVERS,
            format=None if config.THINK_KG_DOMAINS_LEFTOVERS else DOMAINS_SCHEMA,
            temperature=inference.judgement_temperature(config.THINK_KG_DOMAINS_LEFTOVERS),
        ).response
        raw = (
            parsing.parse_object(
                response,
                f"[domains · leftovers {idx}/{len(batches)}] ",
                DOMAINS_SCHEMA,
                max_attempts,
            )
            or {}
        )
        for domain, members in (raw.get("domains") or {}).items():
            if domain not in placed or not isinstance(members, list):
                continue
            for concept in members:
                if concept in unplaced:
                    placed[domain].append(concept)
                    unplaced.discard(concept)

    return [c for c in pending if c in unplaced]


# LINKING -------------------------------------------------------------------------------------


# The order the material introduces things in is the oldest signal in prerequisite
# learning (RefD and its successors read it straight off the textbook), and it is free:
# extraction recorded where each concept was first seen. Domains are ordered by the median
# of their members and members by their own position, so when the linking prompts say
# «the list follows the material», it is true — it used to be whatever order the model
# named the domains in.
def order_domains(concepts_by_domains: dict, positions: dict[str, int]) -> dict:
    def median(members: list[str]) -> float:
        known = sorted(positions[m] for m in members if m in positions)
        if not known:
            return float("inf")
        middle = len(known) // 2
        return known[middle] if len(known) % 2 else (known[middle - 1] + known[middle]) / 2

    unclassified = config.KG_BUILDER_UNCLASSIFIED_DOMAIN
    domains = sorted(
        concepts_by_domains,
        key=lambda d: (d == unclassified, median(concepts_by_domains[d]), d),
    )
    return {d: blocks.ordered(concepts_by_domains[d], positions) for d in domains}


# One question over the whole inventory produced 10 prerequisite edges for 199 concepts:
# ordering a syllabus is not something a model does in one turn over a flat list. Asked
# per domain — a dozen concepts at a time, with the relations already known as evidence —
# and then once for what crosses domains, it is a question that can actually be answered.
def link_relations(
    concepts_by_domains: dict,
    relations: list[list],
    definitions: dict[str, str] | None = None,
    *,
    schema,
    max_attempts: int,
) -> list[list]:
    domains = list(concepts_by_domains)
    if not domains:
        return relations

    progress.phase("link", f"{len(domains)} dominio(s)")
    known = {tuple(r) for r in relations}
    before = len(known)
    total = len(domains) + 1

    with progress.step(
        "kg_link", "Enlazando conceptos y ordenando el temario", total
    ) as reporter:
        for idx, domain in enumerate(domains, 1):
            progress.checkpoint()
            members = concepts_by_domains[domain]
            reporter.tick(idx, detail=f"{domain} · {len(members)} concepto(s)")
            progress.advance((idx - 1) / total, f"{domain} ({idx}/{len(domains)})")
            known.update(
                tuple(r)
                for r in link_domain(
                    domain,
                    members,
                    relations,
                    definitions,
                    schema=schema,
                    max_attempts=max_attempts,
                )
            )

        progress.checkpoint()
        reporter.tick(total, detail="relaciones entre dominios")
        progress.advance((total - 1) / total, "relaciones entre dominios")
        known.update(
            tuple(r)
            for r in link_cross_domain(
                concepts_by_domains, definitions, schema=schema, max_attempts=max_attempts
            )
        )

    logger.info(f"El enlazado añadió {len(known) - before} relación(es)")
    progress.advance(1.0, f"{len(known) - before} relación(es) nuevas")
    return sorted(list(r) for r in known)


def link_domain(
    domain: str,
    members: list[str],
    relations: list[list],
    definitions: dict[str, str] | None = None,
    *,
    schema,
    max_attempts: int,
) -> list[list]:
    if len(members) < 2:
        return []
    prompt = link_domain_relations_prompt(
        domain, blocks.nodes_block(members, relations, {}, definitions=definitions), schema
    )
    response = inference.generate(
        model=config.KG_LINK_DOMAIN_MODEL,
        prompt=prompt,
        think=config.THINK_KG_LINK_DOMAIN,
        temperature=inference.judgement_temperature(config.THINK_KG_LINK_DOMAIN),
    ).response
    raw = parsing.parse_object(response, f"[link · {domain}] ", LINK_SCHEMA, max_attempts)
    if raw is None:
        return []
    return parsing.valid_relations(raw.get("relations", []), schema, allowed=set(members))


def link_cross_domain(
    concepts_by_domains: dict,
    definitions: dict[str, str] | None = None,
    *,
    schema,
    max_attempts: int,
) -> list[list]:
    if len(concepts_by_domains) < 2:
        return []
    prompt = link_cross_domain_relations_prompt(
        blocks.domains_block(concepts_by_domains, definitions), schema
    )
    response = inference.generate(
        model=config.KG_LINK_CROSS_DOMAIN_MODEL,
        prompt=prompt,
        think=config.THINK_KG_LINK_CROSS_DOMAIN,
        temperature=inference.judgement_temperature(config.THINK_KG_LINK_CROSS_DOMAIN),
    ).response
    raw = parsing.parse_object(response, "[link · global] ", LINK_SCHEMA, max_attempts)
    if raw is None:
        return []

    domain_of = {c: d for d, members in concepts_by_domains.items() for c in members}
    proposed = parsing.valid_relations(
        raw.get("relations", []), schema, allowed=set(domain_of)
    )
    crossing = [r for r in proposed if domain_of[r[0]] != domain_of[r[2]]]
    if len(crossing) < len(proposed):
        logger.debug(
            f"Entre dominios: descartadas {len(proposed) - len(crossing)} relación(es) "
            "que no cruzaban ningún dominio"
        )
    return crossing


# TYPING AND CYCLES ---------------------------------------------------------------------------


def build_typed_relations(relations: list[list], universe: set, schema) -> list[dict]:
    buckets = {relation.key: defaultdict(list) for relation in schema}
    for source, key, target in relations:
        if source not in universe or target not in universe:
            continue
        if key not in schema:
            key = schema.fallback
            if key is None:
                continue
        if target not in buckets[key][source]:
            buckets[key][source].append(target)

    typed = []
    for relation in schema:
        data = buckets[relation.key]
        if not data:
            continue
        relations_data = {source: sorted(data[source]) for source in sorted(data)}
        typed.append({"details": relation.details(), "relations_data": relations_data})
    return typed


# A prerequisite edge `A → B` reads «B before A», so B should be introduced before A in
# the material. Counting the edges that say otherwise measures the draft against the one
# witness that is not a model; it is reported, never acted on — the cross-domain prompt is
# right that the order is evidence and not a verdict, and a textbook may well present a
# consequence before its foundation.
def report_against_order(typed: list[dict], positions: dict, prerequisite: str | None) -> None:
    if not positions or prerequisite is None:
        return
    group = next((g for g in typed if g["details"]["verbose"] == prerequisite), None)
    if group is None:
        return
    edges = [(s, t) for s, ts in group["relations_data"].items() for t in ts]
    judged = [(s, t) for s, t in edges if s in positions and t in positions]
    backwards = [(s, t) for s, t in judged if positions[t] > positions[s]]
    logger.info(
        f"Orden del material: {len(backwards)} de {len(judged)} arista(s) de "
        f"«{prerequisite}» apuntan a un concepto que el material introduce más tarde"
    )


# Every cycle in a `directed`+`acyclic` relation loses one edge, so the loader's cycle
# check passes. For the prerequisite relation the edge that goes is the one that most
# contradicts the order of the material — the one whose target is introduced furthest
# AFTER its source — because that is the one most likely to have been written backwards.
# Where no position is known, or for any other acyclic relation, it is the DFS back edge,
# as before, and the direction of what survives is still not corrected: that stays manual.
def break_cycles(
    typed: list[dict], positions: dict | None = None, prerequisite: str | None = None
) -> list[dict]:
    positions = positions or {}
    for group in typed:
        details = group["details"]
        if not (details.get("acyclic") and details.get("directed")):
            continue
        ordered = bool(positions) and details["verbose"] == prerequisite
        graph = nx.DiGraph()
        for source, targets in group["relations_data"].items():
            graph.add_edges_from((source, target) for target in targets)
        removed = []
        while not nx.is_directed_acyclic_graph(graph):
            cycle = [edge[:2] for edge in nx.find_cycle(graph)]
            source, target = most_backwards(cycle, positions) if ordered else cycle[-1]
            graph.remove_edge(source, target)
            removed.append((source, target))
        if not removed:
            continue
        rebuilt = defaultdict(list)
        for source, target in graph.edges():
            rebuilt[source].append(target)
        group["relations_data"] = {s: sorted(rebuilt[s]) for s in sorted(rebuilt)}
        logger.warning(
            f"Rotas {len(removed)} arista(s) de retroceso en «{details['verbose']}»: {removed}"
        )
    return typed


def most_backwards(cycle: list[tuple[str, str]], positions: dict) -> tuple[str, str]:
    def lag(edge: tuple[str, str]) -> float:
        source, target = edge
        if source not in positions or target not in positions:
            return float("-inf")
        return positions[target] - positions[source]

    return max(cycle, key=lag)
