"""Every per-instance path, derived from one root."""

from dataclasses import dataclass
from pathlib import Path

INSTANCE_DIRNAME = "instance"
CACHE_DIRNAME = "cache"
RAW_DIRNAME = "raw"


@dataclass(frozen=True)
class Workspace:
    """One instance's tree: where its artifacts, its cache and its host state live.

    It imports nothing from the package, which is what lets `config` import it.

    `slug` carries no default. An unnamed workspace would mean one particular instance,
    and a workspace always belongs to somebody, so its name is asked for and never
    assumed. The raw directory is not configurable for the same reason: every instance
    names it `raw`, and a setting there is one more way for two workspaces to disagree
    about where a corpus lives.
    """

    root: Path
    slug: str

    def __post_init__(self) -> None:
        """Resolve `root` once, so every path derived from it is absolute."""
        object.__setattr__(self, "root", Path(self.root).resolve())

    # DIRECTORIES -------------------------------------------------------------------------

    @property
    def instance_dir(self) -> Path:
        """The instance definition: the artifacts and the host state beside them."""
        return self.root / INSTANCE_DIRNAME

    @property
    def cache_dir(self) -> Path:
        """Everything regenerable, safe to delete at the cost of a rebuild."""
        return self.root / CACHE_DIRNAME

    @property
    def raw_dir(self) -> Path:
        """The documents this instance was authored from."""
        return self.root / RAW_DIRNAME

    @property
    def raw_corpus_dir(self) -> Path:
        """The theory corpus the knowledge graph is extracted from."""
        return self.raw_dir / "raw_corpus"

    @property
    def raw_exemplars_dir(self) -> Path:
        """The documents the exemplars profile and bank are built from."""
        return self.raw_dir / "raw_exemplars_bank"

    # WHAT THIS INSTANCE DECLARES ABOUT ITSELF --------------------------------------------

    @property
    def locale_path(self) -> Path:
        """The language its prompts are written in.

        The one thing about a workspace that has to be readable BEFORE anything is built,
        since it is what the builders' own instructions are written in — so it cannot live
        in `content_context.json`, which a build produces. Undotted because it is not host
        state: it travels with `export-instance`, and a workspace handed to somebody else
        is unreadable without it. Absent means `es`.
        """
        return self.instance_dir / "locale.json"

    # INSTANCE ARTIFACTS ------------------------------------------------------------------

    @property
    def kg_path(self) -> Path:
        """The curated knowledge graph."""
        return self.instance_dir / "knowledge_graph.json"

    @property
    def kg_autogenerated_path(self) -> Path:
        """The graph builder's draft, which the curated file wins over."""
        return self.instance_dir / "knowledge_graph_autogenerated.json"

    @property
    def exemplars_bank_path(self) -> Path:
        """The example items, with the tagger's concepts once they are tagged."""
        return self.instance_dir / "exemplars_bank.json"

    @property
    def exemplars_profile_path(self) -> Path:
        """The content schema this instance sets its items to."""
        return self.instance_dir / "exemplars_profile.json"

    @property
    def exemplars_profile_autogenerated_path(self) -> Path:
        """The profile builder's draft, which the curated file wins over."""
        return self.instance_dir / "exemplars_profile_autogenerated.json"

    @property
    def content_context_path(self) -> Path:
        """What subject this instance is about, in prose.

        An instance artifact and not host state, even with no `raw/` and no builder of its
        own: the OTHER two builders synthesise it at the end of their work, each with what
        its artifact knows about the subject. It has the draft/curated pair the graph and
        the profile have, and the curated one wins — which is what stops every rebuild
        rewriting a person's text once more.
        """
        return self.instance_dir / "content_context.json"

    @property
    def content_context_autogenerated_path(self) -> Path:
        """The latest synthesis of the context, which the curated file wins over."""
        return self.instance_dir / "content_context_autogenerated.json"

    # REGENERABLE DERIVATIONS -------------------------------------------------------------

    @property
    def markdown_cache_dir(self) -> Path:
        """The raw documents as markdown, per document."""
        return self.cache_dir / "markdown"

    @property
    def concept_descriptions_path(self) -> Path:
        """The LLM-written description of each concept, which is what gets embedded."""
        return self.cache_dir / "concept_descriptions.json"

    @property
    def concept_sources_path(self) -> Path:
        """Which piece of the theory corpus each concept came from.

        A derivation of the corpus and not part of the artifact: the curated graph is
        edited by hand and must not swell with hundreds of KB of quotations. Rewritten
        whole on every graph build; without it the descriptions are composed from the
        relations alone.
        """
        return self.cache_dir / "concept_sources.json"

    @property
    def concepts_embeddings_path(self) -> Path:
        """The concepts index, fingerprinted so a model or corpus change invalidates it."""
        return self.cache_dir / "embeddings" / "concepts_embeddings.npz"

    @property
    def exemplars_bank_embeddings_path(self) -> Path:
        """The exemplars bank index, cached per item text."""
        return self.cache_dir / "embeddings" / "exemplars_bank_embeddings.npz"

    # HOST STATE --------------------------------------------------------------------------

    @property
    def history_dir(self) -> Path:
        """The snapshots that make emptying a stage undoable."""
        return self.instance_dir / ".history"

    @property
    def runs_dir(self) -> Path:
        """The event log of each job run against this instance."""
        return self.instance_dir / ".runs"

    @property
    def review_state_path(self) -> Path:
        """Which artifacts are approved, and the hashes that decide whether they are stale."""
        return self.instance_dir / ".review_state.json"

    @property
    def curriculum_path(self) -> Path:
        """The concepts this instance considers covered.

        Host state, not an artifact: no builder produces it, it does not come from `raw/`,
        and it is not part of the instance definition. It is a teaching decision about the
        workspace, like `.review_state.json`.
        """
        return self.instance_dir / ".curriculum.json"
