"""Phase 1 — load the instance, warm the indices, hand back a `PipelineContext`.

Read-only by default: `initialize(tag=True)` is the only phase-1 write to `instance/`.
Initialize once per process and generate many times — building the embedder writes every
missing concept description and indexes the graph, which is minutes.
"""

import json
from dataclasses import dataclass
from functools import partial
from pathlib import Path

from loguru import logger

from .. import config
from ..concept_tagger import ConceptTagger
from ..core import progress
from ..core.workspace import Workspace
from ..embedder import Embedder
from ..instance import locale
from ..instance.content_context import ContentContext
from .. import prompts as prompts_pkg
from ..instance.exemplars_profile import ExemplarsProfile
from ..instance.knowledge_graph import KnowledgeGraph
from ..variatio import VariantGenerator
from . import _artifacts


def _embed_text(exemplars_profile: ExemplarsProfile):
    """Bind the profile's renderer to the per-field budget everything indexes under."""
    return partial(
        exemplars_profile.embed_text, field_max_chars=config.EMBEDDING_FIELD_MAX_CHARS
    )


def make_embedder(
    ws: Workspace,
    exemplars_profile: ExemplarsProfile,
    knowledge_graph: KnowledgeGraph,
    content_context: ContentContext | None = None,
) -> Embedder:
    """Build the index for a workspace.

    Apart from `initialize` because the bank build needs it too and cannot call that: the
    bank `initialize` requires is precisely the one being written.
    """
    return Embedder(
        knowledge_graph,
        config.EMBEDDING_LLM,
        prompts=prompts_pkg.of(locale.prompt_language(ws)),
        embed_text=_embed_text(exemplars_profile),
        embed_signature=exemplars_profile.embed_signature,
        context=content_context or _artifacts.load_content_context(ws),
        descriptions_path=ws.concept_descriptions_path,
        concept_sources_path=ws.concept_sources_path,
        concepts_cache_path=ws.concepts_embeddings_path,
        exemplars_bank_cache_path=ws.exemplars_bank_embeddings_path,
    )


def make_tagger(
    ws: Workspace,
    embedder: Embedder,
    exemplars_profile: ExemplarsProfile,
    content_context: ContentContext | None = None,
) -> ConceptTagger:
    """Build the tagger over an existing index, for the same reason as `make_embedder`."""
    return ConceptTagger(
        embedder,
        config.CONCEPT_TAGGER_LLM,
        prompts=prompts_pkg.of(locale.prompt_language(ws)),
        embed_text=_embed_text(exemplars_profile),
        primary_text=exemplars_profile.primary_text,
        context=content_context if content_context is not None else ContentContext(),
    )


@dataclass
class PipelineContext:
    """Everything a run needs, loaded once: the artifacts, the index and the generator."""

    exemplars_profile: ExemplarsProfile
    content_context: ContentContext
    knowledge_graph: KnowledgeGraph
    embedder: Embedder
    exemplars_bank: dict
    tagger: ConceptTagger
    generator: VariantGenerator
    exemplars_profile_path: Path
    knowledge_graph_path: Path
    workspace: Workspace
    prompts: object
    language: str

    def apply_bank(self, bank: dict) -> None:
        """Adopt a new bank everywhere at once.

        The bank is the one artifact that changes while the context is alive (tagging,
        manual edits), and swapping it means re-embedding and re-merging the index; doing
        it here keeps embedder and generator from drifting apart.
        """
        self.exemplars_bank = bank
        self.embedder.enrich_index_with_content(bank)
        self.generator.exemplars_bank = bank


def _resolve_content_context(
    ws: Workspace, exemplars_profile: ExemplarsProfile, profile_path: Path
) -> ContentContext:
    """Load the subject context, falling back to the one an old profile still carries.

    That fallback is read HERE and nowhere else: the graph's own path must not learn to
    load a profile again.
    """
    content_context = _artifacts.load_content_context(ws)
    context_path = _artifacts.content_context_path(ws)

    if context_path is None and exemplars_profile.legacy_content_context:
        content_context = ContentContext.from_legacy(
            exemplars_profile.legacy_content_context
        )
        logger.warning(
            f"Context still inside the profile ({profile_path.name}); used as it is. "
            f"Move it to {ws.content_context_path.name} so the builders can "
            "synthesise it"
        )
    elif context_path is None:
        logger.warning(
            "No subject context: no prompt will know the subject, the level or the "
            "language; the next graph or profile build synthesises it"
        )
    else:
        if context_path == ws.content_context_autogenerated_path:
            logger.warning(
                f"Uncurated context: {context_path.name}; curate it by hand in "
                f"{ws.content_context_path.name} so it stops being rewritten on every build"
            )
        logger.info(
            f"Context ({context_path.name}): "
            f"«{content_context.subject or 'subject not declared'}»"
        )
    return content_context


def _check_bank_against_profile(
    bank: dict, exemplars_profile: ExemplarsProfile, profile_path: Path
) -> None:
    """Raise on a bank the profile cannot place; warn on items over the embedding budget.

    Everything downstream resolves each item against the type it declares, so one aggregated
    error here names the artifact that has to be rebuilt instead of failing deep inside the
    embedding loop.
    """
    unplaceable = exemplars_profile.unplaceable_items(bank)
    if unplaceable:
        sample = list(unplaceable.items())[:5]
        raise ValueError(
            f"{len(unplaceable)} bank item(s) do not match the exemplars profile "
            f"({profile_path.name}); the bank was built against a different one and "
            f"has to be rebuilt. First: "
            + "; ".join(f"{item_id}: {reason}" for item_id, reason in sample)
        )
    oversized = exemplars_profile.oversized_embed_items(
        bank, config.EMBEDDING_MAX_CHARS, config.EMBEDDING_FIELD_MAX_CHARS
    )
    if oversized:
        worst = sorted(oversized.items(), key=lambda pair: -pair[1])[:5]
        logger.warning(
            f"{len(oversized)} bank item(s) exceed the {config.EMBEDDING_MAX_CHARS:,} "
            "character budget and may be truncated when indexed: "
            + ", ".join(f"{item_id} ({size:,})" for item_id, size in worst)
        )


def initialize(ws: Workspace, tag: bool = False) -> PipelineContext:
    """Load the instance and warm the indices.

    Read-only by default: tagging is a separate, explicit act (`stages.tag_bank`)
    because it rewrites the exemplars bank. `tag=True` restores the old all-in-one
    behaviour the CLI relies on.
    """
    profile_path = _artifacts.exemplars_profile_path(ws)
    if profile_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_PROFILE)
    if profile_path == ws.exemplars_profile_autogenerated_path:
        logger.warning(f"Uncurated exemplars profile: {profile_path.name}")

    kg_path = _artifacts.knowledge_graph_path(ws)
    if kg_path is None:
        raise _artifacts.MissingArtifactError(_artifacts.KNOWLEDGE_GRAPH)
    if kg_path == ws.kg_autogenerated_path:
        logger.warning(f"Uncurated graph: {kg_path.name}; curate it by hand in {ws.kg_path.name}")

    with progress.step("load_instance", "Loading the instance (profile, graph and bank)"):
        if ws.exemplars_bank_path.is_file():
            with open(ws.exemplars_bank_path, encoding="utf-8") as f:
                bank = json.load(f)
        else:
            raise _artifacts.MissingArtifactError(_artifacts.EXEMPLARS_BANK)

        exemplars_profile = ExemplarsProfile(profile_path)
        knowledge_graph = KnowledgeGraph(kg_path)
        content_context = _resolve_content_context(ws, exemplars_profile, profile_path)

        logger.info(
            f"Profile ({profile_path.name}): {len(exemplars_profile.item_types)} item type(s) — "
            + ", ".join(exemplars_profile.item_types)
        )

        _check_bank_against_profile(bank, exemplars_profile, profile_path)

        logger.info(
            f"Graph ({kg_path.name}): {len(knowledge_graph.all_concepts)} concept(s), "
            f"{len(knowledge_graph.taggable_concepts)} taggable, "
            f"{len(knowledge_graph.relation_details)} relation type(s)"
        )
        # The single door every entry point goes through, so this is where the one warning
        # about an unreviewed graph is spent. An exclusion list IS a review, so a graph
        # written before the flag existed does not earn it.
        nothing_excluded = not knowledge_graph.generic_non_taggable_concepts
        if not knowledge_graph.taggability_reviewed and nothing_excluded:
            logger.warning(
                f"Graph ({kg_path.name}): taggability not reviewed; the "
                f"{len(knowledge_graph.all_concepts)} concept(s) are treated as "
                "taggable, including the ones that identify nothing"
            )
        logger.info(
            f"Bank: {len(bank)} item(s), "
            f"{sum(1 for item in bank.values() if item.get('concepts'))} already tagged"
        )

    language = locale.prompt_language(ws)
    embedder = make_embedder(ws, exemplars_profile, knowledge_graph, content_context)
    tagger = make_tagger(ws, embedder, exemplars_profile, content_context)
    generator = VariantGenerator(
        knowledge_graph=knowledge_graph,
        exemplars_bank=bank,
        embedder=embedder,
        exemplars_profile=exemplars_profile,
        content_context=content_context,
        generator_model=config.VARIANT_GENERATION_LLM,
        prompts=prompts_pkg.of(language),
        prerequisite_relation=locale.prerequisite_relation(ws),
        tagger=tagger,
    )

    context = PipelineContext(
        exemplars_profile=exemplars_profile,
        content_context=content_context,
        knowledge_graph=knowledge_graph,
        embedder=embedder,
        exemplars_bank=bank,
        tagger=tagger,
        generator=generator,
        exemplars_profile_path=profile_path,
        knowledge_graph_path=kg_path,
        workspace=ws,
        prompts=prompts_pkg.of(language),
        language=language,
    )

    # Tagging BEFORE enriching the index is the cross-run warm start: the merged index this
    # run builds is what the next one consumes. Changing the order changes tagging quality.
    if tag:
        from .tag import tag_bank

        tag_bank(context)
    else:
        embedder.enrich_index_with_content(bank)

    return context
