import json
from pathlib import Path

from ..core.json_io import write_json
from ..core.workspace import Workspace

CANONICAL_KEYS = ("subject", "educational_level", "language_of_instruction")

NARRATIVE_KEY = "narrative"


class ContentContext:
    def __init__(self, raw: dict | None = None):
        raw = dict(raw or {})
        self.narrative: str = str(raw.pop(NARRATIVE_KEY, "") or "").strip()
        self.facts: dict[str, str] = {
            key: str(value).strip()
            for key, value in raw.items()
            if isinstance(value, (str, int, float)) and str(value).strip()
        }

    @classmethod
    def load(cls, path: str | Path | None) -> "ContentContext":
        if path is None:
            return cls()
        path = Path(path)
        if not path.is_file():
            return cls()
        try:
            with path.open(encoding="utf-8") as f:
                return cls(json.load(f))
        except (json.JSONDecodeError, OSError):
            return cls()

    # The flat key->value dict that used to live under the profile's `content_context`.
    # It converts with no loss and no model call: every key stays a fact, and a workspace
    # that has not been through a build yet reads exactly as it did before.
    @classmethod
    def from_legacy(cls, flat: dict) -> "ContentContext":
        return cls(flat)

    def save(self, path: str | Path) -> None:
        write_json(path, self.as_dict())

    def as_dict(self) -> dict:
        data: dict[str, str] = {}
        if self.narrative:
            data[NARRATIVE_KEY] = self.narrative
        data.update(self.facts)
        return data

    # The three the naive arm of the evaluation composes its sentence from. It cannot use
    # the prose -- it builds "Eres experto en X, a nivel de Y. Redáctalo en Z" -- so these
    # stay addressable by name however well written the narrative is.
    @property
    def subject(self) -> str:
        return self.facts.get("subject", "")

    @property
    def educational_level(self) -> str:
        return self.facts.get("educational_level", "")

    @property
    def language_of_instruction(self) -> str:
        return self.facts.get("language_of_instruction", "")

    # What every prompt interpolates, and the only renderer of it in the project. There
    # used to be five copies of the `- key: value` join, one per prompt, which is why the
    # dict could never become prose: the shape was decided five times.
    #
    # The listing survives as the fallback and is byte-identical to those five, because a
    # workspace whose context has not been synthesised yet must read as it always did.
    def prompt_block(self) -> str:
        if self.narrative:
            return self.narrative
        return "\n".join(f"- {key}: {value}" for key, value in self.facts.items())

    def __bool__(self) -> bool:
        return bool(self.narrative or self.facts)


# Curated over draft, the same rule the graph and the profile follow. It lives HERE and not
# in `stages/_artifacts` -- which re-exports it -- because the builders synthesise the
# context and a builder may not import a stage: `stages/build.py` imports the builders, so
# the other direction closes the cycle.
def resolve_path(ws: Workspace) -> Path | None:
    if ws.content_context_path.is_file():
        return ws.content_context_path
    if ws.content_context_autogenerated_path.is_file():
        return ws.content_context_autogenerated_path
    return None


def load_for(ws: Workspace) -> ContentContext:
    return ContentContext.load(resolve_path(ws))
