import json
import re
from pathlib import Path

import ollama
from docling.document_converter import DocumentConverter, InputFormat
from json_repair import repair_json
from loguru import logger

from system import config
from system.content_profile import ContentProfile
from system.prompts import infer_content_profile_prompt, json_repair_prompt


class ContentProfileBuilder:
    SUPPORTED_EXTS = (".pdf", ".docx", ".md", ".txt")
    CODE_FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
    SEPARATOR_RE = re.compile(r"^\s*---\s*$", re.MULTILINE)

    def __init__(
        self,
        model: str = config.CONTENT_PROFILE_BUILDER_LLM,
        verbose: bool = True,
    ):
        self.model = model
        self.budget = config.SCHEMA_INFERENCE_BUDGET
        self.max_repair_attempts = config.MAX_JSON_REPAIR_TRIES

        logger.enable(__name__) if verbose else logger.disable(__name__)

        self._docling = DocumentConverter(allowed_formats=[InputFormat.PDF, InputFormat.DOCX])

    # PUBLIC API ----------------------------------------------------------------------------------

    def build(self, input_dir: str, output_file_path: str) -> dict:
        input_path = Path(input_dir)
        files = sorted(
            p
            for p in input_path.iterdir()
            if p.is_file() and p.suffix.lower() in self.SUPPORTED_EXTS
        )
        if not files:
            logger.error(f"No supported files found in: {input_dir}")
            return {}

        logger.info(f"Found {len(files)} file(s) - inferring content profile")
        sample = self._gather_sample(files)
        if not sample.strip():
            logger.error("No content extracted from any file")
            return {}

        profile = self._infer(sample)
        if not profile:
            logger.error("Could not produce a content profile draft")
            return {}

        self._save(profile, output_file_path)
        try:
            ContentProfile(output_file_path)
            logger.success(f"Autogenerated content profile → {output_file_path} (loads cleanly)")
        except Exception as e:
            logger.warning(
                f"Autogenerated content profile → {output_file_path} — "
                f"needs manual fixes before it loads: {e}"
            )
        return profile

    # SAMPLING ------------------------------------------------------------------------------------

    # Schema variety comes from breadth (every document's shape), not volume: use the whole
    # corpus when it fits the budget, otherwise take leading whole blocks from each document so
    # all are represented and no item is truncated mid-way.
    def _gather_sample(self, files: list[Path]) -> str:
        per_doc: list[tuple[str, list[str]]] = []
        for file_path in files:
            try:
                content = self._to_markdown(file_path)
            except Exception as e:
                logger.exception(f"[{file_path.name}] skipped: {e}")
                continue
            blocks = self._split_blocks(content)
            if blocks:
                per_doc.append((file_path.stem, blocks))

        if not per_doc:
            return ""

        total = sum(len(b) for _, blocks in per_doc for b in blocks)
        if total <= self.budget:
            logger.info(
                f"Corpus fits budget ({total:,} ≤ {self.budget:,} chars) - using all content"
            )
            chosen = per_doc
        else:
            share = max(1, self.budget // len(per_doc))
            logger.info(
                f"Corpus exceeds budget ({total:,} > {self.budget:,} chars) - "
                f"sampling ~{share:,} chars from each of {len(per_doc)} document(s)"
            )
            chosen = [(name, self._head_blocks(blocks, share)) for name, blocks in per_doc]

        sections = [
            f"===== DOCUMENTO: {name} =====\n\n" + "\n\n---\n\n".join(blocks)
            for name, blocks in chosen
        ]
        return "\n\n".join(sections)

    @staticmethod
    def _head_blocks(blocks: list[str], share: int) -> list[str]:
        picked, size = [], 0
        for b in blocks:
            if picked and size + len(b) > share:
                break
            picked.append(b)
            size += len(b)
        return picked

    # INFERENCE -----------------------------------------------------------------------------------

    def _infer(self, sample: str) -> dict:
        prompt = infer_content_profile_prompt(sample)
        response = ollama.generate(model=self.model, think=False, prompt=prompt).response
        profile = self._parse(response)
        err = self._validate(profile)

        for attempt in range(1, self.max_repair_attempts + 1):
            if err is None:
                break
            logger.warning(f"repair {attempt}/{self.max_repair_attempts}: {err}")
            repair_prompt = json_repair_prompt(
                broken_output=response, error_msg=err, shape="objeto"
            )
            response = ollama.generate(model=config.REPAIR_LLM, prompt=repair_prompt).response
            candidate = self._parse(response)
            if candidate is not None:
                profile = candidate
            err = self._validate(profile)

        if profile is None:
            return {}
        if err is not None:
            logger.warning(f"Profile still invalid after repairs — saving draft anyway: {err}")
        return profile

    @classmethod
    def _parse(cls, response: str) -> dict | None:
        cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", response.strip())
        raw = repair_json(cleaned, return_objects=True)
        return raw if isinstance(raw, dict) and raw else None

    @staticmethod
    def _validate(profile: dict | None) -> str | None:
        if profile is None:
            return "top-level JSON is not an object"
        try:
            ContentProfile._validate(profile)
            for spec in profile["fields"].values():
                ContentProfile._spec_to_field(spec)
            return None
        except (ValueError, KeyError, TypeError) as e:
            return f"{type(e).__name__}: {str(e)[:200]}"

    # HELPERS -------------------------------------------------------------------------------------

    def _to_markdown(self, input_path: Path) -> str:
        suffix = input_path.suffix.lower()
        if suffix in (".md", ".txt"):
            return input_path.read_text(encoding="utf-8")
        if suffix in (".pdf", ".docx"):
            return self._docling.convert(str(input_path)).document.export_to_markdown()
        raise ValueError(f"Unsupported file extension: {suffix}")

    def _split_blocks(self, text: str) -> list[str]:
        fences: list[str] = []

        def _stash(m):
            fences.append(m.group(0))
            return f"§§FENCE{len(fences) - 1}§§"

        masked = self.CODE_FENCE_RE.sub(_stash, text)
        pieces = (
            self.SEPARATOR_RE.split(masked)
            if self.SEPARATOR_RE.search(masked)
            else re.split(r"\n\s*\n", masked)
        )

        def _restore(p: str) -> str:
            return re.sub(r"§§FENCE(\d+)§§", lambda m: fences[int(m.group(1))], p).strip()

        return [r for r in (_restore(p) for p in pieces) if r]

    @staticmethod
    def _save(profile: dict, output_file_path: str) -> None:
        output_path = Path(output_file_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as f:
            json.dump(profile, f, ensure_ascii=False, indent=2)
