import json
import os
from pathlib import Path

import pytest

from variatio import config

pytestmark = pytest.mark.corpus

# WHICH INSTANCE IS MEASURED. `workspaces/` is gitignored in full, so a checkout has
# whatever its owner built under whatever they called it; the reference slug stays the
# default and the variable is the way to point these at a real one — the same variable the
# `model`-marked measurements read.
WORKSPACE = os.environ.get("VARIATIO_MODEL_WORKSPACE", "default")
ROOT = Path("workspaces") / WORKSPACE
SOURCES = ROOT / "cache" / "concept_sources.json"
DRAFT = ROOT / "instance" / "knowledge_graph_autogenerated.json"
CURATED = ROOT / "instance" / "knowledge_graph.json"

MIN_UNITS = 3
MAX_UNITS = 12
MAX_UNCLASSIFIED_SHARE = 0.05


def sources() -> dict:
    if not SOURCES.exists():
        pytest.skip(f"no hay {SOURCES}; reconstruye el grafo para medir el temario")
    with SOURCES.open(encoding="utf-8") as f:
        return json.load(f)


# The DRAFT and not the curated graph: `concept_sources.json` and the draft are the two
# files one build writes, so they are the pair that is consistent with each other. The
# curated one may be older by any number of hand edits.
def graph() -> dict:
    path = DRAFT if DRAFT.exists() else CURATED
    if not path.exists():
        pytest.skip(f"no hay {path}; reconstruye el grafo para medir el temario")
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def test_the_build_recorded_a_syllabus_at_all():
    stored = sources()
    assert stored.get("outline"), (
        "El caché no tiene «outline»: lo escribió un build anterior a la segmentación "
        "del temario. Reconstruye el grafo."
    )
    assert stored.get("units"), (
        "Hay índice pero no unidades: la segmentación cayó al camino anterior. Busca en "
        "el registro del build el aviso «El modelo no segmentó el temario»."
    )


def test_the_number_of_units_is_a_syllabus_and_not_a_table_of_contents():
    units = sources()["units"]
    assert MIN_UNITS <= len(units) <= MAX_UNITS, [u["name"] for u in units]


def test_no_unit_of_the_graph_ends_up_empty():
    empty = [d for d, members in graph()["concepts_by_domains"].items() if not members]
    assert empty == []


def test_the_catch_all_stays_marginal():
    by_domain = graph()["concepts_by_domains"]
    total = sum(len(members) for members in by_domain.values())
    leftovers = len(by_domain.get(config.KG_BUILDER_UNCLASSIFIED_DOMAIN, []))
    assert total > 0
    assert leftovers / total <= MAX_UNCLASSIFIED_SHARE, f"{leftovers} de {total}"
