"""The one home of the path → (kind, stage) table.

`instance_io` reads it to import and export a workspace, and `mirror` to decide which
artifact a file that was just written belongs to. A second copy is how the two would come
to disagree about what a directory holds.
"""

from pathlib import Path

from variatio import entrypoints
from variatio.core.workspace import Workspace as FsWorkspace

from .models import CURATED, DRAFT

KINDS = (entrypoints.KNOWLEDGE_GRAPH, entrypoints.EXEMPLARS_PROFILE, entrypoints.EXEMPLARS_BANK)


def locate(ws: FsWorkspace, path: Path) -> tuple[str, str] | None:
    """Return the (kind, stage) this path is, or None when it is not one of the artifacts."""
    target = Path(path).resolve()
    for kind, stage_paths in artifact_paths(ws).items():
        for stage, candidate in stage_paths.items():
            if candidate.resolve() == target:
                return kind, stage
    return None


def artifact_paths(ws: FsWorkspace) -> dict[str, dict[str, Path]]:
    """Return every artifact file of this workspace, by kind and then by stage."""
    return {
        entrypoints.KNOWLEDGE_GRAPH: {CURATED: ws.kg_path, DRAFT: ws.kg_autogenerated_path},
        entrypoints.EXEMPLARS_PROFILE: {
            CURATED: ws.exemplars_profile_path,
            DRAFT: ws.exemplars_profile_autogenerated_path,
        },
        entrypoints.EXEMPLARS_BANK: {CURATED: ws.exemplars_bank_path},
    }
