import { useMutation } from "@tanstack/react-query";
import {
  ArrowRight,
  ChevronRight,
  CircleCheck,
  CircleDashed,
  Cpu,
  Hammer,
  Lock,
  Pencil,
  Server,
  TriangleAlert,
  UploadCloud,
} from "lucide-react";
import { useState } from "react";

import { RawImport } from "@/components/RawImport";
import { StageBadge } from "@/components/StageGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { InfoHint } from "@/components/ui/hint";
import { Alert, Separator, Skeleton, Spinner } from "@/components/ui/misc";
import { api } from "@/lib/api";
import { JOB_EXPLAIN } from "@/lib/explain";
import { ENGINE_LABEL, bytes, duration, when } from "@/lib/format";
import { Link, useRouter } from "@/lib/router";
import type { StageState } from "@/lib/types";
import { cn } from "@/lib/utils";
import {
  useHealth,
  useInvalidateChain,
  usePipeline,
  useRaw,
  useSubmitJob,
} from "@/state/queries";

const SCREEN: Record<string, string> = {
  content_profile: "/preparar/perfil",
  knowledge_graph: "/preparar/grafo",
  exemplars_bank: "/preparar/banco",
};

const EXPLAIN: Record<string, string> = {
  content_profile:
    "Define el esquema de un ítem y las guías de extracción y generación. Se infiere de una muestra de los ejemplares en bruto.",
  knowledge_graph:
    "El vocabulario de conceptos y dominios. Es la única fuente de conceptos que podrá usarse después: nada fuera de aquí puede etiquetarse ni generarse.",
  exemplars_bank:
    "Los ítems extraídos de los documentos, etiquetados con conceptos del grafo. Alimentan los ejemplos few-shot de la generación.",
};

function StageCard({
  stage,
  index,
  rawMissing,
}: {
  stage: StageState;
  index: number;
  rawMissing: string | null;
}) {
  const submit = useSubmitJob();
  const blocked = Boolean(stage.blocked_reason);
  const missing = stage.status === "missing";
  const buildable = !blocked && !rawMissing;
  const build = JOB_EXPLAIN[stage.build_job];

  return (
    <Card
      className={cn(
        "relative transition-colors",
        stage.status === "approved" && "border-[color-mix(in_oklch,var(--success)_45%,var(--border))]",
        stage.status === "stale" && "border-destructive/50",
        blocked && "opacity-70",
      )}
    >
      <CardHeader className="pb-2">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "flex size-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold",
              stage.status === "approved"
                ? "bg-[var(--success)] text-background"
                : "bg-muted text-muted-foreground",
            )}
          >
            {stage.status === "approved" ? <CircleCheck className="size-3.5" /> : index + 1}
          </span>
          <div className="flex flex-1 items-center gap-1.5">
            <CardTitle>{stage.label}</CardTitle>
            <InfoHint label={`Qué es ${stage.label}`}>{EXPLAIN[stage.artifact]}</InfoHint>
          </div>
          <StageBadge stage={stage} />
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        {stage.is_autogenerated ? (
          <p className="flex items-center gap-1.5 text-xs text-[var(--warning)]">
            <TriangleAlert className="size-3.5" />
            Borrador autogenerado, sin curar.
          </p>
        ) : null}

        {stage.stale_because.length > 0 ? (
          <div className="space-y-1 rounded-md border border-destructive/40 bg-destructive/10 p-2">
            {stage.stale_because.map((cause) => (
              <p key={cause.artifact} className="text-xs text-destructive">
                {cause.reason}
              </p>
            ))}
          </div>
        ) : null}

        {blocked ? (
          <p className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Lock className="size-3.5" />
            {stage.blocked_reason}
          </p>
        ) : null}

        {rawMissing && !blocked ? (
          <p className="flex items-center gap-1.5 text-xs text-[var(--warning)]">
            <UploadCloud className="size-3.5" />
            Faltan documentos en «{rawMissing}»: impórtalos antes de construir.
          </p>
        ) : null}

        {stage.approved_at && stage.status === "approved" ? (
          <p className="text-xs text-muted-foreground">Aprobado el {when(stage.approved_at)}</p>
        ) : null}

        <div className="flex flex-wrap gap-2 pt-1">
          {missing ? (
            <Button
              size="sm"
              disabled={!buildable || submit.isPending}
              onClick={() => submit.mutate({ kind: stage.build_job })}
            >
              <Hammer />
              Construir
            </Button>
          ) : (
            <Link to={SCREEN[stage.artifact]}>
              <Button size="sm" variant={stage.status === "approved" ? "outline" : "default"} disabled={blocked}>
                <Pencil />
                {stage.status === "approved" ? "Revisar de nuevo" : "Revisar"}
              </Button>
            </Link>
          )}
          {!missing ? (
            <Button
              size="sm"
              variant="ghost"
              disabled={!buildable || submit.isPending}
              onClick={() => submit.mutate({ kind: stage.build_job })}
              title="Vuelve a ejecutar el constructor sobre los datos en bruto"
            >
              <Hammer />
              Reconstruir
            </Button>
          ) : null}
          {build ? (
            <InfoHint label="Qué ocurre al construir" className="self-center">
              <p>{build.what}</p>
              <p className="mt-1">
                <span className="font-medium">Produce:</span> {build.produces}
              </p>
              <p className="mt-1">
                <span className="font-medium">Coste:</span> {build.cost}
              </p>
            </InfoHint>
          ) : null}
        </div>
      </CardContent>
    </Card>
  );
}

function RawSection() {
  const raw = useRaw();
  const slots = raw.data?.slots ?? [];
  const emptySlots = slots.filter((slot) => slot.files.length === 0);
  const [open, setOpen] = useState(false);
  const expanded = open || emptySlots.length > 0;
  const total = slots.reduce((sum, slot) => sum + slot.files.length, 0);
  const size = slots.reduce((sum, slot) => sum + slot.bytes, 0);

  return (
    <section className="space-y-3">
      <div className="flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => setOpen((value) => !value)}
          disabled={emptySlots.length > 0}
          className="flex items-center gap-1.5 text-sm font-medium disabled:cursor-default"
        >
          {emptySlots.length > 0 ? (
            <UploadCloud className="size-4 text-[var(--warning)]" />
          ) : (
            <ChevronRight className={cn("size-4 transition-transform", expanded && "rotate-90")} />
          )}
          Datos en bruto
        </button>
        <InfoHint label="Qué son los datos en bruto">
          Los documentos de partida. No forman parte del programa: se copian a{" "}
          <span className="font-mono">raw_data</span> y cada construcción los vuelve a leer de
          disco. Sin ellos no hay nada que construir.
        </InfoHint>
        {total > 0 ? (
          <span className="text-xs text-muted-foreground">
            {total} archivo(s) · {bytes(size)}
          </span>
        ) : null}
        {emptySlots.length > 0 ? (
          <Badge variant="warning">
            {emptySlots.map((slot) => slot.label.toLowerCase()).join(" y ")} sin archivos
          </Badge>
        ) : null}
        {!expanded ? (
          <Button size="sm" variant="ghost" onClick={() => setOpen(true)}>
            <UploadCloud />
            Importar
          </Button>
        ) : null}
      </div>

      {expanded ? <RawImport /> : null}
    </section>
  );
}

function SystemCard() {
  const health = useHealth();
  const raw = useRaw();
  const invalidate = useInvalidateChain();
  const index = useMutation({
    mutationFn: () => api.submitJob("index", {}, true),
    onSuccess: invalidate,
  });

  if (health.isLoading) return <Skeleton className="h-40" />;
  if (!health.data) {
    return (
      <Alert tone="danger" title="Sin servidor">
        <p>La API no responde en el puerto 8000.</p>
      </Alert>
    );
  }

  const { available, engine, host, models, context_ready } = health.data;
  const slots = raw.data?.slots ?? [];

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2">
          <Server className="size-4 text-muted-foreground" />
          Sistema
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        <div className="flex items-center justify-between gap-2">
          <span className="flex items-center gap-1.5 text-muted-foreground">
            Motor de inferencia
            <InfoHint label="Dónde responde el motor">
              Todo el tráfico de modelos pasa por aquí. Atiende en{" "}
              <span className="font-mono">{host}</span>; si deja de responder, los trabajos
              fallan al arrancar pero la interfaz sigue navegable.
            </InfoHint>
          </span>
          <span className="flex items-center gap-1.5" title={host}>
            <span
              className={cn(
                "size-1.5 rounded-full",
                available ? "bg-[var(--success)]" : "bg-destructive",
              )}
            />
            <span className="font-medium">{ENGINE_LABEL[engine] ?? engine}</span>
            {available ? null : (
              <span className="text-xs text-destructive">sin conexión</span>
            )}
          </span>
        </div>

        <div className="flex items-start justify-between gap-2">
          <span className="text-muted-foreground">Modelos</span>
          <div className="text-right">
            {models.missing.length === 0 ? (
              <Badge variant="success">{Object.keys(models.required).length} disponibles</Badge>
            ) : (
              <div className="space-y-1">
                {models.missing.map((model) => (
                  <Badge key={model} variant="danger" className="block">
                    falta {model}
                  </Badge>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="flex items-center justify-between gap-2">
          <span className="flex items-center gap-1.5 text-muted-foreground">
            Índices en memoria
            <InfoHint label="Qué son los índices en memoria">
              Los embeddings del grafo y del banco, cargados en RAM. En frío, el primer trabajo
              que los necesite paga la carga; calentarlos la adelanta.
            </InfoHint>
          </span>
          {context_ready ? (
            <Badge variant="success">Calientes</Badge>
          ) : (
            <div className="flex items-center gap-2">
              <Badge variant="outline">Fríos</Badge>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => index.mutate()}
                disabled={index.isPending || !available}
              >
                {index.isPending ? <Spinner /> : <Cpu />}
                Calentar
              </Button>
            </div>
          )}
        </div>

        <Separator />

        <div className="space-y-1 text-xs text-muted-foreground">
          {slots.map((slot) => (
            <p key={slot.kind} className="flex items-center gap-1.5">
              {slot.files.length > 0 ? (
                <CircleCheck className="size-3.5 shrink-0 text-[var(--success)]" />
              ) : (
                <CircleDashed className="size-3.5 shrink-0" />
              )}
              <span className="min-w-0 flex-1 truncate" title={slot.path}>
                {slot.label}
              </span>
              <span className="tabular-nums">{slot.files.length} archivo(s)</span>
            </p>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

const RAW_FOR: Record<string, string> = {
  content_profile: "exemplars",
  exemplars_bank: "exemplars",
  knowledge_graph: "corpus",
};

export function Dashboard() {
  const pipeline = usePipeline();
  const raw = useRaw();
  const { navigate } = useRouter();

  if (pipeline.isLoading) {
    return (
      <div className="grid gap-4 lg:grid-cols-3">
        <Skeleton className="h-56" />
        <Skeleton className="h-56" />
        <Skeleton className="h-56" />
      </div>
    );
  }

  const stages = pipeline.data?.stages ?? [];
  const unlocked = pipeline.data?.generation_unlocked ?? false;
  const next = stages.find((s) => s.status !== "approved");
  const emptySlots = (raw.data?.slots ?? []).filter((slot) => slot.files.length === 0);
  const rawMissingFor = (artifact: string) =>
    emptySlots.find((slot) => slot.kind === RAW_FOR[artifact])?.label ?? null;

  return (
    <div className="space-y-6">
      <header className="flex items-center gap-2">
        <h1 className="text-xl font-semibold tracking-tight">Panel</h1>
        <InfoHint label="Cómo funciona la cadena">
          Cada artefacto se construye, se revisa y se aprueba antes de desbloquear el siguiente.
          Se revisa una vez al principio; después se generan variantes contra una instancia
          congelada.
        </InfoHint>
      </header>

      {emptySlots.length > 0 ? (
        <Alert tone="warning" title="Faltan datos en bruto">
          <p>
            {emptySlots.map((slot) => slot.label).join(" y ")} no{" "}
            {emptySlots.length > 1 ? "tienen" : "tiene"} ningún documento. Impórtalos aquí abajo:
            son la materia prima de la que se construye toda la cadena.
          </p>
        </Alert>
      ) : null}

      <RawSection />

      {next ? (
        <Alert
          tone="info"
          title={`Siguiente paso: ${next.label}`}
          action={
            <Button size="sm" onClick={() => navigate(SCREEN[next.artifact])}>
              Ir
              <ArrowRight />
            </Button>
          }
        >
          <p>
            {next.blocked_reason ??
              (next.status === "missing"
                ? "Todavía no existe: hay que construirlo."
                : "Existe pero no está aprobado.")}
          </p>
        </Alert>
      ) : (
        <Alert
          tone="success"
          title="Cadena aprobada de principio a fin"
          action={
            <Button size="sm" onClick={() => navigate("/generar")}>
              Generar
              <ArrowRight />
            </Button>
          }
        />
      )}

      <div className="grid gap-4 lg:grid-cols-4">
        <div className="grid content-start gap-4 lg:col-span-3 xl:grid-cols-3">
          {stages.map((stage, index) => (
            <StageCard
              key={stage.artifact}
              stage={stage}
              index={index}
              rawMissing={rawMissingFor(stage.artifact)}
            />
          ))}
        </div>
        <div className="space-y-4">
          <SystemCard />
          <Card className={cn(!unlocked && "opacity-70")}>
            <CardHeader className="pb-2">
              <CardTitle>Generación</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {unlocked ? null : (
                <p className="flex items-center gap-1.5 text-sm text-muted-foreground">
                  <Lock className="size-3.5" />
                  Requiere las tres etapas aprobadas.
                </p>
              )}
              <Button className="w-full" disabled={!unlocked} onClick={() => navigate("/generar")}>
                <ArrowRight />
                Ir a generar
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>

      {pipeline.data?.current_job ? (
        <p className="text-xs text-muted-foreground">
          Trabajo en curso: {pipeline.data.current_job.label} ·{" "}
          {duration(pipeline.data.current_job.elapsed_ms)}
          {pipeline.data.queued > 0 ? ` · ${pipeline.data.queued} en cola` : ""}
        </p>
      ) : null}
    </div>
  );
}
