import { useMutation } from "@tanstack/react-query";
import {
  ArrowRight,
  CircleCheck,
  CircleDashed,
  Cpu,
  Hammer,
  Lock,
  Pencil,
  Server,
  TriangleAlert,
} from "lucide-react";

import { StageBadge } from "@/components/StageGate";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { InfoHint } from "@/components/ui/hint";
import { Alert, Separator, Skeleton, Spinner } from "@/components/ui/misc";
import { api } from "@/lib/api";
import { duration, when } from "@/lib/format";
import { Link, useRouter } from "@/lib/router";
import type { StageState } from "@/lib/types";
import { cn } from "@/lib/utils";
import { useHealth, useInvalidateChain, usePipeline, useSubmitJob } from "@/state/queries";

const SCREEN: Record<string, string> = {
  content_profile: "/preparar/perfil",
  knowledge_graph: "/preparar/grafo",
  exemplars_bank: "/preparar/banco",
};

const EXPLAIN: Record<string, string> = {
  content_profile:
    "Define el esquema de un ítem y las guías de extracción y generación. Se infiere de una muestra de los ejemplares en bruto.",
  knowledge_graph:
    "El vocabulario de conceptos y dominios. Es la única fuente de conceptos que podrá usarse después: nada fuera de aquí puede etiquetarse ni generarse.",
  exemplars_bank:
    "Los ítems extraídos de los documentos, etiquetados con conceptos del grafo. Alimentan los ejemplos few-shot de la generación.",
};

function StageCard({ stage, index }: { stage: StageState; index: number }) {
  const submit = useSubmitJob();
  const blocked = Boolean(stage.blocked_reason);
  const missing = stage.status === "missing";

  return (
    <Card
      className={cn(
        "relative transition-colors",
        stage.status === "approved" && "border-[color-mix(in_oklch,var(--success)_45%,var(--border))]",
        stage.status === "stale" && "border-destructive/50",
        blocked && "opacity-70",
      )}
    >
      <CardHeader className="pb-2">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "flex size-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold",
              stage.status === "approved"
                ? "bg-[var(--success)] text-background"
                : "bg-muted text-muted-foreground",
            )}
          >
            {stage.status === "approved" ? <CircleCheck className="size-3.5" /> : index + 1}
          </span>
          <div className="flex flex-1 items-center gap-1.5">
            <CardTitle>{stage.label}</CardTitle>
            <InfoHint label={`Qué es ${stage.label}`}>{EXPLAIN[stage.artifact]}</InfoHint>
          </div>
          <StageBadge stage={stage} />
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        {stage.is_autogenerated ? (
          <p className="flex items-center gap-1.5 text-xs text-[var(--warning)]">
            <TriangleAlert className="size-3.5" />
            Borrador autogenerado, sin curar.
          </p>
        ) : null}

        {stage.stale_because.length > 0 ? (
          <div className="space-y-1 rounded-md border border-destructive/40 bg-destructive/10 p-2">
            {stage.stale_because.map((cause) => (
              <p key={cause.artifact} className="text-xs text-destructive">
                {cause.reason}
              </p>
            ))}
          </div>
        ) : null}

        {blocked ? (
          <p className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Lock className="size-3.5" />
            {stage.blocked_reason}
          </p>
        ) : null}

        {stage.approved_at && stage.status === "approved" ? (
          <p className="text-xs text-muted-foreground">Aprobado el {when(stage.approved_at)}</p>
        ) : null}

        <div className="flex flex-wrap gap-2 pt-1">
          {missing ? (
            <Button
              size="sm"
              disabled={blocked || submit.isPending}
              onClick={() => submit.mutate({ kind: stage.build_job })}
            >
              <Hammer />
              Construir
            </Button>
          ) : (
            <Link to={SCREEN[stage.artifact]}>
              <Button size="sm" variant={stage.status === "approved" ? "outline" : "default"} disabled={blocked}>
                <Pencil />
                {stage.status === "approved" ? "Revisar de nuevo" : "Revisar"}
              </Button>
            </Link>
          )}
          {!missing ? (
            <Button
              size="sm"
              variant="ghost"
              disabled={blocked || submit.isPending}
              onClick={() => submit.mutate({ kind: stage.build_job })}
              title="Vuelve a ejecutar el constructor sobre los datos en bruto"
            >
              <Hammer />
              Reconstruir
            </Button>
          ) : null}
        </div>
      </CardContent>
    </Card>
  );
}

function SystemCard() {
  const health = useHealth();
  const invalidate = useInvalidateChain();
  const index = useMutation({
    mutationFn: () => api.submitJob("index", {}, true),
    onSuccess: invalidate,
  });

  if (health.isLoading) return <Skeleton className="h-40" />;
  if (!health.data) {
    return (
      <Alert tone="danger" title="Sin servidor">
        <p>La API no responde en el puerto 8000.</p>
      </Alert>
    );
  }

  const { available, host, models, context_ready, paths } = health.data;

  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center gap-2">
          <Server className="size-4 text-muted-foreground" />
          Sistema
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        <div className="flex items-center justify-between gap-2">
          <span className="text-muted-foreground">Motor de inferencia</span>
          <span className="flex items-center gap-1.5">
            <span
              className={cn(
                "size-1.5 rounded-full",
                available ? "bg-[var(--success)]" : "bg-destructive",
              )}
            />
            <code className="font-mono text-xs">{host}</code>
          </span>
        </div>

        <div className="flex items-start justify-between gap-2">
          <span className="text-muted-foreground">Modelos</span>
          <div className="text-right">
            {models.missing.length === 0 ? (
              <Badge variant="success">{Object.keys(models.required).length} disponibles</Badge>
            ) : (
              <div className="space-y-1">
                {models.missing.map((model) => (
                  <Badge key={model} variant="danger" className="block">
                    falta {model}
                  </Badge>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="flex items-center justify-between gap-2">
          <span className="flex items-center gap-1.5 text-muted-foreground">
            Índices en memoria
            <InfoHint label="Qué son los índices en memoria">
              Los embeddings del grafo y del banco, cargados en RAM. En frío, el primer trabajo
              que los necesite paga la carga; calentarlos la adelanta.
            </InfoHint>
          </span>
          {context_ready ? (
            <Badge variant="success">Calientes</Badge>
          ) : (
            <div className="flex items-center gap-2">
              <Badge variant="outline">Fríos</Badge>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => index.mutate()}
                disabled={index.isPending || !available}
              >
                {index.isPending ? <Spinner /> : <Cpu />}
                Calentar
              </Button>
            </div>
          )}
        </div>

        <Separator />

        <div className="space-y-1 text-xs text-muted-foreground">
          <p className="flex items-center gap-1.5">
            {paths.raw_exemplars_exists ? (
              <CircleCheck className="size-3.5 text-[var(--success)]" />
            ) : (
              <CircleDashed className="size-3.5" />
            )}
            <span className="font-mono">{paths.raw_exemplars}</span>
          </p>
          <p className="flex items-center gap-1.5">
            {paths.raw_corpus_exists ? (
              <CircleCheck className="size-3.5 text-[var(--success)]" />
            ) : (
              <CircleDashed className="size-3.5" />
            )}
            <span className="font-mono">{paths.raw_corpus}</span>
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

export function Dashboard() {
  const pipeline = usePipeline();
  const { navigate } = useRouter();

  if (pipeline.isLoading) {
    return (
      <div className="grid gap-4 lg:grid-cols-3">
        <Skeleton className="h-56" />
        <Skeleton className="h-56" />
        <Skeleton className="h-56" />
      </div>
    );
  }

  const stages = pipeline.data?.stages ?? [];
  const unlocked = pipeline.data?.generation_unlocked ?? false;
  const next = stages.find((s) => s.status !== "approved");

  return (
    <div className="space-y-6">
      <header className="flex items-center gap-2">
        <h1 className="text-xl font-semibold tracking-tight">Panel</h1>
        <InfoHint label="Cómo funciona la cadena">
          Cada artefacto se construye, se revisa y se aprueba antes de desbloquear el siguiente.
          Se revisa una vez al principio; después se generan variantes contra una instancia
          congelada.
        </InfoHint>
      </header>

      {next ? (
        <Alert
          tone="info"
          title={`Siguiente paso: ${next.label}`}
          action={
            <Button size="sm" onClick={() => navigate(SCREEN[next.artifact])}>
              Ir
              <ArrowRight />
            </Button>
          }
        >
          <p>
            {next.blocked_reason ??
              (next.status === "missing"
                ? "Todavía no existe: hay que construirlo."
                : "Existe pero no está aprobado.")}
          </p>
        </Alert>
      ) : (
        <Alert
          tone="success"
          title="Cadena aprobada de principio a fin"
          action={
            <Button size="sm" onClick={() => navigate("/generar")}>
              Generar
              <ArrowRight />
            </Button>
          }
        />
      )}

      <div className="grid gap-4 lg:grid-cols-4">
        <div className="grid content-start gap-4 lg:col-span-3 xl:grid-cols-3">
          {stages.map((stage, index) => (
            <StageCard key={stage.artifact} stage={stage} index={index} />
          ))}
        </div>
        <div className="space-y-4">
          <SystemCard />
          <Card className={cn(!unlocked && "opacity-70")}>
            <CardHeader className="pb-2">
              <CardTitle>Generación</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {unlocked ? null : (
                <p className="flex items-center gap-1.5 text-sm text-muted-foreground">
                  <Lock className="size-3.5" />
                  Requiere las tres etapas aprobadas.
                </p>
              )}
              <Button className="w-full" disabled={!unlocked} onClick={() => navigate("/generar")}>
                <ArrowRight />
                Ir a generar
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>

      {pipeline.data?.current_job ? (
        <p className="text-xs text-muted-foreground">
          Trabajo en curso: {pipeline.data.current_job.label} ·{" "}
          {duration(pipeline.data.current_job.elapsed_ms)}
          {pipeline.data.queued > 0 ? ` · ${pipeline.data.queued} en cola` : ""}
        </p>
      ) : null}
    </div>
  );
}
