import { CircleCheck, Lock, RotateCcw, TriangleAlert, UploadCloud } from "lucide-react";
import type { ReactNode } from "react";

import { BuildButton, type BuildLabels } from "@/components/BuildButton";
import { BuildProgress } from "@/components/BuildProgress";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { InfoHint } from "@/components/ui/hint";
import { Alert, Spinner } from "@/components/ui/misc";
import { api } from "@/lib/api";
import { ARTIFACT_STATUS, when } from "@/lib/format";
import { Link } from "@/lib/router";
import type { StageState } from "@/lib/types";
import { useInvalidateChain, useRawMissingFor } from "@/state/queries";
import { useMutation } from "@tanstack/react-query";

export function StageBadge({ stage }: { stage: StageState }) {
  const meta = ARTIFACT_STATUS[stage.status];
  return <Badge variant={meta.tone as never}>{meta.label}</Badge>;
}

/**
 * A stage is visible before it is available, and says exactly why it is not.
 * A disabled control with no explanation is the thing this screen exists to avoid.
 *
 * What the stage *is* goes behind the (i) next to the title; what is wrong with it
 * right now stays on the page, because that is the part you have to act on.
 */
export function StageGate({
  stage,
  title,
  description,
  actions,
  buildLabels,
  livePreview,
  children,
}: {
  stage: StageState | undefined;
  title: string;
  description: ReactNode;
  actions?: ReactNode;
  buildLabels?: BuildLabels;
  /** Lo que el constructor está escribiendo AHORA, bajo la barra. No es el artefacto que
   *  se va a reemplazar —eso sigue oculto— sino el que está saliendo. */
  livePreview?: ReactNode;
  children: ReactNode;
}) {
  const invalidate = useInvalidateChain();
  const rawMissing = useRawMissingFor(stage?.artifact);
  const approve = useMutation({
    mutationFn: () => api.approve(stage!.artifact),
    onSuccess: invalidate,
  });
  const reopen = useMutation({
    mutationFn: () => api.reopen(stage!.artifact),
    onSuccess: invalidate,
  });

  if (!stage) {
    return (
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Spinner /> Cargando estado de la cadena…
      </div>
    );
  }

  const blocked = Boolean(stage.blocked_reason);
  const building = stage.status === "building";
  const missing = stage.status === "missing";
  const ready = !building && !missing;

  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-semibold tracking-tight">{title}</h1>
            <InfoHint label={`Qué es ${title}`}>{description}</InfoHint>
            <StageBadge stage={stage} />
            {/* Un borrador no es un defecto: puede estar bien tal cual. El distintivo dice
                de dónde sale el fichero que se está leyendo, y lo dice él solo — la (i) que
                lo acompañaba repetía el mismo aviso a dos centímetros del distintivo. */}
            {stage.is_autogenerated ? (
              <Badge
                variant="outline"
                title="Se está leyendo el fichero del constructor; al guardar cualquier cambio pasa al fichero curado"
              >
                autogenerado
              </Badge>
            ) : null}
          </div>
        </div>

        <div className="flex shrink-0 items-center gap-2">
          {actions}
          {building ? null : <BuildButton stage={stage} labels={buildLabels} />}
          {ready && !blocked ? (
            stage.status === "approved" ? (
              <Button variant="outline" onClick={() => reopen.mutate()} disabled={reopen.isPending}>
                <RotateCcw />
                Reabrir
              </Button>
            ) : (
              <Button onClick={() => approve.mutate()} disabled={approve.isPending}>
                <CircleCheck />
                Aprobar
              </Button>
            )
          ) : null}
        </div>
      </header>

      {stage.status === "approved" && stage.approved_at ? (
        <p className="text-xs text-muted-foreground">Aprobado el {when(stage.approved_at)}.</p>
      ) : null}

      {stage.stale_because.length > 0 ? (
        <Alert tone="danger" title="Obsoleto">
          {stage.stale_because.map((cause) => (
            <p key={cause.artifact}>{cause.reason}</p>
          ))}
        </Alert>
      ) : null}

      {blocked ? (
        <Alert tone="warning" title="Bloqueado">
          <p className="flex items-center gap-1.5">
            <Lock className="size-3.5" />
            {stage.blocked_reason}
          </p>
        </Alert>
      ) : null}

      {/* Solo queda el aviso que dice algo que la cabecera no dice ya: que la materia
          prima no está, y dónde se sube. El otro era «Sin construir» + un segundo botón de
          construir, con el distintivo y el botón de la cabecera a un palmo — dos bloques
          para una acción que es una. El botón de la cabecera se explica solo: cuando falta
          el corpus se deshabilita y su tooltip dice exactamente eso. */}
      {missing && rawMissing ? (
        <Alert
          tone="warning"
          title="Faltan los datos de partida"
          action={
            <Link to="/">
              <Button size="sm" variant="outline">
                <UploadCloud />
                Importar
              </Button>
            </Link>
          }
        >
          <p>
            «{rawMissing}» no tiene ningún documento, y es la materia prima de{" "}
            {stage.label.toLowerCase()}. Impórtalos desde el panel y vuelve aquí.
          </p>
        </Alert>
      ) : null}

      {/* Una etapa sin construir no tiene contenido, y pedírselo a la pantalla es pedirle
          que lea un fichero que no existe: el banco contestaba con un 404 y lo pintaba como
          un error rojo, con los esqueletos latiendo detrás, mientras el grafo y el perfil
          simplemente no pintaban nada. Aquí no hay nada roto — falta un paso — así que la
          cabecera, con su distintivo «Sin construir» y su botón, es todo lo que se ve.

          Mientras se reconstruye, el artefacto anterior desaparece de la pantalla: lo que
          hay en ella dejaría de ser lo que se está mirando en cuanto termine, y editarlo
          sería trabajar sobre algo a punto de ser sobrescrito. No se borra nada — el
          fichero sigue en disco hasta que el constructor lo reemplace — así que cancelar
          lo devuelve tal cual estaba, y por eso se dice aquí en vez de dejarlo suponer. */}
      {building ? (
        <>
          <Alert tone="info" title="Construyendo una versión nueva">
            <p>
              {stage.label} deja de mostrarse mientras dura la construcción. El que hay
              ahora sigue guardado: si cancelas, vuelve tal cual. Solo se reemplaza cuando
              el nuevo termina.
            </p>
          </Alert>
          <BuildProgress artifact={stage.artifact} />
          {livePreview}
        </>
      ) : missing ? null : (
        <div className={blocked ? "pointer-events-none select-none opacity-45" : undefined}>
          {children}
        </div>
      )}
    </div>
  );
}

export function StaleWarning({ children }: { children: ReactNode }) {
  return (
    <Alert tone="warning">
      <p className="flex items-start gap-1.5">
        <TriangleAlert className="mt-0.5 size-3.5 shrink-0" />
        <span>{children}</span>
      </p>
    </Alert>
  );
}
