import { CircleCheck, Lock, RotateCcw, TriangleAlert } from "lucide-react";
import type { ReactNode } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Alert, Spinner } from "@/components/ui/misc";
import { api } from "@/lib/api";
import { ARTIFACT_STATUS, when } from "@/lib/format";
import type { StageState } from "@/lib/types";
import { useInvalidateChain } from "@/state/queries";
import { useMutation } from "@tanstack/react-query";

export function StageBadge({ stage }: { stage: StageState }) {
  const meta = ARTIFACT_STATUS[stage.status];
  return <Badge variant={meta.tone as never}>{meta.label}</Badge>;
}

/**
 * A stage is visible before it is available, and says exactly why it is not.
 * A disabled control with no explanation is the thing this screen exists to avoid.
 */
export function StageGate({
  stage,
  title,
  description,
  actions,
  children,
}: {
  stage: StageState | undefined;
  title: string;
  description: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
}) {
  const invalidate = useInvalidateChain();
  const approve = useMutation({
    mutationFn: () => api.approve(stage!.artifact),
    onSuccess: invalidate,
  });
  const reopen = useMutation({
    mutationFn: () => api.reopen(stage!.artifact),
    onSuccess: invalidate,
  });

  if (!stage) {
    return (
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Spinner /> Cargando estado de la cadena…
      </div>
    );
  }

  const blocked = Boolean(stage.blocked_reason);
  const ready = stage.status !== "missing" && stage.status !== "building";

  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-semibold tracking-tight">{title}</h1>
            <StageBadge stage={stage} />
            {stage.is_autogenerated ? (
              <Badge variant="warning" title="Se está usando el borrador autogenerado">
                autogenerado
              </Badge>
            ) : null}
          </div>
          <p className="mt-1 max-w-3xl text-sm text-muted-foreground">{description}</p>
          {stage.path ? (
            <p className="mt-1 font-mono text-xs text-muted-foreground">{stage.path}</p>
          ) : null}
        </div>

        <div className="flex shrink-0 items-center gap-2">
          {actions}
          {ready && !blocked ? (
            stage.status === "approved" ? (
              <Button variant="outline" onClick={() => reopen.mutate()} disabled={reopen.isPending}>
                <RotateCcw />
                Reabrir
              </Button>
            ) : (
              <Button onClick={() => approve.mutate()} disabled={approve.isPending}>
                <CircleCheck />
                Aprobar
              </Button>
            )
          ) : null}
        </div>
      </header>

      {stage.status === "approved" && stage.approved_at ? (
        <p className="text-xs text-muted-foreground">Aprobado el {when(stage.approved_at)}.</p>
      ) : null}

      {stage.stale_because.length > 0 ? (
        <Alert tone="danger" title="Este artefacto quedó obsoleto">
          {stage.stale_because.map((cause) => (
            <p key={cause.artifact}>{cause.reason}</p>
          ))}
        </Alert>
      ) : null}

      {blocked ? (
        <Alert tone="warning" title="Etapa bloqueada">
          <p className="flex items-center gap-1.5">
            <Lock className="size-3.5" />
            {stage.blocked_reason}
          </p>
        </Alert>
      ) : null}

      {stage.status === "missing" ? (
        <Alert tone="info" title="Todavía no existe">
          <p>Construye este artefacto para poder revisarlo.</p>
        </Alert>
      ) : null}

      {stage.status === "building" ? (
        <Alert tone="info" title="Construyéndose ahora">
          <p>Abre el panel de ejecución para ver el progreso.</p>
        </Alert>
      ) : null}

      <div className={blocked ? "pointer-events-none select-none opacity-45" : undefined}>
        {children}
      </div>
    </div>
  );
}

export function StaleWarning({ children }: { children: ReactNode }) {
  return (
    <Alert tone="warning">
      <p className="flex items-start gap-1.5">
        <TriangleAlert className="mt-0.5 size-3.5 shrink-0" />
        <span>{children}</span>
      </p>
    </Alert>
  );
}
