import json

from loguru import logger

from .. import config
from ..core import inference
from ..core.repair import parse_with_repair
from ..core.workspace import Workspace
from ..instance.content_context import CANONICAL_KEYS, NARRATIVE_KEY, ContentContext, load_for
from ..prompts import synthesize_content_context_prompt

CONTENT_CONTEXT_SCHEMA = {
    "type": "object",
    "properties": {
        NARRATIVE_KEY: {"type": "string"},
        **{key: {"type": "string"} for key in CANONICAL_KEYS},
    },
    "required": [NARRATIVE_KEY, *CANONICAL_KEYS],
    "additionalProperties": False,
}


# Constrained and with thinking off, like `concept_description_prompt`: grammar and
# reasoning are not compatible on this stack, and with the channel closed a reasoning model
# deliberates into the answer -- which here would be indexed as if it were the subject.
def synthesize(
    ws: Workspace,
    evidence_block: str,
    source_label: str,
    model: str,
) -> ContentContext | None:
    current = load_for(ws)
    prompt = synthesize_content_context_prompt(
        current_block=current.prompt_block(),
        evidence_block=evidence_block.strip(),
        source_label=source_label,
        max_chars=config.CONTENT_CONTEXT_MAX_CHARS,
    )
    response = inference.generate(
        model=model,
        prompt=prompt,
        think=False,
        temperature=config.TEMPERATURE_DETERMINISTIC,
        format=CONTENT_CONTEXT_SCHEMA,
    ).response
    parsed, error = parse_with_repair(
        response,
        _parse,
        config.REPAIR_LLM,
        config.MAX_JSON_REPAIR_TRIES,
        shape='{"narrative": "…", "subject": "…", '
        '"educational_level": "…", "language_of_instruction": "…"}',
        format=CONTENT_CONTEXT_SCHEMA,
    )
    if parsed is None:
        logger.warning(
            f"No se pudo sintetizar el contexto de la asignatura ({error}); "
            "se conserva el que había"
        )
        return None

    synthesized = ContentContext(
        {
            NARRATIVE_KEY: str(parsed.get(NARRATIVE_KEY, "")),
            **{key: str(parsed.get(key, "") or "") for key in CANONICAL_KEYS},
        }
    )
    # The cap is stated in the prompt and enforced here, because a prompt is a request.
    # Trimmed on a sentence boundary: half a clause interpolated into every prompt of the
    # system reads as a corrupted file, not as a long one.
    synthesized.narrative = _clip(synthesized.narrative, config.CONTENT_CONTEXT_MAX_CHARS)

    # Always the DRAFT. The curated file is what a person wrote and what wins on read, and
    # a build that overwrote it would be the drift this pair exists to stop.
    synthesized.save(ws.content_context_autogenerated_path)
    logger.success(
        f"Contexto de la asignatura sintetizado desde {source_label.lower()}: "
        f"«{synthesized.subject or 'materia sin declarar'}», "
        f"{len(synthesized.narrative)} caracteres"
    )
    if ws.content_context_path.is_file():
        logger.info(
            f"Hay un contexto curado ({ws.content_context_path.name}); sigue mandando él. "
            f"La síntesis queda en {ws.content_context_autogenerated_path.name}"
        )
    return synthesized


def _parse(response: str) -> tuple[dict | None, str | None]:
    try:
        data = json.loads(response)
    except json.JSONDecodeError as e:
        return None, str(e)
    if not isinstance(data, dict):
        return None, f"expected an object, got {type(data).__name__}"
    if not str(data.get(NARRATIVE_KEY, "")).strip():
        return None, f"'{NARRATIVE_KEY}' is missing or empty"
    return data, None


# Sentence first, word second, character never. This text is interpolated into every
# prompt of the system, and a clause cut in half reads as a corrupted file rather than as
# a long one -- the same reason `extraction.excerpt` cuts by paragraphs.
def _clip(text: str, limit: int) -> str:
    text = text.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    stop = cut.rfind(".")
    if stop > 0:
        return cut[: stop + 1].strip()
    space = cut.rfind(" ")
    return (cut[:space] if space > 0 else cut).strip() + "…"
