import json
import re
from pathlib import Path

from json_repair import repair_json
from loguru import logger

from .. import config, inference, progress
from ..content_profile import ContentProfile
from ..prompts import (
    infer_content_profile_prompt,
    json_repair_prompt,
    repair_content_profile_prompt,
)
from . import _source_docs


BUILD_PHASES = (
    ("sample", "Leyendo una muestra del corpus", 30),
    ("infer", "Infiriendo el esquema de un ítem", 70),
)


class ContentProfileBuilder:
    FIELD_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

    def __init__(
        self,
        model: str = config.CONTENT_PROFILE_BUILDER_LLM,
        verbose: bool = True,
    ):
        self.model = model
        self.budget = config.SCHEMA_INFERENCE_BUDGET
        self.max_repair_attempts = config.MAX_JSON_REPAIR_TRIES

        logger.enable(__name__) if verbose else logger.disable(__name__)

        self._docling = _source_docs.default_converter()

    # PUBLIC API ----------------------------------------------------------------------------------

    def build(self, input_dir: str, output_file_path: str) -> dict:
        files = _source_docs.list_source_files(input_dir)
        if not files:
            logger.error(f"No supported files found in: {input_dir}")
            return {}

        logger.info(f"Found {len(files)} file(s) - inferring content profile")
        progress.phase("sample", f"0/{len(files)} documento(s)")
        with progress.step("sample", "Leyendo una muestra del corpus", len(files)):
            sample = self._gather_sample(files)
        if not sample.strip():
            logger.error("No content extracted from any file")
            return {}

        progress.phase("infer", f"{len(sample):,} caracteres de muestra en una sola llamada")
        with progress.step("infer_profile", "Infiriendo el perfil de contenido"):
            profile = self._infer(sample)
        progress.advance(1.0)
        if not profile:
            logger.error("Could not produce a content profile draft")
            return {}

        _source_docs.save_json(profile, output_file_path)
        try:
            ContentProfile(output_file_path)
            logger.success(f"Autogenerated content profile → {output_file_path} (loads cleanly)")
        except Exception as e:
            logger.warning(
                f"Autogenerated content profile → {output_file_path} — "
                f"needs manual fixes before it loads: {e}"
            )
        return profile

    # SAMPLING ------------------------------------------------------------------------------------

    # Schema variety comes from breadth (every document's shape), not volume: use the whole
    # corpus when it fits the budget, otherwise take leading whole blocks from each document so
    # all are represented and no item is truncated mid-way.
    def _gather_sample(self, files: list[Path]) -> str:
        per_doc: list[tuple[str, list[str]]] = []
        for idx, file_path in enumerate(files, 1):
            progress.checkpoint()
            progress.tick("sample", idx, len(files), detail=file_path.name)
            progress.advance((idx - 1) / len(files), f"{file_path.name} ({idx}/{len(files)})")
            try:
                content = _source_docs.to_markdown(self._docling, file_path)
            except RuntimeError as e:
                logger.exception(f"[{file_path.name}] skipped: {e}")
                continue
            blocks = _source_docs.split_blocks(content)
            if blocks:
                per_doc.append((file_path.stem, blocks))

        if not per_doc:
            return ""

        total = sum(len(b) for _, blocks in per_doc for b in blocks)
        if total <= self.budget:
            logger.info(
                f"Corpus fits budget ({total:,} ≤ {self.budget:,} chars) - using all content"
            )
            chosen = per_doc
        else:
            share = max(1, self.budget // len(per_doc))
            logger.info(
                f"Corpus exceeds budget ({total:,} > {self.budget:,} chars) - "
                f"sampling ~{share:,} chars from each of {len(per_doc)} document(s)"
            )
            chosen = [(name, self._head_blocks(blocks, share)) for name, blocks in per_doc]

        sections = [
            f"===== DOCUMENTO: {name} =====\n\n" + "\n\n---\n\n".join(blocks)
            for name, blocks in chosen
        ]
        return "\n\n".join(sections)

    @staticmethod
    def _head_blocks(blocks: list[str], share: int) -> list[str]:
        picked, size = [], 0
        for b in blocks:
            if picked and size + len(b) > share:
                break
            picked.append(b)
            size += len(b)
        return picked

    # INFERENCE -----------------------------------------------------------------------------------

    def _infer(self, sample: str) -> dict:
        prompt = infer_content_profile_prompt(sample)
        think = inference.supports_thinking(self.model)
        logger.info(f"Inferring with '{self.model}' (thinking {'on' if think else 'off'})")
        response = inference.generate(model=self.model, think=think, prompt=prompt).response
        profile = self._parse(response)
        err = self._validate(profile)

        for attempt in range(1, self.max_repair_attempts + 1):
            if err is None:
                break
            logger.warning(f"repair {attempt}/{self.max_repair_attempts}: {err}")
            if profile is None:
                repair_model = config.REPAIR_LLM
                repair_prompt = json_repair_prompt(
                    broken_output=response, error_msg=err, shape="objeto"
                )
            else:
                repair_model = self.model
                repair_prompt = repair_content_profile_prompt(
                    profile=json.dumps(profile, ensure_ascii=False, indent=2), error_msg=err
                )
            response = inference.generate(model=repair_model, prompt=repair_prompt).response
            candidate = self._parse(response)
            if candidate is not None:
                profile = candidate
            err = self._validate(profile)

        if profile is None:
            return {}
        if err is not None:
            logger.warning(f"Profile still invalid after repairs — saving draft anyway: {err}")
        return profile

    @classmethod
    def _parse(cls, response: str) -> dict | None:
        cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", response.strip())
        raw = repair_json(cleaned, return_objects=True)
        return raw if isinstance(raw, dict) and raw else None

    @classmethod
    def _validate(cls, profile: dict | None) -> str | None:
        if profile is None:
            return "top-level JSON is not an object"
        try:
            ContentProfile._validate(profile)
            invalid = [n for n in profile["fields"] if not cls.FIELD_NAME_RE.match(n)]
            if invalid:
                return (
                    f"field names must be english snake_case matching "
                    f"^[a-z][a-z0-9_]*$ — offending: {invalid}"
                )
            for spec in profile["fields"].values():
                ContentProfile._spec_to_field(spec)
            return None
        except (ValueError, KeyError, TypeError) as e:
            return f"{type(e).__name__}: {str(e)[:200]}"

